### PR TITLE
[GLUTEN-2961][VL][CORE] Decimal sum avg use row_constructor

### PR DESCRIPTION
**Pull request by liujiayi771**
## What changes were proposed in this pull request?

Decimal sum and avg have the meaning of overflow when the child field is null, and gluten's row_constructor_with_null cannot be used.

## How was this patch tested?
SPARK-28067: Aggregate sum should not return wrong results for decimal overflow
SPARK-35955: Aggregate avg should not return wrong results for decimal overflow

### CODE REVIEW

**Comment by liujiayi771** [comment]
@JkSelf Please take a look.

**Review by JkSelf — APPROVED** [review]
LGTM

**Comment by JkSelf** [comment]
@liujiayi771 Can you help to rebase? Thanks.

**Comment by liujiayi771** [comment]
> @liujiayi771 Can you help to rebase? Thanks.

Done.

**Pull request merged**
