### PR TITLE
[GLUTEN-1407] Let profile control shim version

### LINKED ISSUE #1407: Gluten still depends on Spark32 shims when build with -Pspark-3.3
**Describe the bug**
When run gluten-it with Spark3.3, maven build failed due to `io.glutenproject:spark-sql-columnar-shims-spark32:jar:0.5.0-SNAPSHOT` not found.

**To Reproduce**
```
cd <GLUTEN_HOME>
mvn clean install -Pspark-3.3 -Pbackends-velox -DskipTests
cd tools/gluten-it
mvn clean package -Pspark-3.3
```

mvn clean package -Pspark-3.3 -X
```
[DEBUG] io.glutenproject:gluten-it:jar:1.0-SNAPSHOT
[DEBUG]    io.glutenproject:gluten-package:jar:0.5.0-SNAPSHOT:compile
[DEBUG]       io.glutenproject:gluten-core:jar:0.5.0-SNAPSHOT:compile
[DEBUG]          io.glutenproject:spark-sql-columnar-shims-spark32:jar:0.5.0-SNAPSHOT:compile
[DEBUG]          io.glutenproject:spark-sql-columnar-shims-common:jar:0.5.0-SNAPSHOT:compile
[DEBUG]          com.google.protobuf:protobuf-java:jar:3.16.3:compile
[DEBUG]          com.google.protobuf:protobuf-java-util:jar:3.16.3:compile
[DEBUG]             com.google.code.gson:gson:jar:2.8.6:compile
```

**Problem**
https://github.com/oap-project/gluten/blob/c156453883eafd7958b725a24391ba57d2e63ba6/pom.xml#L106

**Why CI not reproduce?**
CI install spark32 and spark33 first, so gluten-it could pass.

I will fix it.

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

Fixes #1407 

## How was this patch tested?

manual tests.

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by Yohahaha** [comment]
CI failed due to `apt update`
```
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

**Comment by Yohahaha** [comment]
Hi @zhouyuan @zhejiangxiaomai  could you help review this?

**Comment by zhejiangxiaomai** [comment]
cc: @zhztheplayer

**Comment by PHILO-HE** [comment]
It looks the shim version is not correctly set according to profile in building the gluten-it module. Not sure the fundamental reason. Anyway, this PR works also in my test.
Just re-triggered the failed CI job.

**Review by zhejiangxiaomai — APPROVED** [review]

**Pull request merged**
