### PR TITLE
Fix Spark Shim Provider not found for spark 3.3

### PR DESCRIPTION
**Pull request by izchen**
## What changes were proposed in this pull request?

After https://github.com/oap-project/gluten/pull/1030, all SQL functions of spark 3.3 do not work:

```
INFO SparkShimLoader: Loading Spark Shims for version: 3.3.1
java.lang.ExceptionInInitializerError
	at io.glutenproject.expression.ExpressionConverter$.replaceWithExpressionTransformer(ExpressionConverter.scala:34)
	at io.glutenproject.execution.ProjectExecTransformer.$anonfun$getRelNode$2(BasicPhysicalOperatorTransformer.scala:406)
	...
Caused by: java.lang.IllegalStateException: No Spark Shim Provider found for 3.3.1
	at io.glutenproject.sql.shims.SparkShimLoader$.loadSparkShimProvider(SparkShimLoader.scala:61)
	at io.glutenproject.sql.shims.SparkShimLoader$.getSparkShimProvider(SparkShimLoader.scala:76)
	at io.glutenproject.sql.shims.SparkShimLoader$.getSparkShims(SparkShimLoader.scala:32)
	at io.glutenproject.expression.ExpressionMappings$.<init>(ExpressionMappings.scala:377)
	at io.glutenproject.expression.ExpressionMappings$.<clinit>(ExpressionMappings.scala)
	...
```

`META-INF/services/io.glutenproject.sql.shims.SparkShimProvider` file of `spark-sql-columnar-shims-spark32` and `spark-sql-columnar-shims-spark33` overwrite each other and the file is written to  `gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar`.

## How was this patch tested?

Before this PR:

```
$ unzip -p ./package/target/gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar META-INF/services/io.glutenproject.sql.shims.SparkShimProvider

io.glutenproject.sql.shims.spark32.SparkShimProvider
```

After this PR:

```
$ unzip -p ./package/target/gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar META-INF/services/io.glutenproject.sql.shims.SparkShimProvider

io.glutenproject.sql.shims.spark33.SparkShimProvider
```

### CODE REVIEW

**Comment by zhztheplayer** [comment]
>$ unzip -p ./package/target/gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar META-INF/services/io.glutenproject.sql.shims.SparkShimProvider
>
>io.glutenproject.sql.shims.spark32.SparkShimProvider
>
>io.glutenproject.sql.shims.spark33.SparkShimProvider

Why 3.2 shim and 3.3 shim are both included in ./package/target/gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar ? Is this intended behaviour during building Gluten?

**Comment by izchen** [comment]
> Why 3.2 shim and 3.3 shim are both included in ./package/target/gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar ? Is this intended behaviour during building Gluten?

This is an unintended behavior that is due to the following behavior of maven-shade-plugin:

https://maven.apache.org/plugins/maven-shade-plugin/faq.html#two-executions

This issue occurs when there is no `mvn clean` between `mvn package -Pspark-3.2` and `mvn package -Pspark-3.3`

**Comment by izchen** [comment]
friendly ping @zhztheplayer  @FelixYBW  

In script `./dev/buildbundle-veloxbe.sh`, there is no `mvn clean` between mvn `package -Pspark-3.2` and mvn `package -Pspark-3.3`, so the output `gluten-spark3.3_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar` is wrong. Let's fix it.

**Comment by zhztheplayer** [comment]
@izchen Sorry I was just curious about your case when I left my previous comment. But can we use the original solution to merge the service files? Or you just prefer the current one? 

If we delete the compiled jars it could be better to delete them in maven **clean** phase. But I am not sure if it's possible.

**Comment by izchen** [comment]
@zhztheplayer Thanks for your comments!

> But can we use the original solution to merge the service files? Or you just prefer the current one?

As you said, we can merge `spark-sql-columnar-shims-spark32` and `spark-sql-columnar-shims-spark33` into the output jar in the future to match the Spark version at runtime. But the current implementation does not support doing merges because there are some files with the same package name, such as `JoinSelectionShim.scala`.

> If we delete the compiled jars it could be better to delete them in maven clean phase.

A better phase to remove package jar maybe `prepare-package`.

**Comment by zhouyuan** [comment]
related: https://github.com/oap-project/gluten/issues/1161

**Comment by FelixYBW** [comment]
> related: #1161

Can mvn clean solve the issue? Do we need the fix?

**Comment by izchen** [comment]
> > related: #1161
> 
> Can mvn clean solve the issue? Do we need the fix?

This fix is not needed if `./dev/buildbundle-veloxbe.sh` is the only way to package. But if someone packages directly using `mvn package` command, running the program will get a confusing error.

**Comment by zhejiangxiaomai** [comment]
Hello, @izchen  I merged a [PR#1177](https://github.com/oap-project/gluten/pull/1177) yesterday which should solve your problem. And I feel sorry that I didn't notice this PR before.

**Pull request closed without merging**
