### PR TITLE
[VL] Add a test for isnan function

### PR DESCRIPTION
**Pull request by zhli1142015**
## What changes were proposed in this pull request?

Add isnan support. Now only double is supported by velox, it should be an easy change to support float also.

## How was this patch tested?

UT.

### CODE REVIEW

**Comment by zhli1142015** [comment]
https://github.com/facebookincubator/velox/pull/8272

**Comment by PHILO-HE** [comment]
@zhli1142015, this pr should be pending until the velox pr is merged. Right?

**Comment by zhli1142015** [comment]
> Hi @zhli1142015, this pr should be pending until the velox pr is merged. Right?

I thought this can be merged to support double type only first, but I found different null behavior for double type input also, let's wait the velox pr merged.
Thanks.

**Comment by zhli1142015** [comment]
@PHILO-HE , could you help review this PR?

**Review by PHILO-HE — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
