### PR TITLE
[DOC] Fix links for [Build with Velox] and [Build with ClickHouse Backend]

### PR DESCRIPTION
**Pull request by kerwin-zk**
## What changes were proposed in this pull request?

Fix links for [Build with Velox] and [Build with ClickHouse Backend]

### CODE REVIEW

**Comment by winningsix** [comment]
@xieqi  FYI

**Review by jinchengchenghh — APPROVED** [review]

**Comment by zhouyuan** [comment]
@kerwin-zk as @dh20 find, there's another broken link, can you please help to fix it? 
https://github.com/oap-project/gluten/pull/1590

**Review by zhouyuan — APPROVED** [review]
👍

**Comment by zhouyuan** [comment]
@kerwin-zk @dh20 Thank you for the checking an fixes 👍

**Comment by dh20** [comment]
@zhouyuan Is there a communication group for the current Gluten project? Our company wants to apply this project, but some usage issues cannot be communicated.

**Pull request merged**
