### PR TITLE
[CH-187] Clickhouse backend support math functions

### PR DESCRIPTION
**Pull request by taiyang-li**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

close https://github.com/Kyligence/ClickHouse/issues/187

### CODE REVIEW

**Comment by lviiii** [comment]
@zhixingheyi-tian FYI

**Review by jinchengchenghh — APPROVED** [review]

**Comment by zhixingheyi-tian** [comment]
Some functions is same with #535 .
Can review together.
Thanks！

**Comment by zhixingheyi-tian** [comment]
Why only one  CI job?

**Comment by jinchengchenghh** [comment]
Maybe because `This branch has conflicts that must be resolved`

**Comment by taiyang-li** [comment]
> Some functions is same with #535 . Can review together. Thanks！

Already fix the conflicts based on your changes which is merged in main branch already.

Of course we can review together. BTW, do you think it is better for us to first list our plans in issue to avoid working on the same functions?

**Comment by zhixingheyi-tian** [comment]
> 

That's OK!

**Comment by zhixingheyi-tian** [comment]
> > Some functions is same with #535 . Can review together. Thanks！
> 
> Already fix the conflicts with main branch
> 
> Of course we can review together. BTW, do you think it is better for us to list the functions in issues in advance to avoid working on the same functions?

That's OK!

**Comment by zhixingheyi-tian** [comment]
Hi @taiyang-li @zzcclp 
How about merging  #535 firstly. Because #535 passed all CI jobs and new added UTs.

**Comment by taiyang-li** [comment]
@zhixingheyi-tian  I will merge it later.

**Comment by zhixingheyi-tian** [comment]
> @zhixingheyi-tian I will merge it later.

@taiyang-li , do you mean to merge #535  firstly?

**Comment by taiyang-li** [comment]
> > @zhixingheyi-tian I will merge it later.
> 
> @taiyang-li , do you mean to merge #535 firstly?

Yes. That's ok .

**Comment by lviiii** [comment]
@taiyang-li Please rebase and list failed UT, which UTs caused incorrect results with Vanilla Spark and which ones are functionality logic problems? I will add them into blacklist to avoid offloading these functions to Velox. Let's work together to merge this PR.

**Comment by taiyang-li** [comment]
> @taiyang-li Please rebase and list failed UT, which UTs caused incorrect results with Vanilla Spark and which ones are functionality logic problems? I will add them into blacklist to avoid offloading these functions to Velox (refer to #558 ). Let's work together to merge this PR.

Thanks a lot. Already rebased,  let's wait for the CI/CD.

**Comment by taiyang-li** [comment]
Found 2 bugs:
- https://github.com/Kyligence/ClickHouse/issues/199
- https://github.com/Kyligence/ClickHouse/issues/197, closed by https://github.com/Kyligence/ClickHouse/pull/198

**Comment by PHILO-HE** [comment]
We have enabled `bitwise_and` & `bitwise_or` in velox-backend, also with some scala code added for verification, see https://github.com/oap-project/gluten/commit/b426ecb97dd958bc96582efa629fa363ffa35145. Could you please rebase the patch? Thanks!

**Comment by taiyang-li** [comment]
> We have enabled `bitwise_and` & `bitwise_or` in velox-backend, also with some scala code added for verification, see [b426ecb](https://github.com/oap-project/gluten/commit/b426ecb97dd958bc96582efa629fa363ffa35145). Could you please rebase the patch? Thanks!

done. Thanks for reminding.

**Pull request merged**
