### PR TITLE
[CH][UT][Shim] Refactor: fix compile warnings and style issue

### PR DESCRIPTION
**Pull request by baibaichen**
## What changes were proposed in this pull request?

Currently, there are many warnings when compile gluten, for example:
1. unused imports in scala (scala fmt doesn't support remove unused imports)
2. unreach codes: it actually menas bug.
3. scala-style is broken.

This PR add  `-Xfatal-warnings` to treat warning as error to enforce fix compile warnnings.

1. add `-Xfatal-warnings` to treat warning as error
2. fix scalastyle-config.xml
3. add java spotless

## How was this patch tested?

Using existed UT.

### CODE REVIEW

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Review by zhztheplayer — APPROVED** [review]

**Pull request merged**
