### PR TITLE
[GLUTEN-1727][CORE]Fixed the exception which is caused by too many levels of nesting

### PR DESCRIPTION
**Pull request by lgbo-ustc**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

Fixes: #1727

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

 unit tests

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by lgbo-ustc** [comment]
@rui-mo @zzcclp to fixed the issue, we provide our compiled protobuf jar

**Comment by rui-mo** [comment]
Do we need to compile a protobuf in Gluten to fix this issue? @zhouyuan

**Comment by zhztheplayer** [comment]
> @rui-mo @zzcclp to fixed the issue, we provide our compiled protobuf jar

Same issue, how do we get the provided protobuf jar? @lgbo-ustc

**Comment by lgbo-ustc** [comment]
> > @rui-mo @zzcclp to fixed the issue, we provide our compiled protobuf jar
> 
> Same issue, how do we get the provided protobuf jar? @lgbo-ustc

compiled by ourself

**Comment by zhztheplayer** [comment]
> > > @rui-mo @zzcclp to fixed the issue, we provide our compiled protobuf jar
> > 
> > 
> > Same issue, how do we get the provided protobuf jar? @lgbo-ustc
> 
> Currently the pb jar has been a provided jar. see `package.sh`. we can compile the jar by ourself as needed

Let us clarify: Currently Spark provides protobuf jar in its classpath so in Gluten we don't need to specify protobuf jar as compilation dependency. Is that correct?

**Comment by zhztheplayer** [comment]
Another question: Did we try setting a larger limit number via `com.google.protobuf.CodedInputStream#setRecursionLimit` ?

**Comment by PHILO-HE** [comment]
> Another question: Did we try setting a larger limit number via `com.google.protobuf.CodedInputStream#setRecursionLimit` ? cc @rui-mo

It looks we cannot enlarge the limit number via `setRecursionLimit`.
I think it would be better to have a common fix, applicable to all users. Maybe, we need to let the project depend on a custom jar with recursion limit directly changed.

**Comment by PHILO-HE** [comment]
The custom protobuf has been prepared, but it is still in progress to upload the jar to maven repo. Stay tuned. Let's close this one. Thanks!

**Pull request closed without merging**
