### PR TITLE
[OPPRO-191] c++ codestyle follow velox codestyle

### PR DESCRIPTION
**Pull request by jinchengchenghh**
## What changes were proposed in this pull request?

change .clang-format, and format all files by this style

## How was this patch tested?

CI

### CODE REVIEW

**Comment by jinchengchenghh** [comment]
Can you help review? thanks!
@zhztheplayer

**Review by zhztheplayer — APPROVED** [review]
lgtm

@marin-ma @rui-mo I see you are actively working on some non-trivial PRs so please comment if you worry about rebasing issues after this.

**Comment by jinchengchenghh** [comment]
@marin-ma @rui-mo hi, I will merge this PR at 17:00, please notice me if I need to delay, thanks!

**Comment by marin-ma** [comment]
Thanks for your work. I'll rebase after this one get merged.

**Comment by rui-mo** [comment]
LGTM. Just started a Jenkins job for this PR.

**Comment by jinchengchenghh** [comment]
jenkins pass

**Comment by FelixYBW** [comment]
Should we run some tool like clang-format before we submit PR? Or it's automatic in some tools?

**Comment by jinchengchenghh** [comment]
vscode can use clang-format extension to format the code on save

**Pull request merged**
