### PR TITLE
[GLUTEN-1434][VL] Optimize shuffle get batch

### PR DESCRIPTION
**Pull request by jinchengchenghh**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Review by zhztheplayer — COMMENTED** [review]
@jinchengchenghh Can you explain a little bit about the optimization that the patch actually does? Thanks a lot.

**Comment by jinchengchenghh** [comment]
The function `from` will combine a 1 column ColumnarBatch(pid) and a several columns Columnarbatch(data), if the latter batch columns are too much, this will be a burden. The old function `addColumn` use `std::move(children)` to avoid generating all new children vector. @zhztheplayer

**Comment by zhztheplayer** [comment]
> if the latter batch columns are too much, this will be a burden.

Ideally it just brings some meta-data level copy-and-pastes out of the data. Is there some real performance regressions observed from your side?

**Comment by jinchengchenghh** [comment]
No, it may gain performance in user situation.

**Review by zhztheplayer — DISMISSED** [review]
I would not be against this but as an out-of-box observer of this code, it turn's to me that the codes slightly get more complex than it used to be since another flag `removePid` is introduced to the routine. Since we already had a `hasPid()` API in partitioner.

`VeloxColumnarBatch::from(..)` was added to centralize all the batch converting work to reduce the code complexity. If no performance regression is guaranteed to take place I would suggest doing performance optimization work only when it's really needed.

**Comment by zhztheplayer** [comment]
Would you like to rebase? Thanks.

**Comment by jinchengchenghh** [comment]
I optimize the code logic to remove `removePid`, the old logic is too complicated.

**Comment by jinchengchenghh** [comment]
For velox shuffle, we don't need Arrow schema_, do you think we should move to velox types? @zhztheplayer There may be a lot of code refactor.

**Review by zhztheplayer — APPROVED** [review]

**Comment by zhztheplayer** [comment]
>  For velox shuffle, we don't need Arrow schema_, do you think we should move to velox types? @zhztheplayer There may be a lot of code refactor.

By this did you mean using the current approach that infers schema from the first columnar batch?

**Pull request merged**
