### PR TITLE
[VL] Use a config to control coalesce batches

### PR DESCRIPTION
**Pull request by rui-mo**
## What changes were proposed in this pull request?

Use a config to control whether CoalesceBatches should be inserted.

## How was this patch tested?

Closes https://github.com/oap-project/gluten/issues/1468.

### CODE REVIEW

**Comment by zhouyuan** [comment]
@jinchengchenghh

**Review by jinchengchenghh — APPROVED** [review]

**Comment by jinchengchenghh** [comment]
I would remove Arrow, after shuffle write Velox RowVecter, I will remove CoalesceBatch operator

**Comment by rui-mo** [comment]
retest this please

**Review by PHILO-HE — APPROVED** [review]

**Comment by liuneng1994** [comment]
This PR beak clickhouse backend ci @rui-mo , I will revert it.

**Pull request merged**
