### PR TITLE
[CORE] Add arch suffix for package jar

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

Add arch suffix for package jar and thridparty-lib.jar

See https://github.com/trustin/os-maven-plugin/blob/master/README.md#property-osdetectedarch

### CODE REVIEW

**Comment by Yohahaha** [comment]
@PHILO-HE @zhouyuan could you help review this patch?

**Comment by PHILO-HE** [comment]
cc @baibaichen @exmy

**Comment by exmy** [comment]
LGTM

**Comment by PHILO-HE** [comment]
@zhouyuan, assume we need to change package name in internal test accordingly.

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Pull request merged**
