### PR TITLE
[OPPRO-213]update build_velox.sh

### PR DESCRIPTION
**Pull request by zhejiangxiaomai**
## What changes were proposed in this pull request?
Update velox_build.sh script. If we compile gluten with an existing repo, we need apply our change and compile option of the repo.

## How was this patch tested?
Test this script in two ways.

one way is build gluten with option " -Dbuild_velox_from_source=ON " 
 The full compiling command is 
`mvn clean package -Pbackends-velox -Pfull-scala-compiler -DskipTests -Dcheckstyle.skip -Dbuild_cpp=ON -Dbuild_velox=ON -Dbuild_velox_from_source=ON -Dbuild_arrow=OFF -D build_protobuf=OFF`

another is  build gluten with option " -Dvelox_home=$VELOX_HOME  "
The full compiling command is 
`mvn clean package -Pbackends-velox -Pfull-scala-compiler -DskipTests -Dcheckstyle.skip -Dbuild_cpp=ON -Dbuild_velox=ON -Dvelox_home=$VELOX_HOME   -Dbuild_arrow=OFF -Dbuild_protobuf=OFF  -Dcompile_velox=OFF/ON`

### CODE REVIEW

**Comment by zhouyuan** [comment]
@zhejiangxiaomai can you do a rebase?

**Comment by FelixYBW** [comment]
If we use "-Dbuild_velox_from_source=ON ", Velox is cloned to tools/build/velox_ep and installed to tools/build/velox_install.

**Comment by FelixYBW** [comment]
@zhejiangxiaomai  can you update readme of Velox? [Velox.md](https://github.com/oap-project/gluten/tree/main/docs/velox.md). 

Let's add two ways to build. If customer use -Dvelox_home=$VELOX_HOME, how they can apply our changes to Velox script and how they can build it firstly.

**Comment by zhejiangxiaomai** [comment]
> @zhejiangxiaomai can you do a rebase?

rebase done

**Pull request merged**
