### PR TITLE
[CH] Fix expand transformer can't collect metrics

### PR DESCRIPTION
**Pull request by exmy**
## How was this patch tested?

 manual tests

image

### CODE REVIEW

**Comment by exmy** [comment]
cc @lgbo-ustc @zzcclp

**Comment by lgbo-ustc** [comment]
There is a parameter `collect_processors` in  base class `ITransformingStep`, should set this to be true instead.

**Comment by lgbo-ustc** [comment]
LGTM

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
