### PR TITLE
[GLUTEN-1658] [CORE] feat: Support SparkResourcesUtil.scala in k8s

### PR DESCRIPTION
**Pull request by zbbkeepgoing**
## What changes were proposed in this pull request?

Support get the total cores of the Spark application in kubernetes.

### CODE REVIEW

**Review by FelixYBW — APPROVED** [review]

**Comment by zbbkeepgoing** [comment]
retest this please

**Comment by zbbkeepgoing** [comment]
Run Gluten Clickhouse CI

**Comment by zhouyuan** [comment]
Run Gluten Clickhouse CI

**Comment by zhouyuan** [comment]
@zbbkeepgoing thanks for this fix!
The command to re-trigger clickhouse tests is to comment: "Run Gluten Clickhouse CI"

-yuan

**Pull request merged**
