### PR TITLE
[VL] Improving performance by using xsimd::memcpy

### PR DESCRIPTION
**Pull request by zuochunwei**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by marin-ma** [comment]
Is this PR ready to merge?

**Comment by zuochunwei** [comment]
> Is this PR ready to merge?

Yes, I removed the `WIP` tag from this PR's title/

**Comment by marin-ma** [comment]
Looks like the TPCH workload doesn't have much performance improvement. Is this because memcpy is not hotspot in this kind of workload?

**Comment by zuochunwei** [comment]
> Looks like the TPCH workload doesn't have much performance improvement. Is this because memcpy is not hotspot in this kind of workload?

it seems to be right.
the TPCH workload test may be not enough precise.

**Review by marin-ma — APPROVED** [review]

**Pull request merged**
