### PR TITLE
[WIP][document] Update logo and trademark info

### PR DESCRIPTION
**Pull request by weiting-chen**
## What changes were proposed in this pull request?

Add Intel and Kyligence logo and trademark information.

## How was this patch tested?

N/A, README Change Only

### CODE REVIEW

**Review by FelixYBW — APPROVED** [review]

**Comment by FelixYBW** [comment]
@weiting-chen  can you check with other contributor if they would like to put their icon there?

**Comment by weiting-chen** [comment]
> 

Ok, will check with them and update later.

**Comment by weiting-chen** [comment]
@FelixYBW Add meituan and bigo logo. Need to get the approval again.

**Review by FelixYBW — DISMISSED** [review]

**Review by FelixYBW — APPROVED** [review]

**Comment by FelixYBW** [comment]
@zzcclp Can you check?

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
