### PR TITLE
[GLUTEN-1218]add c2r and r2c as parent of file scan exec for some case

### PR DESCRIPTION
**Pull request by lhuang09287750**
## What changes were proposed in this pull request?

add c2r and r2c as parent of file scan exec of which the out put format is spark columnar during TransformPostOverrides

## How was this patch tested?
add a test in GlutenClickHouseTPCHParquetSuite

    test("demo5") {
       withSQLConf(("spark.gluten.sql.columnar.filescan", "false")) {
        val sql =
          """
            |select a.s_suppkey, sum(a.s_acctbal) from supplier a left join supplier b on a.s_suppkey=b.s_suppkey
            |group by a.s_suppkey
            |order by a.s_suppkey
            |""".stripMargin
        compareResultsAgainstVanillaSpark(sql, true, { _ => })
      }

      Thread.sleep(6000000)
     }

### CODE REVIEW

**Comment by zzcclp** [comment]
please create a issue for this, and add the test case.

**Comment by lhuang09287750** [comment]
> please create a issue for this, and add the test case.
both done,  https://github.com/oap-project/gluten/issues/1218

**Comment by lhuang09287750** [comment]
@rui-mo ，maybe something wrong with velox ci

**Comment by PHILO-HE** [comment]
@lhuang09287750, thanks for your PR!
Did you explicitly enable spark's vectorized reader in your test? We have disabled it in gluten code, but if user explicitly enables it, it may still work. For perf. considerations, we didn't do the C2R then R2C transition for supporting spark's vectorized reader in a workaround approach. Is it strongly needed for you to use spark's vectorized reader for gluten scan fallback case?

**Comment by lhuang09287750** [comment]
@PHILO-HE yes, in our product KE, we use customized spark's vectorized reader which is derived from DataSourceScanExec.

**Comment by zzcclp** [comment]
IMO, it's better to support extending customized rules to transform customized spark plan, for example, XXXDataSourceScanExec. The way in this pr will add a vanilla C2R and a native R2C for file source scan, which is costly.

**Comment by lhuang09287750** [comment]
@rui-mo not much help because we want to use customized Spark's vectorized reader which is optimized for our product for fallback case

**Comment by PHILO-HE** [comment]
> @PHILO-HE yes, in our product KE, we want to use customized spark's vectorized reader which is derived from DataSourceScanExec for fallback case.

Considering the overhead brought by the transitions, is it still beneficial to you with your customized spark's vectorized reader used? It may need some perf. tests.

**Comment by lhuang09287750** [comment]
We consider to find a more efficient way ,so close this pr now
Thank you all!

**Pull request closed without merging**
