### PR TITLE
[CORE] Do not catch errors during plan validation

### PR DESCRIPTION
**Pull request by zhztheplayer**
We shouldn't catch Java/Scala errors during validation since:

1. Errors can lead to invalid state (e.g. load shared library failed, load class failed)
2. All errors should be addressed in development phase, catching them hides potential code bugs

Instead, we should only catch exceptions (although Exception is still too general for indicating a validation failure) at the moment.

### CODE REVIEW

**Comment by zhztheplayer** [comment]
@ulysses-you

**Review by ulysses-you — DISMISSED** [review]

**Comment by zhztheplayer** [comment]
An error blocks tests from passing

```
2023-08-14T05:52:47.1239016Z [31m- approx_count_distinct *** FAILED ***[0m
2023-08-14T05:52:47.1239736Z [31m  java.lang.AssertionError: assertion failed: Only one input attribute is expected.[0m
2023-08-14T05:52:47.1240527Z [31m  at scala.Predef$.assert(Predef.scala:223)[0m
2023-08-14T05:52:47.1243467Z [31m  at io.glutenproject.execution.HashAggregateExecTransformer.$anonfun$getAggRelWithRowConstruct$2(HashAggregateExecTransformer.scala:696)[0m
2023-08-14T05:52:47.1247190Z [31m  at io.glutenproject.execution.HashAggregateExecTransformer.$anonfun$getAggRelWithRowConstruct$2$adapted(HashAggregateExecTransformer.scala:495)[0m
2023-08-14T05:52:47.1248168Z [31m  at scala.collection.immutable.List.foreach(List.scala:431)[0m
2023-08-14T05:52:47.1249245Z [31m  at io.glutenproject.execution.HashAggregateExecTransformer.getAggRelWithRowConstruct(HashAggregateExecTransformer.scala:495)[0m
2023-08-14T05:52:47.1250489Z [31m  at io.glutenproject.execution.HashAggregateExecTransformer.getAggRel(HashAggregateExecTransformer.scala:841)[0m
2023-08-14T05:52:47.1251725Z [31m  at io.glutenproject.execution.HashAggregateExecBaseTransformer.doValidateInternal(HashAggregateExecBaseTransformer.scala:144)[0m
2023-08-14T05:52:47.1253274Z [31m  at io.glutenproject.extension.GlutenPlan.doValidate(GlutenPlan.scala:66)[0m
2023-08-14T05:52:47.1254152Z [31m  at io.glutenproject.extension.GlutenPlan.doValidate$(GlutenPlan.scala:63)[0m
2023-08-14T05:52:47.1255236Z [31m  at io.glutenproject.execution.HashAggregateExecBaseTransformer.doValidate(HashAggregateExecBaseTransformer.scala:48)[0m
```

**Comment by rui-mo** [comment]
@zhztheplayer This part trys to insert a projection node before aggregation for row_constructor. Looks it is not supported for approx_count_distinct yet.

**Comment by zhztheplayer** [comment]
> @zhztheplayer This part trys to insert a projection node before aggregation for row_constructor. Looks it is not supported for approx_count_distinct yet. Can we change to throw exception instead of assert?
> 
> > assert(functionInputAttributes.size == 1, "Only one input attribute is expected.")

OK so sounds to me like it can be considered as a normal validation statement? I'll make the change. Thanks.

**Comment by rui-mo** [comment]
> OK so sounds to me like it can be considered as a normal validation statement? Then I'll make the change to make it throw exception. Thanks.

@zhztheplayer Yes, that makes sense to me.

**Review by rui-mo — APPROVED** [review]

**Pull request merged**
