### PR TITLE
[VL] Update gluten-it: Remove a workaround against TPC-DS Q8

### PR DESCRIPTION
**Pull request by zhztheplayer**
related to bloom filter patch https://github.com/oap-project/gluten/commit/7384682b856b7d3e6598c38b363bb20ac882d959#diff-2b8d009043c16aacc3175020f2529ccef696f8f7e726b9091618a05e70b530bf

### CODE REVIEW

**Review by FelixYBW — APPROVED** [review]

**Comment by zhztheplayer** [comment]
@jinchengchenghh Just want to see if you have some inputs to get a fix work. It looks like sub-optimal if we pass a customized config option for a specific query.

**Comment by FelixYBW** [comment]
> @jinchengchenghh Just want to see if you have some inputs to get a fix work. It looks like sub-optimal if we pass a customized config option for a specific query.

what happen if we enable bf here?

**Comment by jinchengchenghh** [comment]
Because this unsupport case https://github.com/oap-project/gluten/blob/main/docs/VeloxNotSupport.md#runtime-bloomfilter

**Comment by zhztheplayer** [comment]
> Because this unsupport case https://github.com/oap-project/gluten/blob/main/docs/VeloxNotSupport.md#runtime-bloomfilter

It looks like a fall-back option that requires user to pass a specific config option. Would you think the exception can be somehow predictable during plan validation?

**Comment by jinchengchenghh** [comment]
No, this validation involves 2 nodes, aggregate function bloom_filter_agg and might_contain should both be offloaded or fallback

**Comment by jinchengchenghh** [comment]
We have discussed that in meeting, now we use velox BloomFilter whose implementation is different with spark BloomFilter, so the serialized binary is different, only if we implement native spark BloomFilter, we can avoid this error

**Comment by jinchengchenghh** [comment]
For q8, if we fix the fallback might_contain, we can fix this error

**Comment by zhztheplayer** [comment]
> if the query fallbacks might_contain to velox but offload bloom_filter_agg to velox

If we know the filter needs to be fall-backed, then during planning phase we should know the agg has to be fall-backed therefore.

I noticed in Spark (correct me if wrong) bloom-filter's planning part is in rule [InjectRuntimeFilter](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/InjectRuntimeFilter.scala) which should be in so-called **logical planning phase**, since a logical rule like this is hard to extend by Spark's design, so probably this is also the root-cause why we can't easily inject our own validation codes.

But still we may have chance to do some tricks like workarounds in our own columnar rule to avoid such "mandatory manual fall-back", just like [what we have done against broadcast join](https://github.com/oap-project/gluten/blob/main/gluten-core/src/main/scala/io/glutenproject/extension/ColumnarQueryStagePrepOverrides.scala) (join and exchange should be both fall-backed or off-loaded).

**Comment by jinchengchenghh** [comment]
The hashjoin Exec falback child plan is relevant to Exchange, but `bloom_filter_agg` exists in HashAggregateExec while `migh_contain` exists in `ExpressionConverter` which nearly exists in all the nodes, for TPC-DS Q8, might_contain exists in `FilterExec`

**Comment by zhztheplayer** [comment]
Closed by https://github.com/oap-project/gluten/pull/1048

**Pull request closed without merging**
