### PR TITLE
[GLUTEN-4713][CORE] Not trim the Alias from resultExpressions when determining whether a post-project is needed

### LINKED ISSUE #4713: [VL] TPCDS-Q23b failed on large scale
### Backend

VL (Velox)

### Bug description

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007feb2f043bcb, pid=1573553, tid=0x00007feb1e9ff700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_161-b12) (build 1.8.0_161-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.161-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libvelox.so+0x4b84bcb]  facebook::velox::exec::GroupingSet::extractGroups(folly::Range<char**>, std::shared_ptr<facebook::velox::RowVector> const&)+0xdb
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /mnt/DP_disk5/tpcds/yarn/usercache/sparkuser/appcache/application_1702277591581_0578/container_1702277591581_0578_01_000016/hs_err_pid1573553.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

### Spark version

None

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by liujiayi771**
## What changes were proposed in this pull request?

Fix #4713.

## How was this patch tested?

Exists CI. Test 1T TPCDS q23b.

### CODE REVIEW

**Comment by liujiayi771** [comment]
A final agg stage will core after #4628, the difference is that it lacks a post-project.
Before:
```
-- Project[expressions: (n3_3:VARCHAR, "n1_4"), (n3_4:VARCHAR, "n1_5"), (n3_5:DECIMAL(28, 2), "n2_2")] -> n3_3:VARCHAR, n3_4:VARCHAR, n3_5:DECIMAL(28, 2)
   Output: 4251 rows (578.06KB, 2 batches), Cpu time: 10.76us, Blocked wall time: 0ns, Peak memory: 0B, Memory allocations: 0, Threads: 1
      queuedWallNanos              sum: 0ns, count: 1, min: 0ns, max: 0ns
      runningAddInputWallNanos     sum: 769ns, count: 1, min: 769ns, max: 769ns
      runningFinishWallNanos       sum: 0ns, count: 1, min: 0ns, max: 0ns
      runningGetOutputWallNanos    sum: 7.79us, count: 1, min: 7.79us, max: 7.79us
  -- Aggregation[SINGLE [n1_4, n1_5] n2_2 := sum_merge_extract("n1_6")] -> n1_4:VARCHAR, n1_5:VARCHAR, n2_2:DECIMAL(28, 2)
     Output: 4251 rows (578.06KB, 2 batches), Cpu time: 16.47ms, Blocked wall time: 0ns, Peak memory: 14.97MB, Memory allocations: 24, Threads: 1
        distinctKey0                 sum: 1886, count: 1, min: 1886, max: 1886
        distinctKey1                 sum: 1172, count: 1, min: 1172, max: 1172
        hashtable.capacity           sum: 8192, count: 1, min: 8192, max: 8192
        hashtable.numDistinct        sum: 4251, count: 1, min: 4251, max: 4251
        hashtable.numRehashes        sum: 14, count: 1, min: 14, max: 14
        hashtable.numTombstones      sum: 0, count: 1, min: 0, max: 0
        runningAddInputWallNanos     sum: 15.43ms, count: 1, min: 15.43ms, max: 15.43ms
        runningFinishWallNanos       sum: 484ns, count: 1, min: 484ns, max: 484ns
        runningGetOutputWallNanos    sum: 749.48us, count: 1, min: 749.48us, max: 749.48us
    -- Project[expressions: (n1_4:VARCHAR, "n0_0"), (n1_5:VARCHAR, "n0_1"), (n1_6:ROW<col_0:DECIMAL(28, 2),col_1:BOOLEAN>, row_constructor("n0_2","n0_3"))] -> n1_4:VARCHAR, n1_5:VARCHAR, n1_6:ROW<col_0:DECIMAL(28, 2),col_1:BOOLEAN>
       Output: 4387 rows (303.35KB, 984 batches), Cpu time: 4.70ms, Blocked wall time: 0ns, Peak memory: 0B, Memory allocations: 0, Threads: 1
          runningAddInputWallNanos     sum: 232.21us, count: 1, min: 232.21us, max: 232.21us
          runningFinishWallNanos       sum: 1.44us, count: 1, min: 1.44us, max: 1.44us
          runningGetOutputWallNanos    sum: 3.93ms, count: 1, min: 3.93ms, max: 3.93ms
      -- ValueStream[] -> n0_0:VARCHAR, n0_1:VARCHAR, n0_2:DECIMAL(28, 2), n0_3:BOOLEAN
         Input: 0 rows (0B, 0 batches), Output: 4387 rows (303.35KB, 984 batches), Cpu time: 83.66ms, Blocked wall time: 0ns, Peak memory: 0B, Memory allocations: 0, Threads: 1
            runningAddInputWallNanos     sum: 0ns, count: 1, min: 0ns, max: 0ns
            runningFinishWallNanos       sum: 380ns, count: 1, min: 380ns, max: 380ns
            runningGetOutputWallNanos    sum: 84.58ms, count: 1, min: 84.58ms, max: 84.58ms
```
After:
```
-- Aggregation[SINGLE [n1_4, n1_5] n2_2 := sum_merge_extract("n1_6")] -> n1_4:VARCHAR, n1_5:VARCHAR, n2_2:DECIMAL(28, 2)
   Output: 1678 rows (288.28KB, 1 batches), Cpu time: 10.18ms, Blocked wall time: 0ns, Peak memory: 8.69MB, Memory allocations: 22, Threads: 1
      distinctKey0                 sum: 1013, count: 1, min: 1013, max: 1013
      distinctKey1                 sum: 706, count: 1, min: 706, max: 706
      hashtable.capacity           sum: 1076768, count: 1, min: 1076768, max: 1076768
      hashtable.numDistinct        sum: 1678, count: 1, min: 1678, max: 1678
      hashtable.numRehashes        sum: 14, count: 1, min: 14, max: 14
      hashtable.numTombstones      sum: 0, count: 1, min: 0, max: 0
      queuedWallNanos              sum: 1.00us, count: 1, min: 1.00us, max: 1.00us
      rangeKey0                    sum: 4380950328322, count: 1, min: 4380950328322, max: 4380950328322
      runningAddInputWallNanos     sum: 8.96ms, count: 1, min: 8.96ms, max: 8.96ms
      runningFinishWallNanos       sum: 0ns, count: 1, min: 0ns, max: 0ns
      runningGetOutputWallNanos    sum: 941.15us, count: 1, min: 941.15us, max: 941.15us
  -- Project[expressions: (n1_4:VARCHAR, "n0_0"), (n1_5:VARCHAR, "n0_1"), (n1_6:ROW<col_0:DECIMAL(28, 2),col_1:BOOLEAN>, row_constructor("n0_2","n0_3"))] -> n1_4:VARCHAR, n1_5:VARCHAR, n1_6:ROW<col_0:DECIMAL(28, 2),col_1:BOOLEAN>
     Output: 1721 rows (128.53KB, 810 batches), Cpu time: 3.44ms, Blocked wall time: 0ns, Peak memory: 0B, Memory allocations: 0, Threads: 1
        runningAddInputWallNanos     sum: 168.30us, count: 1, min: 168.30us, max: 168.30us
        runningFinishWallNanos       sum: 2.39us, count: 1, min: 2.39us, max: 2.39us
        runningGetOutputWallNanos    sum: 2.83ms, count: 1, min: 2.83ms, max: 2.83ms
    -- ValueStream[] -> n0_0:VARCHAR, n0_1:VARCHAR, n0_2:DECIMAL(28, 2), n0_3:BOOLEAN
       Input: 0 rows (0B, 0 batches), Output: 1721 rows (128.53KB, 810 batches), Cpu time: 41.32ms, Blocked wall time: 0ns, Peak memory: 0B, Memory allocations: 0, Threads: 1
          runningAddInputWallNanos     sum: 0ns, count: 1, min: 0ns, max: 0ns
          runningFinishWallNanos       sum: 445ns, count: 1, min: 445ns, max: 445ns
          runningGetOutputWallNanos    sum: 41.35ms, count: 1, min: 41.35ms, max: 41.35ms
```

While refactoring the pull-out project, I found that a final agg would add a post-project when `resultExpressions` contained `Alias(Attribute)`. However, when the `Attribute` in the `Alias` matches the native output, the native plan, being unaware of the Spark `Alias`'s name, would consider this `Alias(Attribute)` unnecessary for introducing an additional post-project. Therefore, I performed a `trimAlias` before making the comparison.
For example,
```
resultExpressions = attr(a), attr(b), alias(attr(c))
allAggregateResultAttributes = attr(a), attr(b), attr(c)
```

However, it seems that without this post-project step, a core dump occurs with large datasets, while there are no problems with small datasets.

cc @zhouyuan @rui-mo @ulysses-you

**Comment by ulysses-you** [comment]
it's interesting, please fix ch backend test

**Comment by liujiayi771** [comment]
@zzcclp Could you help to review?

**Review by zhouyuan — APPROVED** [review]
👍 
thanks a lot for this quick fix, works on my test.

**Comment by zzcclp** [comment]
LGTM if test passed.

**Review by ulysses-you — APPROVED** [review]

**Pull request merged**
