### PR TITLE
[Gluten-core] add SqlLogicTest cases for test coverage.

### PR DESCRIPTION
**Pull request by jikunshang**
## What changes were proposed in this pull request?

add SqlLogicTest cases for test coverage.
SqlLogicTest is a test tool from SqlLite, it can provide millions queries. I reference `SQLQueryTestSuite` from spark, which is an E2E test cases for SQL queries. I add a test suite which could run queries from Sql logic test.
refer link: 
[doc](https://www.sqlite.org/sqllogictest/doc/trunk/about.wiki)
[repo mirror](https://github.com/gregrahn/sqllogictest)

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by FelixYBW** [comment]
Thank you, does it cover some of the corner case? Can velox and CK backend pass the test?

@zhouyuan do we need to add to our CI tests?

**Comment by jikunshang** [comment]
> Thank you, does it cover some of the corner case? Can velox and CK backend pass the test?
> 
> @zhouyuan do we need to add to our CI tests?

I think it will cover some corner cases. I just verified vanilla spark path, this is a quick result for spark coverage:
(note: total query include create and insert query)

File | Total query | Spark exception | Gluten
-- | -- | -- | --
Select1.sql | 1008 | 340 |  
Select2.sql | 1036 | 345 |  
Select3.sql | 3356 | 1194 |  
Select4.sql | 3878 | 25 |  
Select5.sql | 1508 | 0 |  

This suite will run about 1 hour in vanilla spark. seems it's not enabled in CI. Maybe we should add it to nightly test.

**Comment by PHILO-HE** [comment]
Is it possible to just download the query resources from somewhere for test use? It looks heavy to maintain them in the repo. cc @zhouyuan

**Comment by zhouyuan** [comment]
hi @jikunshang,

Thanks a lot for improving the tests - Spark UT coverage is not good enough indeed. I can see this is a good compilement for Gluten. The current GHA is a little long(~1.8H) already and I'm afraid including this test will overload the servers. I aggree on enable this in the nighly tests. Also we do have some fuzz tests running inside intel lab, and running with many hours:
- Fuzz tests for Gluten(utilizing Spark catalyst API to generate the valid SQL, and running with Spark SQL) 
- Fuzz tests for Velox(using the Velox fuzz testing)

We may need to put these tests into a separate repo(or folder) so developers can help to run those tests on their own servers.
@zzcclp how do you think about this? 


Thanks, -yuan


> > Thank you, does it cover some of the corner case? Can velox and CK backend pass the test?
> > @zhouyuan do we need to add to our CI tests?
> 
> I think it will cover some corner cases. I just verified vanilla spark path, this is a quick result for spark coverage: (note: total query include create and insert query)
> 
> File	Total query	Spark exception	Gluten
> Select1.sql	1008	340	 
> Select2.sql	1036	345	 
> Select3.sql	3356	1194	 
> Select4.sql	3878	25	 
> Select5.sql	1508	0	 
> This suite will run about 1 hour in vanilla spark. seems it's not enabled in CI. Maybe we should add it to nightly test.

**Comment by FelixYBW** [comment]
Oh, I s

> hi @jikunshang,
> 
> Thanks a lot for improving the tests - Spark UT coverage is not good enough indeed. I can see this is a good compilement for Gluten. The current GHA is a little long(~1.8H) already and I'm afraid including this test will overload the servers. I aggree on enable this in the nighly tests. Also we do have some fuzz tests running inside intel lab, and running with many hours:
> 
> * Fuzz tests for Gluten(utilizing Spark catalyst API to generate the valid SQL, and running with Spark SQL)
> * Fuzz tests for Velox(using the Velox fuzz testing)
> 
> We may need to put these tests into a separate repo(or folder) so developers can help to run those tests on their own servers. @zzcclp how do you think about this?
> 
> Thanks, -yuan

Oh, I see. Let's use it as other Fuzz tests. Since we are not going to put it in CI, Let's not include it in Gluten repo. Just do the similar way as Fuzz.  Thank you @jikunshang to propose this!

**Comment by FelixYBW** [comment]
Let's close it and put it in our nightly test.

**Pull request closed without merging**
