### PR TITLE
[GLUTEN-3670][CH] Support escape with excel format

### PR DESCRIPTION
**Pull request by loneylee**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#3670-ID)

## How was this patch tested?

Test by ut

### CODE REVIEW

**Comment by loneylee** [comment]
Run Gluten Clickhouse CI

**Comment by loneylee** [comment]
Run Gluten Clickhouse CI

**Comment by taiyang-li** [comment]
LGTM

**Review by taiyang-li — APPROVED** [review]

**Review by baibaichen — APPROVED** [review]
LGTM

**Pull request merged**
