### PR TITLE
[GLUTEN-1864][CORE] feat: Support bucketed read

### PR DESCRIPTION
**Pull request by WangGuangxin**
## What changes were proposed in this pull request?

Support bucketed read

(Fixes: \#1864)

## How was this patch tested?
existing unit tests on bucket read

### CODE REVIEW

**Comment by WangGuangxin** [comment]
@PHILO-HE @rui-mo Can you please help review this?  BTW, not sure why the CI fails

**Comment by PHILO-HE** [comment]
Hi @WangGuangxin, there is a compilation error reported from ClickHouse CI:
```
clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHTransformerApi.scala:38: error:
class CHTransformerApi needs to be abstract, since method genInputPartitionSeq in trait TransformerApi of type 
```

**Comment by zhouyuan** [comment]
@WangGuangxin can you please do a rebase? There's a minor conflict in `FileScanExec`

-yuan

**Comment by WangGuangxin** [comment]
> @WangGuangxin can you please do a rebase? There's a minor conflict in `FileScanExec`
> 
> -yuan

rebased

**Review by zzcclp — APPROVED** [review]
LGTM

**Comment by zzcclp** [comment]
please rebase

**Review by zhouyuan — APPROVED** [review]
👍

**Pull request merged**
