### PR TITLE
[GLUTEN-4789] [VL] Wrong preceding/following convert in window function node

### PR DESCRIPTION
**Pull request by WangGuangxin**
## What changes were proposed in this pull request?

The convert logic in `WindowFuncitonNode.java`  make the assumption that the lower bound of a row/range frame are always `preceding offset`, and the upper bound are always `following offset`,  which is not the case.

https://github.com/oap-project/gluten/blob/6acd1b367a669bcca8af3708c00328cc3e707d2a/gluten-core/src/main/java/io/glutenproject/substrait/expression/WindowFunctionNode.java#L80

For example, following case is also a valid row frame.
```
select max(l_suppkey) over  (partition by l_suppkey order by l_orderkey rows between 2 preceding and 1 preceding) from lineitem
```

In fact, the spark row frame will convert preceding offset A to -A, so that the lower and upper bound params in `SpecifiedWindowFrame` are always **following offset**. 

Since Velox requires the input offset must be positive, so we just need to convert negative following offset to preceding offset, and vice versa.

## How was this patch tested?
UT

### CODE REVIEW

**Comment by WangGuangxin** [comment]
cc @lgbo-ustc @PHILO-HE @rui-mo @ulysses-you

**Comment by ulysses-you** [comment]
Run Gluten Clickhouse CI

**Comment by ulysses-you** [comment]
lgtm if ch backend tests pass

**Review by ulysses-you — APPROVED** [review]

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Pull request merged**
