### PR TITLE
[Gluten-2199][CH] Fix lock issue2

### PR DESCRIPTION
**Pull request by binmahone**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#2199)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by binmahone** [comment]
Run Gluten Clickhouse CI

**Comment by binmahone** [comment]
Run Gluten Clickhouse CI

**Review by baibaichen — APPROVED** [review]
LGTM

**Comment by baibaichen** [comment]
image
performace looks good

**Pull request merged**
