### PR TITLE
[GLUTEN-2343] [VL] Copy buffers to a big buffer and then compress

### PR DESCRIPTION
**Pull request by jinchengchenghh**
Try to compress all the buffer to one buffer, and then compress the big buffer.
If this can gain performance improvement, will move to folly stream compression. It can accept several buffers to compress.

### CODE REVIEW

**Comment by FelixYBW** [comment]
duplicated?

**Comment by zhouyuan** [comment]
@Guhaiyan

**Comment by jinchengchenghh** [comment]
Regretly, it has no performance improvement for both lz4 and zstd compression.
I will switch to zstd stream codec to find if there is potential improvement.

**Comment by jinchengchenghh** [comment]
@Guhaiyan Do you test this PR in your environment? What's the performance compared to before?

**Comment by jinchengchenghh** [comment]
stream codec performance is not good, so close this PR.

**Pull request closed without merging**
