### PR TITLE
[VL] Enable tests for string for ascii, replace

### PR DESCRIPTION
**Pull request by izchen**
https://github.com/oap-project/gluten/issues/1478

### CODE REVIEW

**Comment by izchen** [comment]
Depend on Velox function support:
https://github.com/facebookincubator/velox/pull/4631
https://github.com/facebookincubator/velox/pull/4909
https://github.com/facebookincubator/velox/pull/4922

**Comment by PHILO-HE** [comment]
@izchen, I note your PR for fixing chr function is still pending in velox upstream. Can you just file your drafted velox PRs to oap/velox? We can get them firstly merged in oap/velox. Thus, this gluten PR will not be blocked. Thanks!

**Comment by izchen** [comment]
> @izchen, I note your PR for fixing chr function is still pending in velox upstream. Can you just file your drafted velox PRs to oap/velox? We can get them firstly merged in oap/velox. Thus, this gluten PR will not be blocked. Thanks!

@PHILO-HE I just created two oap/velox pr，would you mind take a look?

https://github.com/oap-project/velox/pull/277
https://github.com/oap-project/velox/pull/278

**Comment by PHILO-HE** [comment]
Will merge the patch soon. @izchen, thank you so much!

**Review by PHILO-HE — APPROVED** [review]

**Comment by zhouyuan** [comment]
@izchen thank you for the quick turnaround!

-yuan

**Comment by izchen** [comment]
@PHILO-HE @zhouyuan , Thanks!

**Pull request merged**
