### PR TITLE
[GLUTEN-2501][CI] Fix license header and include CH modules in CI check

### PR DESCRIPTION
**Pull request by xieqi**
## What changes were proposed in this pull request?

Add license check for CK

## How was this patch tested?

No need test, just add license

### CODE REVIEW

**Comment by PHILO-HE** [comment]
@zzcclp, @baibaichen, please take a review.

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by PHILO-HE** [comment]
Will merge the patch soon if no review comment. @baibaichen @zzcclp

**Review by PHILO-HE — APPROVED** [review]
Looks great!

**Pull request merged**
