### PR TITLE
[VL] fix: Update Velox setup scripts for centos 7

### PR DESCRIPTION
**Pull request by ccat3z**
## What changes were proposed in this pull request?

Update setup scripts for centos 7

## How was this patch tested?

Build on clear centos 7

### CODE REVIEW

**Comment by zhouyuan** [comment]
@zhejiangxiaomai @weiting-chen  This patch adds Cent7 tests in GA, please take a look.

**Comment by zhejiangxiaomai** [comment]
Please add a new empty line at the end of file. 
image

**Comment by ccat3z** [comment]
vault.centos.org seems unstable. I switched the centos 8 repo to aliyun mirror.

**Review by zhejiangxiaomai — COMMENTED** [review]
pelease remeber change to 
```
VELOX_REPO=https://github.com/oap-project/velox.git
VELOX_BRANCH=main
```

**Comment by weiting-chen** [comment]
> pelease remeber change to
> 
> ```
> VELOX_REPO=https://github.com/oap-project/velox.git
> VELOX_BRANCH=main
> ```

I have trigger CI testing and lets check the result first.

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Review by zhouyuan — DISMISSED** [review]
👍

**Review by zhejiangxiaomai — APPROVED** [review]

**Review by zhejiangxiaomai — APPROVED** [review]

**Review by zhouyuan — APPROVED** [review]
+1 if CI is green

**Review by zhejiangxiaomai — APPROVED** [review]

**Comment by zhouyuan** [comment]
@ccat3z Thanks for improving CentOS related scripts!

**Pull request merged**
