### PR TITLE
[Core] Add Alibaba name in README

### PR DESCRIPTION
**Pull request by weiting-chen**
## What changes were proposed in this pull request?

Add Alibaba name in README.

## How was this patch tested?

N/A, only README update

### CODE REVIEW

**Comment by zhouyuan** [comment]
@Yohahaha

**Comment by Yohahaha** [comment]
Thanks! but the "Alibaba Cloud" would make more sense as we talked in DingDing.
cc @waitinfuture

**Comment by zhouyuan** [comment]
> Thanks! but the "Alibaba Cloud" would make more sense as we talked in DingDing. cc @waitinfuture

Sorry for this, can you please make a change to correct the name? 

-yuan

**Comment by Yohahaha** [comment]
> > Thanks! but the "Alibaba Cloud" would make more sense as we talked in DingDing. cc @waitinfuture
> 
> Sorry for this, can you please make a change to correct the name? 
> 
> -yuan

Ok, I will verify and correct it after internal discussion.

**Comment by FelixYBW** [comment]
Do you want to add logo?

**Pull request merged**
