### PR TITLE
[OPPRO-189] Rebase Arrow to upstream Arrow - Remove unused fastpfor and memory listener

### PR DESCRIPTION
**Pull request by jinchengchenghh**
remove unused fastpfor and memory listener

### CODE REVIEW

**Comment by jinchengchenghh** [comment]
with this change https://github.com/oap-project/arrow/pull/132

**Comment by jinchengchenghh** [comment]
Arrow 9 still has some problem, so I split the big PR to several PRs, this is the first ready PR, After review, I will merge Arrow PR https://github.com/oap-project/arrow/pull/132 and change this PR arrow branch to oap-project branch

**Comment by jinchengchenghh** [comment]
Can you take a look? Thanks! @zhztheplayer

**Review by zhztheplayer — APPROVED** [review]
lgtm

**Pull request merged**
