### PR TITLE
[GLUTEN-3559][VL] Fix unit tests in GlutenSQLQueryTestSuite suite - Part 3

### PR DESCRIPTION
**Pull request by vibhaska**
## What changes were proposed in this pull request?

This PR enables following tests in the suite GlutenSQLQueryTestSuite:
group-by.sql
group-by-ordinal.sql

Now only following tests are left in GlutenSQLQueryTestSuite:
 - typeCoercion/native/mapconcat.sql *** FAILED ***					
	-- mapconcat.sql is disabled for 3.4
 - udaf.sql *** FAILED *** 								
	-- but udaf/udaf.sql passed so just need to verify if same test
 - udf/postgreSQL/udf-select_having.sql - Scala UDF *** FAILED ***			
	-- select_having.sql is disabled for 3.4
 - describe-table-column.sql *** FAILED ***						
	-- missing test file?
 - postgreSQL/select_having.sql *** FAILED ***						
	-- select_having.sql is disabled for 3.4
 - subquery/scalar-subquery/scalar-subquery-select.sql *** FAILED *** (Gluten throws exception: more than one row returned by a subquery used as an expression)
	-- disabled for 3.4

(Fixes: \#3559)

## How was this patch tested?

Ran this UT to confirm the fix

### CODE REVIEW

**Comment by vibhaska** [comment]
> thank you @vibhaska , can you point out which and why query failed in `group-by.sql` and `group-by-ordinal.sql` before ?

group-by-ordinal.sql is passing without any change. Since tests are identified based on regex some additional tests in udaf was also getting enabled and failing. I dont see those udaf tests mentioned anywhere so keeping disabled.

group-by.sql needs to be overridden in Gluten, as we did in earlier versions.

**Review by JkSelf — COMMENTED** [review]
LGTM. Thanks.

**Review by JkSelf — APPROVED** [review]

**Comment by vibhaska** [comment]
@ulysses-you How can we merge this? One check is failing but doesn't look like my changes related.

**Comment by vibhaska** [comment]
@JkSelf @zhli1142015 @ulysses-you can you pleas have a look on how to merge?

**Comment by ulysses-you** [comment]
@vibhaska sorry for the late reply, will merge this pr once CI pass

**Pull request merged**
