### PR TITLE
Make the needed change to upgrade Velox

### PR DESCRIPTION
**Pull request by rui-mo**
## What changes were proposed in this pull request?

Depends on: https://github.com/oap-project/velox/pull/26.

## How was this patch tested?

under test

### CODE REVIEW

**Comment by rui-mo** [comment]
@zhejiangxiaomai Raised PR for Velox and Gluten.

**Comment by rui-mo** [comment]
TPC-H is runnable on double dataset. Need to verify on dwrf dataset.

**Comment by zhejiangxiaomai** [comment]
> TPC-H is runnable on double dataset. Need to verify on dwrf dataset.

I will use jenkens to  test it on dwrf dataset.

**Comment by rui-mo** [comment]
Covered by https://github.com/oap-project/gluten/pull/224.

**Pull request closed without merging**
