### PR TITLE
[GLUTEN-913] Support deploying gluten for other spark patch versions (not well tested)

### LINKED ISSUE #913: No Spark Shim Provider found for 3.2.0
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We run Spark-3.2 in house, when trying gluten + velox, we see issue "No Spark Shim Provider found for 3.2.0".

**Describe the solution you'd like**

Support Spark 3.2.0 version.

**Describe alternatives you've considered**

No alternatives I can think of right now.

**Additional context**

Nan.

### PR DESCRIPTION
**Pull request by CodingCat**
## What changes were proposed in this pull request?

this PR proposes to check spark version only at major and minor version so that we can support build with more spark releases

in the discussion at #913, @FelixYBW suggested that we can support these patch versions but only run daily build on what we have in main branch, and document the policy well 

close #913 

## How was this patch tested?

tested with 3.2.0

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by FelixYBW** [comment]
Thank you, @CodingCat With this PR, will we support 3.2.0 only or support both 3.2.0 and 3.2.2?

**Comment by CodingCat** [comment]
> Thank you, @CodingCat With this PR, will we support 3.2.0 only or support both 3.2.0 and 3.2.2?

it should support both , but I am thinking that, for patch versions, if we should build but not running test to ensure that at least it compiles

**Comment by FelixYBW** [comment]
> 
> it should support both , but I am thinking that, for patch versions, if we should build but not running test to ensure that at least it compiles

Yes, Then let's add someth comments like "Gluten can be built with spark3.2.x and 3.3.x but our CI only track Spark3.2.2 and Spark3.3.1 now. The other minor version may have issues at runtime."

**Comment by CodingCat** [comment]
> > it should support both , but I am thinking that, for patch versions, if we should build but not running test to ensure that at least it compiles
> 
> Yes, Then let's add someth comments like "Gluten can be built with spark3.2.x and 3.3.x but our CI only track Spark3.2.2 and Spark3.3.1 now. The other minor version may have issues at runtime."

I will add docs/change CI script accordingly

**Comment by PHILO-HE** [comment]
Thanks for your PR! 
The purpose is to build gluten with more spark releases (as dependency)? Or just support other spark versions in user's deployment env.? For the first case, spark version should be determined by building profile. The proposed changes for shim layer just matters in matching more spark versions at runtime.
If we ignore patch version in shim layer matching, I am not sure whether there is any compatibility issue, e.g. for supporting newer 3.3.x version in the future.
cc @jinchengchenghh

**Comment by CodingCat** [comment]
> Thanks for your PR! The purpose is to build gluten with more spark releases (as dependency)? Or just support other spark versions in user's deployment env.? For the first case, spark version should be determined by building profile. The proposed changes for shim layer just matters in matching more spark versions at runtime. If we ignore patch version in shim layer matching, I am not sure whether there is any compatibility issue, e.g. for supporting newer 3.3.x version in the future. cc @jinchengchenghh

it's to match more versions in shims

the idea is that 

1. Gluten build with 3.2.x and 3.3.x
2. Gluten build and test with a particular version, e.g. 3.2.2 and 3.3.1 (we can upgrade based on upstream)
3. in docs, we tell users , 3.2.x and 3.3.x are supported in terms of compile time compatibility, but only 3.2.2/3.3.1 is tested against daily build

**Comment by FelixYBW** [comment]
> the idea is that
> 
> 1. Gluten build with 3.2.x and 3.3.x
> 2. Gluten build and test with a particular version, e.g. 3.2.2 and 3.3.1 (we can upgrade based on upstream)
> 3. in docs, we tell users , 3.2.x and 3.3.x are supported in terms of compile time compatibility, but only 3.2.2/3.3.1 is tested against daily build
> 
> @FelixYBW hopefully the above is consistent with what you thought

Yes, excatly. At least currently Gluten can be built with all spark3.2.x and 3.3.x. We just only test 3.2.2 and 3.3.1. Gluten user will take the risk if they are going to run on other minor version.

**Comment by PHILO-HE** [comment]
It would be better to add some warning log during loading shims if user's spark version is not our officially supported ones. Thanks!

**Comment by FelixYBW** [comment]
> It would be better to add some warning log during loading shims if user's spark version is not our officially supported ones. Thanks!

Print to driver log?

**Comment by PHILO-HE** [comment]
> > It would be better to add some warning log during loading shims if user's spark version is not our officially supported ones. Thanks!
> 
> Print to driver log?

If we do print log during loading shim layer, it will be done on both driver side & executor side.

**Review by FelixYBW — APPROVED** [review]

**Comment by CodingCat** [comment]
my PR failed in this spark UT?

```
test("SPARK-36093: RemoveRedundantAliases should not change expression's name") {
    withTable("t1", "t2") {
      withView("t1_v") {
        sql("CREATE TABLE t1(cal_dt DATE) USING PARQUET")
        sql(
          """
            |INSERT INTO t1 VALUES
            |(date'2021-06-27'),
            |(date'2021-06-28'),
            |(date'2021-06-29'),
            |(date'2021-06-30')""".stripMargin)
        sql("CREATE VIEW t1_v AS SELECT * FROM t1")
        sql(
          """
            |CREATE TABLE t2(FLAG INT, CAL_DT DATE)
            |USING PARQUET
            |PARTITIONED BY (CAL_DT)""".stripMargin)
        val insert = sql(
          """
            |INSERT INTO t2 SELECT 2 AS FLAG,CAL_DT FROM t1_v
            |WHERE CAL_DT BETWEEN '2021-06-29' AND '2021-06-30'""".stripMargin)
        insert.queryExecution.executedPlan.collectFirst {
          case CommandResultExec(_, DataWritingCommandExec(
            i: InsertIntoHadoopFsRelationCommand, _), _) => i
        }.get.partitionColumns.map(_.name).foreach(name => assert(name == "CAL_DT"))
        checkAnswer(sql("SELECT FLAG, CAST(CAL_DT as STRING) FROM t2 "),
            Row(2, "2021-06-29") :: Row(2, "2021-06-30") :: Nil)
        checkAnswer(sql("SHOW PARTITIONS t2"),
            Row("CAL_DT=2021-06-29") :: Row("CAL_DT=2021-06-30") :: Nil)
      }
    }
  }
```

it is related to my change?

**Comment by FelixYBW** [comment]
> 

@zhztheplayer @zzcclp

**Comment by CodingCat** [comment]
yeah.....cannot really reproduce in my local 
image

**Review by PHILO-HE — APPROVED** [review]

**Pull request merged**
