### PR TITLE
[OPPRO-195] Add pre projection in join operator

### PR DESCRIPTION
**Pull request by marin-ma**

### CODE REVIEW

**Comment by zzcclp** [comment]
Please rebase and re-run tests.

**Comment by zzcclp** [comment]
Hi, I modify TPCH Q12 and run with this pr, the shj will fallback:
```
SELECT /*+ SHUFFLE_HASH(ch_lineitem) */
    l_shipmode,
    sum(
        CASE WHEN o_orderpriority = '1-URGENT'
            OR o_orderpriority = '2-HIGH' THEN
            1
        ELSE
            0
        END) AS high_line_count,
    sum(
        CASE WHEN o_orderpriority <> '1-URGENT'
            AND o_orderpriority <> '2-HIGH' THEN
            1
        ELSE
            0
        END) AS low_line_count
FROM
    ch_orders,
    ch_lineitem
WHERE
    **o_orderkey = l_orderkey - 2**
    AND l_shipmode IN ('MAIL', 'SHIP')
    AND l_commitdate < l_receiptdate
    AND l_shipdate < l_commitdate
    AND l_receiptdate >= date'1994-01-01' AND l_receiptdate < date'1994-01-01' + interval 1 year
GROUP BY
    l_shipmode
ORDER BY
    l_shipmode;

```
image

Is it right?

**Comment by marin-ma** [comment]
> Hi, I modify TPCH Q12 and run with this pr, the shj will fallback:
> 
> ```
> SELECT /*+ SHUFFLE_HASH(ch_lineitem) */
>     l_shipmode,
>     sum(
>         CASE WHEN o_orderpriority = '1-URGENT'
>             OR o_orderpriority = '2-HIGH' THEN
>             1
>         ELSE
>             0
>         END) AS high_line_count,
>     sum(
>         CASE WHEN o_orderpriority <> '1-URGENT'
>             AND o_orderpriority <> '2-HIGH' THEN
>             1
>         ELSE
>             0
>         END) AS low_line_count
> FROM
>     ch_orders,
>     ch_lineitem
> WHERE
>     **o_orderkey = l_orderkey - 2**
>     AND l_shipmode IN ('MAIL', 'SHIP')
>     AND l_commitdate < l_receiptdate
>     AND l_shipdate < l_commitdate
>     AND l_receiptdate >= date'1994-01-01' AND l_receiptdate < date'1994-01-01' + interval 1 year
> GROUP BY
>     l_shipmode
> ORDER BY
>     l_shipmode;
> ```
> 
> image
> 
> Is it right?

The Exchange fallback is because we don't support non-AttributeReference expression in repartition expression, but Join didn't fallback.

**Comment by zzcclp** [comment]
Got it.

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
