### PR TITLE
[VL] Include Velox non-contiguous allocations into Spark memory manager's accountation

### PR DESCRIPTION
**Pull request by zhztheplayer**
Relate to #1194

### CODE REVIEW

**Comment by zhouyuan** [comment]
@jackylee-ch

**Review by zhejiangxiaomai — APPROVED** [review]

**Comment by zhztheplayer** [comment]
@jackylee-ch Hi Jacky, since this patch is relatively independent to any specific bug/issue so I'm going to merge in advance. Please still let me know once you have any updates.

**Comment by zhztheplayer** [comment]
cc @zhouyuan

**Comment by jackylee-ch** [comment]
@zhztheplayer Sorry for late response. I test TPCDS with this pr last night, and there were still some executors were killed by excessive memory usage.

**Pull request merged**
