### PR TITLE
[GLUTEN-2673][CH] Fallback when lpad/rpad third arg is non-literal

### PR DESCRIPTION
**Pull request by taiyang-li**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#2673)

### CODE REVIEW

**Comment by taiyang-li** [comment]
```
ERROR: failed to solve: centos:7: failed to do request: Head "https://registry-1.docker.io/v2/library/centos/manifests/7": Service Unavailable (did you mean centos?)
Error: Process completed with exit code 1. 
``` 

failed velox not related to pr changes.

**Comment by taiyang-li** [comment]
failed ut not related to this pr.  cc @PHILO-HE  @zzcclp

**Review by zzcclp — DISMISSED** [review]
LGTM

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
