### PR TITLE
[VL] Add bit_get and bit_count function support for Velox backend

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

Since oap/velox has already include this commit after rebase, let's add it.

## How was this patch tested?

bit_get tested in GlutenBitwiseExpressionsSuite.
bit_count tested in VeloxFunctionsValidateSuite.

### CODE REVIEW

**Comment by Yohahaha** [comment]
Hi @PHILO-HE @rui-mo 

This PR is ready for review, would you help take a look?
The reason of CI failure is network problem.

**Comment by Yohahaha** [comment]
Please ignore lots of line changes of doc, my IDE will auto update it and I have no idea to avoid it.

**Comment by Yohahaha** [comment]
CI still has network issue.

**Comment by Yohahaha** [comment]
Most CI success, only few of these failed for network issue, I think it's enough to merge, could someone help verify it? @zhejiangxiaomai @PHILO-HE @rui-mo

**Comment by zhejiangxiaomai** [comment]
> Most CI success, only few of these failed for network issue, I think it's enough to merge, could someone help verify it? @zhejiangxiaomai @PHILO-HE @rui-mo

I restarted failed job.

**Review by PHILO-HE — APPROVED** [review]
Looks great!
I understand the table is easily altered due to auto alignment. So it may be better to make a bulk update for `velox-backend-support-progress` in the future. I will track the function support state and do a bulk update. cc @rui-mo

@Yohahaha, it's OK to keep the doc change here. Let's follow the above convention in new PR. Many thanks!

**Pull request merged**
