### PR TITLE
[GLUTEN-1524][CH]support function to_date/to_timestamp/dayofweek/weekday/btrim/ltrim/rtrim

### PR DESCRIPTION
**Pull request by taiyang-li**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#1524)

### CODE REVIEW

**Comment by taiyang-li** [comment]
@rui-mo maybe we need to append to_date/to_timestamp to velox's blacklist before they are supported by velox.

**Comment by rui-mo** [comment]
> @rui-mo maybe we need to append to_date/to_timestamp to velox's blacklist before they are supported by velox. I'm not sure, can you confirm it?

OK, let's wait for the CI.

**Review by rui-mo — APPROVED** [review]

**Comment by taiyang-li** [comment]
Velox failed uts.  cc @rui-mo 
```
2023-05-05T10:42:05.2000116Z E0505 18:42:05.199209 48497 Exceptions.h:68] Line: ../../velox/substrait/SubstraitParser.cpp:136, Function:parseType, Expression:  Parsing for Substrait type not supported: timestamp {
2023-05-05T10:42:05.2001968Z Type is not supported due to:Parsing for Substrait type not supported: timestamp {
2023-05-05T10:42:05.2002960Z   nullability: NULLABILITY_NULLABLE
2023-05-05T10:42:05.2003617Z }
2023-05-05T10:42:05.2004237Z   nullability: NULLABILITY_NULLABLE
2023-05-05T10:42:05.2004867Z }
2023-05-05T10:42:05.2005175Z
2023-05-05T10:42:05.2005560Z Validation failed for input types in ProjectRel.
2023-05-05T10:42:05.2006453Z , Source: RUNTIME, ErrorCode: NOT_IMPLEMENTED
```

**Comment by taiyang-li** [comment]
I found the new adding trim functions introduced by (https://github.com/Kyligence/ClickHouse/pull/287) has bugs, and they are fixed in this pr.

**Comment by taiyang-li** [comment]
```
2023-05-08T02:22:07.5509959Z [10/53] Performing download step (download, verify and extract) for 'zlib_ep'
2023-05-08T02:22:07.5512095Z FAILED: zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download /opt/gluten/ep/build-arrow/build/arrow_ep/cpp/build/orc_ep-prefix/src/orc_ep-build/zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download
2023-05-08T02:22:07.5516103Z cd /opt/gluten/ep/build-arrow/build/arrow_ep/cpp/build/orc_ep-prefix/src/orc_ep-build/zlib_ep-prefix/src && /usr/bin/cmake -P /opt/gluten/ep/build-arrow/build/arrow_ep/cpp/build/orc_ep-prefix/src/orc_ep-build/zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download-RELEASE.cmake && /usr/bin/cmake -E touch /opt/gluten/ep/build-arrow/build/arrow_ep/cpp/build/orc_ep-prefix/src/orc_ep-build/zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download
2023-05-08T02:22:07.5519128Z CMake Error at zlib_ep-stamp/zlib_ep-download-RELEASE.cmake:49 (message):
2023-05-08T02:22:07.5519987Z   Command failed: 1
2023-05-08T02:22:07.5520363Z
2023-05-08T02:22:07.5522580Z    '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/opt/gluten/ep/build-arrow/build/arrow_ep/cpp/build/orc_ep-prefix/src/orc_ep-build/zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download-RELEASE-impl.cmake'
2023-05-08T02:22:07.5523880Z
2023-05-08T02:22:07.5524092Z   See also
2023-05-08T02:22:07.5524423Z
2023-05-08T02:22:07.5525633Z     /opt/gluten/ep/build-arrow/build/arrow_ep/cpp/build/orc_ep-prefix/src/orc_ep-build/zlib_ep-prefix/src/zlib_ep-stamp/zlib_ep-download-*.log
2023-05-08T02:22:07.5526481Z
2023-05-08T02:22:07.5526496Z

``` 

Velox compile failed, but seems not related to this pr  cc @rui-mo @zzcclp

**Review by zzcclp — APPROVED** [review]
LGTM

**Review by liuneng1994 — DISMISSED** [review]
LGTM

**Review by rui-mo — APPROVED** [review]

**Comment by rui-mo** [comment]
@taiyang-li All checks were passed.

**Pull request merged**
