### PR TITLE
[VL] Avoid shrinking the binary buffer which triggers spill

### PR DESCRIPTION
**Pull request by marin-ma**
If spill is triggered by resizing binary partition buffer, should avoid shrinking itself during reclaiming memory from shrinking partition buffers. Because shrinking the buffer can possibly invalid the original underlying `ptr`.

### CODE REVIEW

**Comment by marin-ma** [comment]
@jackylee-ch @zhztheplayer Could you help to review? Thanks!

**Review by zhouyuan — APPROVED** [review]
👍

**Pull request merged**
