### PR TITLE
[VL] make VeloxMemoryPool::allocate conform to velox::MemoryPoolImpl::allocate

### PR DESCRIPTION
**Pull request by zuochunwei**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zuochunwei** [comment]
@zhztheplayer

**Comment by zhztheplayer** [comment]
Running TPC benchmarking now.

**Comment by zhztheplayer** [comment]
Update: there is still ~3% performance regression. Let's hold off for a while.

**Comment by FelixYBW** [comment]
solved by another way

**Pull request closed without merging**
