### PR TITLE
[GLUTEN-1386][CH] Improve max(NULL)/min(NULL) execution efficiency

### PR DESCRIPTION
**Pull request by KevinyhZou**
## What changes were proposed in this pull request?
Improve max(NULL)/min(NULL) execution efficiency: The max(NULL)/min(NULL) aggreate function's return type is NullType, which make the transform support validation to be false, and lead this query can not be exeuecte on the native engine.

So we make the change, let the transform support validation be supported on NullType

(Fixes: \#1386)

## How was this patch tested?
manual tests

This is tested on clickhouse-backend.  The tested query ` select id, max(NULL), min(NULL) from test_tbl3 where id > 0  group by id limit 3` , the tested table has about 63000000 rows, and stored as parquet, which archived 60% improvement.

### CODE REVIEW

**Comment by zhztheplayer** [comment]
Should we use the same naming convention e.g. `[CH]` on the lhs of the PR title? I see there are some `[Clickhouse-backend]`s and some `[CH]`s currently.

**Comment by KevinyhZou** [comment]
> Should we use the same naming convention e.g. `[CH]` on the lhs of the PR title? I see there are some `[Clickhouse-backend]`s and some `[CH]`s currently.

done

**Comment by zzcclp** [comment]
please add the test cases.

**Comment by KevinyhZou** [comment]
The test case add done，and merge pr : https://github.com/oap-project/gluten/pull/1383 into this,  as it will cause core when query max(NULL) / min(NULL) . Please have a review at this pr. @zzcclp

**Review by zzcclp — APPROVED** [review]
LGTM

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
