### PR TITLE
Velox backend: Enable partial SQL tests in GlutenSQLQueryTestSuite.

### PR DESCRIPTION
**Pull request by lviiii**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Review by jinchengchenghh — APPROVED** [review]
Wait for CI

**Comment by lviiii** [comment]
> 

Passed

**Comment by lviiii** [comment]
>

**Comment by lviiii** [comment]
> Wait for CI

Passed

**Pull request merged**
