### PR TITLE
[GLUTEN-4860][CELEBORN] Replace celeborn link

### PR DESCRIPTION
**Pull request by kerwin-zk**
## What changes were proposed in this pull request?

#4860

## How was this patch tested?

CI

### CODE REVIEW

**Comment by kerwin-zk** [comment]
@ulysses-you @PHILO-HE  cc

**Comment by ulysses-you** [comment]
it seems we did not touch ch backend celeborn.. how can the CI passed ?

**Comment by kerwin-zk** [comment]
> it seems we did not touch ch backend celeborn.. how can the CI passed ?

@ulysses-you CH's CH's CI is maintained internally, and I have sent them the new link.

**Review by ulysses-you — APPROVED** [review]
I'm going to merge this to unblock other prs.

**Comment by ulysses-you** [comment]
@kerwin-zk can you take a look at this issue ?

https://github.com/oap-project/gluten/actions/runs/8166034936/job/22324135499
```
24/03/06 11:53:28 WARN ShuffleClientImpl: Shuffle client has been shutdown!
bash: /opt/apache-celeborn-0.3.0-incubating-bin/sbin/stop-worker.sh: No such file or directory
Error: Process completed with exit code 127.
```

**Comment by PHILO-HE** [comment]
> @kerwin-zk can you take a look at this issue ?
> 
> https://github.com/oap-project/gluten/actions/runs/8166034936/job/22324135499
> 
> ```
> 24/03/06 11:53:28 WARN ShuffleClientImpl: Shuffle client has been shutdown!
> bash: /opt/apache-celeborn-0.3.0-incubating-bin/sbin/stop-worker.sh: No such file or directory
> Error: Process completed with exit code 127.
> ```

@ulysses-you, this is another issue caused by CI docker image update in last night. Just created a PR: https://github.com/oap-project/gluten/pull/4862

**Pull request merged**
