### PR TITLE
[CH-313] support functions position/locate

### PR DESCRIPTION
**Pull request by exmy**
support functions position/locate for CH

related issue: [CH-313](https://github.com/Kyligence/ClickHouse/issues/313)

test by CH[[314]]

### CODE REVIEW

**Comment by exmy** [comment]
test this please

**Comment by exmy** [comment]
The ch-backend-test failed seems the cmake version does not meet the requirements.

image

**Review by zzcclp — APPROVED** [review]
LGTM.
BTW, please rebase

**Comment by exmy** [comment]
> LGTM. BTW, please rebase

thanks for review, rebase have done

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
