### PR TITLE
[HOTFIX] Remove parameter 'loadch'

### PR DESCRIPTION
**Pull request by zzcclp**
Remove parameter 'loadch'.

### CODE REVIEW

**Comment by QiangCai** [comment]
LGTM, in the future, better to extract interface, and the different library has different implement. it can help to reduce the usage of if-condition code.

**Comment by zzcclp** [comment]
> LGTM, in the future, better to extract interface, and the different library has different implement. it can help to reduce the if-condition code.

Yeah, I am doing this.

**Comment by rui-mo** [comment]
Verified locally. LGTM.

**Comment by rui-mo** [comment]
The close was accidental.

**Comment by weiting-chen** [comment]
LGTM.

**Comment by rui-mo** [comment]
@marin-ma any comment?

**Comment by marin-ma** [comment]
LGTM.

**Pull request merged**
