### PR TITLE
[VL][CI] Fix fallback to columnar shuffle in celeborn test

### PR DESCRIPTION
**Pull request by PHILO-HE**
## What changes were proposed in this pull request?

Celeborn is not correctly installed, which causes CI test actually falls back to columnar shuffle.

## How was this patch tested?

CI verification.

### CODE REVIEW

**Comment by zhouyuan** [comment]
@kerwin-zk could you please help to take a look on this? it seems some wrong results found on tpcds Q51

thanks, -yuan

**Comment by PHILO-HE** [comment]
Post the error message:
Executing SQL query from resource path /tpcds-queries/q51.sql...
Error running query q51.  Error: FATAL: java.lang.RuntimeException: Error while decoding: java.lang.ArithmeticException: Decimal precision 34 exceeds max precision 27

**Comment by kerwin-zk** [comment]
OK, I'll take a look.

**Comment by kerwin-zk** [comment]
@PHILO-HE @zhouyuan I checked and found that the exception was caused by this part of the [code](https://github.com/marin-ma/gluten/blob/52092a3f94bab317251f7c8ac776ddf4b4c9fe9a/cpp/velox/memory/VeloxColumnarBatch.cc#L54) in the PR(#4415). CI can pass if this part of the code is rolled back.

**Comment by ulysses-you** [comment]
@kerwin-zk does it mean the celeborn shuffle code path is broken at present  ?

**Comment by kerwin-zk** [comment]
@ulysses-you Yes, code containing #4415  might have issues with some corner cases when using Celeborn.

**Comment by ulysses-you** [comment]
thank you for the confirming

**Comment by marin-ma** [comment]
@PHILO-HE Thanks for investigating this issue. Let's merge this one first to ensure the CI operates correctly. I will look into the corner case issue.

**Review by marin-ma — APPROVED** [review]

**Comment by PHILO-HE** [comment]
> @PHILO-HE Thanks for investigating this issue. Let's merge this one first to ensure the CI operates correctly. I will look into the corner case issue.

@marin-ma, thanks so much for your time!

**Pull request merged**
