### PR TITLE
[GLUTEN-1925] a cleaner way to solve const column(Avoid SparkPlan Tag…

### PR DESCRIPTION
**Pull request by binmahone**
…). This may obsolete #2900

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by binmahone** [comment]
这个PR的思路是，直接对最后一个WholeStageTransformer标记一个flag，告知它需要对他的input进行materlize block处理。

**Review by taiyang-li — APPROVED** [review]
LGTM

**Comment by binmahone** [comment]
Run Gluten Clickhouse CI

**Review by zzcclp — DISMISSED** [review]
LGTM

**Review by taiyang-li — APPROVED** [review]

**Review by JkSelf — DISMISSED** [review]
LGTM.

**Review by baibaichen — APPROVED** [review]
LGTM

**Pull request merged**
