### PR TITLE
[VL] add support for reading ORC

### PR DESCRIPTION
**Pull request by zuochunwei**
## What changes were proposed in this pull request?
add support for reading ORC files encoded with RLE v1/v2

the PR [oap-velox orc supprt](https://github.com/oap-project/velox/pull/229/files) should be merged before this PR

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zuochunwei** [comment]
@JkSelf

**Comment by JkSelf** [comment]
@zuochunwei Can you also add some orc test in gluten unit test scala side to check whether offload to native and the correctness？

**Comment by JkSelf** [comment]
> 

We can read an orc file to check whether the scan operator can be offloaded and then verify the correctness to compare with vanilla spark. We can also add the orc file format test in TPC-H/DS later.

**Comment by JkSelf** [comment]
@zuochunwei You may need to change the velox repo and branch [here ](https://github.com/oap-project/gluten/blob/9dfc8f8eb7674f49054a76cc97010a60bf48911e/ep/build-velox/src/get_velox.sh#L5)if you changed the velox code.

**Comment by zuochunwei** [comment]
> @zuochunwei You may need to change the velox repo and branch [here ](https://github.com/oap-project/gluten/blob/9dfc8f8eb7674f49054a76cc97010a60bf48911e/ep/build-velox/src/get_velox.sh#L5)if you changed the velox code.

I proposed a corresponding PR for `oap-project/velox`, please refer to [PR](https://github.com/oap-project/velox/pull/229/)

**Comment by zuochunwei** [comment]
> > 
> 
> We can read an orc file to check whether the scan operator can be offloaded and then verify the correctness to compare with vanilla spark. We can also add the orc file format test in TPC-H/DS later.

We have tested read orc file through the TableScan operator, and it's OK

**Comment by zhejiangxiaomai** [comment]
Here is a example to use your local branch to test gluten CI. @zuochunwei 
https://github.com/oap-project/gluten/pull/1503/files

**Comment by zuochunwei** [comment]
> Here is a example to use your local branch to test gluten CI. @zuochunwei https://github.com/oap-project/gluten/pull/1503/files

OK, thank you!

**Comment by JkSelf** [comment]
@zuochunwei I tested orc scan in gluten with following unit test. It can work. Can you add this unit test in TestOperator.scala in this PR? And we can add the orc file format test in TPC-H/DS in the following PRs later.

`test("orc scan") {`
 ` val df = spark.read.format("orc").load("./cpp/velox/benchmarks/data/bm_lineitem/orc/lineitem.orc") `
  `df.createOrReplaceTempView("lineitem_orc") `
 ` runQueryAndCompare( `
   ` "select l_orderkey from lineitem_orc") { df => { `
   ` assert(getExecutedPlan(df).count(plan => { `
     ` plan.isInstanceOf[BatchScanExecTransformer]}) == 1) `
 ` }} `
`} `

**Comment by zuochunwei** [comment]
> @zuochunwei I tested orc scan in gluten with following unit test. It can work. Can you add this unit test in TestOperator.scala in this PR? And we can add the orc file format test in TPC-H/DS in the following PRs later.
> 
> `test("orc scan") {` `val df = spark.read.format("orc").load("./cpp/velox/benchmarks/data/bm_lineitem/orc/lineitem.orc")` `df.createOrReplaceTempView("lineitem_orc") ` `runQueryAndCompare(` `"select l_orderkey from lineitem_orc") { df => {` `assert(getExecutedPlan(df).count(plan => {` `plan.isInstanceOf[BatchScanExecTransformer]}) == 1)` `}}` `} `

done

**Comment by zhejiangxiaomai** [comment]
run `mvn clean install -Pspark-3.2 -Pspark-ut -Pbackends-velox` can see code style error.

**Review by zhejiangxiaomai — APPROVED** [review]
Thanks.

**Pull request merged**
