### PR TITLE
[VL] Decimal sum support overflow

### PR DESCRIPTION
**Pull request by liujiayi771**
## What changes were proposed in this pull request?

decimal sum support overflow

## How was this patch tested?

ci test

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by liujiayi771** [comment]
@rui-mo Can you help merge PR in velox?

**Comment by rui-mo** [comment]
> There is no need to wait for the CH test to finish running. I only modified the VeloxTestSettings on the gluten side.

Makes sense to me.

**Review by rui-mo — APPROVED** [review]

**Comment by rui-mo** [comment]
https://github.com/oap-project/gluten/issues/1217

**Pull request merged**
