### PR TITLE
[GLUTEN-2970][CH] respect clickhouse settings: query_plan_enable_optimizations

### PR DESCRIPTION
**Pull request by taiyang-li**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#2970)

How to enable ch query plan optimization? 
By default ch query plan optimization is disabled, you can use `--conf spark.gluten.sql.columnar.backend.ch.runtime_settings.query_plan_enable_optimizations=true` to enable it.

### CODE REVIEW

**Comment by baibaichen** [comment]
we  need a ut to test `query_plan_enable_optimizations = true`

**Comment by taiyang-li** [comment]
> we need a ut to test `query_plan_enable_optimizations = true`

done

**Comment by baibaichen** [comment]
1. `true `= Gluten Perf Test Pass, GlutenWithCHStandard tpch-data-sf100 total time 121296
2. `false `= Gluten Perf Test Pass, GlutenWithCHStandard tpch-data-sf100 total time 117912

no significant change

**Review by baibaichen — APPROVED** [review]
LGTM

**Pull request merged**
