### PR TITLE
[Gluten-466] Fix maven build issue

### PR DESCRIPTION
**Pull request by kerwin-zk**
## What changes were proposed in this pull request?
#466 

## How was this patch tested?
mvn clean package -Pbackends-velox -Pfull-scala-compiler -DskipTests -Dcheckstyle.skip -Dbuild_cpp=ON -Dbuild_velox=ON -Dbuild_velox_from_source=ON -Dbuild_arrow=ON

### CODE REVIEW

**Comment by jinchengchenghh** [comment]
I'm not sure if this cause the problem. I will rerun checks
Executing SQL query from resource path /tpch-queries-noint-nodate/q16.sql...
Exception in thread "main" java.lang.NoSuchMethodError: io.glutenproject.execution.VeloxHashJoinLikeExecTransformer.antiJoinWorkaroundNeeded()Z
	at io.glutenproject.execution.VeloxHashJoinLikeExecTransformer.$init$(VeloxHashJoinExecTransformer.scala:53)
	at io.glutenproject.execution.VeloxBroadcastHashJoinExecTransformer.<init>(VeloxHashJoinExecTransformer.scala:374)
	at io.glutenproject.backendsapi.velox.VeloxSparkPlanExecApi.genBroadcastHashJoinExecTransformer(VeloxSparkPlanExecApi.scala:142)
	at io.glutenproject.extension.columnar.AddTransformHintRule.addTransformableTag(TransformHintRule.scala:257)
	at io.glutenproject.extension.columnar.AddTransformHintRule.addTransformableTags(TransformHintRule.scala:114)
	at io.glutenproject.extension.columnar.AddTransformHintRule.$anonfun$addTransformableTags$1(TransformHintRule.scala:115)

**Review by jinchengchenghh — APPROVED** [review]

**Comment by zhztheplayer** [comment]
The patch breaks gluten-it's build:

```
[ERROR] Failed to execute goal on project gluten-it: Could not resolve dependencies for project io.glutenproject:gluten-it:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: io.glutenproject:spark-sql-columnar-shims-common:jar:1.0.0-SNAPSHOT, io.glutenproject:gluten-jvm:jar:1.0.0-SNAPSHOT, io.glutenproject:spark-sql-columnar-shims-spark32:jar:1.0.0-SNAPSHOT: Could not find artifact io.glutenproject:spark-sql-columnar-shims-common:jar:1.0.0-SNAPSHOT -> [Help 1]
```

It looks that Maven puts some tricky stuffs around Jar classifier. I tried to specify classifier in gluten-it's pom.xml (https://github.com/zhztheplayer/gluten-it/commit/e507bd3f0de5165162435229075744f410f38712) but that doesn't work.

@jinchengchenghh Not sure if you'll have some clues about the issue?

**Comment by zhztheplayer** [comment]
The patch is somehow dangerous to Velox backend's CI: CI will always find Gluten jars that are without `3.2` classifier, that were definitely out-of-date because of this patch (the patch intends to stop producing non-classifier jars). I am reverting the changes and reopening https://github.com/oap-project/gluten/issues/466.

@kerwin-zk @jinchengchenghh Sorry for the inconvenience and let's work closely when we get some free time to come up with a better solution.

**Comment by kerwin-zk** [comment]
> The patch breaks gluten-it's build (in a clean environment):
> 
> 
> 
> ```
> 
> [ERROR] Failed to execute goal on project gluten-it: Could not resolve dependencies for project io.glutenproject:gluten-it:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: io.glutenproject:spark-sql-columnar-shims-common:jar:1.0.0-SNAPSHOT, io.glutenproject:gluten-jvm:jar:1.0.0-SNAPSHOT, io.glutenproject:spark-sql-columnar-shims-spark32:jar:1.0.0-SNAPSHOT: Could not find artifact io.glutenproject:spark-sql-columnar-shims-common:jar:1.0.0-SNAPSHOT -> [Help 1]
> 
> ```
> 
> 
> 
> It looks that Maven puts some tricky stuffs around Jar classifier. I tried to specify classifier in gluten-it's pom.xml (https://github.com/zhztheplayer/gluten-it/commit/e507bd3f0de5165162435229075744f410f38712) but that doesn't work.
> 
> 
> 
> @jinchengchenghh Not sure if you'll have some clues about the issue?

@zhztheplayer Can you elaborate on how to reproduce this exception?

**Comment by zhztheplayer** [comment]
@kerwin-zk 

You can try replay the commands in CI script https://github.com/oap-project/gluten/blob/903ef0ccc4881d53f5d432a6faddf8c648db6f0f/.github/workflows/unittests.yml#L63 in a clean environment (note that in CI we enabled maven cache so the PR didn't fail CI).

For example

```
# After installing Gluten
git clone -b main https://github.com/zhztheplayer/gluten-it.git gluten-it
cd gluten-it
mvn clean package -Pspark-3.2 -Pgluten-velox -Darrow.version=10.0.0-SNAPSHOT
```

**Pull request merged**
