### PR TITLE
[OPPRO-81] Rework JNI loading process

### PR DESCRIPTION
**Pull request by zhztheplayer**

### CODE REVIEW

**Comment by zhztheplayer** [comment]
@rui-mo @marin-ma @zzcclp Would you like to help me review or verify the PR for Velox / CH BEs? It just passed tests for Gazelle-CPP in my environment.

**Review by zzcclp — APPROVED** [review]
LGTM, verified locally with ClickHouse backend.

**Comment by marin-ma** [comment]
Verified locally with Velox backend.

**Comment by rui-mo** [comment]
Verified on Jenkins.

**Pull request merged**
