### PR TITLE
[OPPRO-169] Use the global memory pool when creating TaskCursor to avoid the pool released in velox

### PR DESCRIPTION
**Pull request by JkSelf**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by JkSelf** [comment]
@zhztheplayer @marin-ma   Please help to review. Thanks.

**Comment by zhztheplayer** [comment]
Update to newest Velox main should solve this I guess.

https://github.com/oap-project/velox/commits/main

**Comment by marin-ma** [comment]
@JkSelf Could you help to verify based on the lastest velox/main and gluten/main? We will move on to use Hongze's solution that has been merged yesterday https://github.com/oap-project/gluten/pull/203. This should fix the coredump issue even if we don't pass the pointer of the global memory pool to Velox's pipeline.

**Comment by JkSelf** [comment]
@zhztheplayer @marin-ma Thanks for your information. This issue can be fixed after rebasing the gluten and velox to latest code.
And I will close this PR.

**Pull request closed without merging**
