### PR TITLE
[WIP][CORE] Add PullOutPreProject rule to decouple substrait pre-project

### PR DESCRIPTION
**Pull request by ulysses-you**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by FelixYBW** [comment]
Title?

**Comment by ulysses-you** [comment]
thank you @FelixYBW for the reminder. This pr is still working in process. I will refine it when it's ready.

**Pull request closed without merging**
