### PR TITLE
[VL][Picked] fix collect_list/collect_set map

### PR DESCRIPTION
**Pull request by Ma-Jian1**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by weixiuli** [comment]
The velox has supported  the collect_list/collect_set？

**Comment by Ma-Jian1** [comment]
> The velox has supported the collect_list/collect_set？

`collect_list/collect_set` can be mapped to  `array_agg/set_agg` if no unittest failed

**Comment by Ma-Jian1** [comment]
This PR can be closed as the relevant changes have already been included in another PR（ https://github.com/PHILO-HE/gluten/commit/b6c0ceaa04aeb416313c89f3eacf09fcb54dad49 ）

**Comment by PHILO-HE** [comment]
This PR is imported to https://github.com/oap-project/gluten/pull/2669, for better debugging. Closing this one. Thanks!

**Pull request closed without merging**
