### PR TITLE
[VL] Daily Update Velox Version (2024-01-05)

### PR DESCRIPTION
**Pull request by marin-ma**
```
8321b3e03 (upstream/main) Add error log in ~MemoryManager (#8262)
8ff2246f6 Add December 2023 monthly update (#8264)
b35147702 Support fuzzing expressions with specific output type in ExpressionFuzzer. (#7976)
3589be95c Remove tests of debug time checks (#8261)
ff6a31fe5 Use string output stream from flex scanners (#8244)
c9878702b Fix flaky AggregationTest.reclaimFromAggregation (#8255)
4cd534b0d Fix GA scheduled job of spark fuzzers (#8251)
8e59fa1fb Optimize casting generic writer to primitives. (#8193)
0616e4ccc Optimizing casting GenericView to primitives. (#8192)
a289ac7eb Improve tmToString and relating document (#8250)
0e25d474c Fix approx_distinct for TIMESTAMP inputs (#8164)
b42ace1a5 Back out "Change cpu driver slicing limit to 1 second by default" (#8248)
4c90d8bc2 Minor refactor in array function registration. (#8247)
f12b055b9 Add checkUsageLeak flag to arbitrator (#8219)
```

### CODE REVIEW

**Review by zhztheplayer — APPROVED** [review]

**Review by zhztheplayer — CHANGES_REQUESTED** [review]
Seems we brought some generated code into Velox's source

https://github.com/oap-project/velox/blob/2024_01_05/modify_velox.patch
https://github.com/oap-project/velox/blob/2024_01_05/third_party/modify_arrow.patch

@marin-ma

**Comment by marin-ma** [comment]
> Seems we brought some generated code into Velox's source
> 
> https://github.com/oap-project/velox/blob/2024_01_05/modify_velox.patch https://github.com/oap-project/velox/blob/2024_01_05/third_party/modify_arrow.patch
> 
> @marin-ma

Oops, sorry...

**Comment by marin-ma** [comment]
@zhztheplayer Removed. PTAL. Thanks!

**Review by zhztheplayer — APPROVED** [review]
Thanks!

**Pull request merged**
