### PR TITLE
[VL] Add left function support

### PR DESCRIPTION
**Pull request by myandpr**
## What changes were proposed in this pull request?

"left" function is not yet implemented in Gluten.
https://github.com/oap-project/gluten/blob/main/docs/SupportProgress.md

Support [left](https://spark.apache.org/docs/latest/api/sql/#left) function for Gluten in Velox.

### Example
```
> SELECT left('Spark SQL', 3);
 Spa
> SELECT left(encode('Spark SQL', 'utf-8'), 3);
 Spa
```

### Related PR in Velox
The left function has been implemented in velox.
https://github.com/facebookincubator/velox/pull/5505

### CODE REVIEW

**Comment by rui-mo** [comment]
Thank you for the great work! But the Velox branch used by Gluten is not up to date, and we are still working on the rebase. Maybe this PR needs to be pended till the commit on `left` function is pulled.
cc @zhejiangxiaomai

**Comment by myandpr** [comment]
> 

Thanks for your review. I will submit a PR about left() to https://github.com/oap-project/velox

**Comment by PHILO-HE** [comment]
> > 
> 
> Thanks for your review. I will submit a PR about left() to https://github.com/oap-project/velox

Hi @myandpr, no need to submit PR to oap/velox. As it will include your velox patch after code rebase is done on our side. Thanks!

**Comment by myandpr** [comment]
> > > 
> > 
> > 
> > Thanks for your review. I will submit a PR about left() to https://github.com/oap-project/velox
> 
> Hi @myandpr, no need to submit PR to oap/velox. As it will include your velox patch after code rebase is done on our side. Thanks!

OK, thank you for following up this PR.

**Comment by PHILO-HE** [comment]
@myandpr, could you please fix the code style violation? See https://github.com/oap-project/gluten/blob/main/docs/developers/NewToGluten.md#javascala-code-style.

**Comment by PHILO-HE** [comment]
This PR has been ported to #3588 already merged. Thanks so much for your contribution!

**Pull request closed without merging**
