### PR TITLE
[VL] Support custom cmake deps download url

### PR DESCRIPTION
**Pull request by Yohahaha**
Specify deps download url by `export GLUTEN_XXX_URL=path` if needed.

### CODE REVIEW

**Comment by Yohahaha** [comment]
@PHILO-HE @marin-ma please help review this patch, thank you!

**Comment by marin-ma** [comment]
If user set `GLUTEN_xxx_URL` environment variable, it's generally expected that they should also need to set `GLUTEN_xxx_SHA256`, or the checksum verification would fail. Is that correct?

**Comment by Yohahaha** [comment]
> If user set `GLUTEN_xxx_URL` environment variable, it's generally expected that they should also need to set `GLUTEN_xxx_SHA256`, or the checksum verification would fail. Is that correct?

No, checksum is optional. checksum would be empty if user only set `GLUTEN_XXX_URL`.

**Comment by marin-ma** [comment]
LGTM. Thanks!

**Review by marin-ma — APPROVED** [review]

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Comment by Yohahaha** [comment]
could we meger?

**Comment by Yohahaha** [comment]
thank you!

**Pull request merged**
