### PR TITLE
[VL] Minor refactor c2r and r2c cpp codes

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

Clean headers and separate default implementation with Velox's.

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Review by FelixYBW — APPROVED** [review]

**Comment by Yohahaha** [comment]
Hi @zhejiangxiaomai, CI has network issue, but some check are success, could we merge this?

**Comment by zhztheplayer** [comment]
> Hi @zhejiangxiaomai, CI has network issue, but some check are success, could we merge this?

GHA CI reports this:

```
2023-08-02T10:20:35.4152983Z In file included from /opt/gluten/cpp/core/utils/TestUtils.h:33,
2023-08-02T10:20:35.4153752Z                  from /opt/gluten/cpp/velox/benchmarks/ColumnarToRowBenchmark.cc:38:
2023-08-02T10:20:35.4155522Z /opt/gluten/cpp/velox/benchmarks/ColumnarToRowBenchmark.cc: In member function ‘virtual void gluten::GoogleBenchmarkColumnarToRowCacheScanBenchmark::operator()(benchmark::State&)’:
2023-08-02T10:20:35.4157385Z /opt/gluten/cpp/velox/benchmarks/ColumnarToRowBenchmark.cc:161:63: error: ‘using element_type = class gluten::VeloxColumnarToRowConverter’ {aka ‘class gluten::VeloxColumnarToRowConverter’} has no member named ‘write’
2023-08-02T10:20:35.4159887Z   161 |         TIME_NANO_OR_THROW(writeTime, columnarToRowConverter->write(cb));
2023-08-02T10:20:35.4160438Z       |                                                               ^~~~~
2023-08-02T10:20:35.4161215Z /opt/gluten/cpp/core/utils/macros.h:83:17: note: in definition of macro ‘TIME_NANO_OR_THROW’
2023-08-02T10:20:35.4161871Z    83 |     auto __s = (expr);                                                                 \
2023-08-02T10:20:35.4184841Z       |                 ^~~~
2023-08-02T10:20:35.4186041Z /opt/gluten/cpp/velox/benchmarks/ColumnarToRowBenchmark.cc: In member function ‘virtual void gluten::GoogleBenchmarkColumnarToRowIterateScanBenchmark::operator()(benchmark::State&)’:
2023-08-02T10:20:35.4187703Z /opt/gluten/cpp/velox/benchmarks/ColumnarToRowBenchmark.cc:217:63: error: ‘using element_type = class gluten::VeloxColumnarToRowConverter’ {aka ‘class gluten::VeloxColumnarToRowConverter’} has no member named ‘write’
2023-08-02T10:20:35.4189414Z   217 |         TIME_NANO_OR_THROW(writeTime, columnarToRowConverter->write(cb));
2023-08-02T10:20:35.4189936Z       |                                                               ^~~~~
2023-08-02T10:20:35.4190537Z /opt/gluten/cpp/core/utils/macros.h:83:17: note: in definition of macro ‘TIME_NANO_OR_THROW’
2023-08-02T10:20:35.4191031Z    83 |     auto __s = (expr);       
```

Can you have a check? Thanks.

**Comment by Yohahaha** [comment]
@zhztheplayer Sorry for that, will fix and check again.

**Comment by Yohahaha** [comment]
Most CI passed, except 2 check failed due to network issue.
Could you help take a look and review? @zhztheplayer @FelixYBW @zhejiangxiaomai

**Comment by zhejiangxiaomai** [comment]
> Most CI passed, except 2 check failed due to network issue. Could you help take a look and review? @zhztheplayer @FelixYBW @zhejiangxiaomai

I restarted failed CI job.

**Comment by Yohahaha** [comment]
Could we merge this PR? All CI were passed.

**Review by zhztheplayer — APPROVED** [review]

**Pull request merged**
