### PR TITLE
[GLUTEN-2891][VL]fix: Add support to scan Delta Lake tables

### PR DESCRIPTION
**Pull request by felipepessoto**
## What changes were proposed in this pull request?

Adds support to Delta Lake table

(Fixes: \#2891)

## How was this patch tested?

Manual test

### CODE REVIEW

**Comment by Yohahaha** [comment]
Thanks for the fix, have you try this patch in your test? Velox does not support Delta format as I know, does Delta file can be read as a normal parquet file?

**Comment by YannByron** [comment]
IMO, this is not enough. If enable column mapping, it will return NULL rows. And in Deletion Vector case, there will be some redundant rows.

**Comment by felipepessoto** [comment]
@YannByron in that case would we need to re-implement Delta features in Velox?
I was expecting Velox to help with Native Scan and some other operators and that Delta would work on top of it applying filters for DV, or changing the column name to scan before sending to Velox. It seems it is not the case.

**Comment by YannByron** [comment]
@felipepessoto 
Sorry for the late reply. I saw you have commented in https://github.com/oap-project/gluten/pull/2902. Let's discuss there.

**Pull request closed without merging**
