### PR TITLE
[GLUTEN-946] Upgrade arrow version to 10.0.1

### PR DESCRIPTION
**Pull request by leoluan2009**
## What changes were proposed in this pull request?

Current arrow version of 10.0.0-SNAPSHOT does not exist in [Maven Central Repository](https://search.maven.org/), so upgrade to 10.0.1.

Fix https://github.com/oap-project/gluten/issues/946

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zhztheplayer** [comment]
@leoluan2009 10.0.0-SNAPSHOT is from Gluten's forked Arrow branch https://github.com/oap-project/arrow/tree/backend_velox_main.

It was on the plan to move to 11.0.0 and before that we can just hold off updating a patch version like `10.0.0` -> `10.0.1`. Some required changes like [this one](https://issues.apache.org/jira/browse/ARROW-16673) which landed into `11.0.0` could be necessary if we dropped our forked Arrow repository.

**Comment by FelixYBW** [comment]
> be necessary if we dropped our fo

@zhztheplayer  how much modification we still need to apply to Arrow if we upgrade to Arrow 11? Can we use patch instead of private arrow?

**Comment by zhztheplayer** [comment]
Not much. I would expect no modification is needed from Gluten's code. But that needs a try.

**Comment by FelixYBW** [comment]
Let's close this one and upgrade to Arrow11

**Pull request closed without merging**
