### PR TITLE
[VL] Minor refactor for rename native Reader to ShuffleReader

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

Align with native ShuffleWriter naming.

### CODE REVIEW

**Comment by Yohahaha** [comment]
The reason of CI failure is https://github.com/oap-project/gluten/issues/2564,  @PHILO-HE could you help re-run failed jobs or merge this patch? this patch just do some renaming. Thanks!

**Review by PHILO-HE — APPROVED** [review]
LGTM! Thanks!

**Comment by PHILO-HE** [comment]
Let's ignore the irrelevant CI failure. Will merge the patch soon.

**Comment by Yohahaha** [comment]
Thanks for the merging!

**Pull request merged**
