### PR TITLE
[VL] Enable all tests of GlutenParquetFileFormatV1Suite/GlutenParquetFileFormatV2Suite for Spark33 and Spark34

### PR DESCRIPTION
**Pull request by Yohahaha**

### CODE REVIEW

**Comment by Yohahaha** [comment]
@PHILO-HE could you help rerun failed CI jobs and review it?

**Comment by PHILO-HE** [comment]
I found there are two code style violations.

```log
error file=/opt/gluten/gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFileFormatSuite.scala message=File line length exceeds 100 characters line=21
error file=/opt/gluten/gluten-ut/spark34/src/test/scala/org/apache/spark/sql/execution/datasources/parquet/GlutenParquetFileFormatSuite.scala message=File line length exceeds 100 characters line=23
Saving to outputFile=/opt/gluten/gluten-ut/spark34/scalastyle-output.xml
Processed 203 file(s)
Found 2 errors
Found 0 warnings
Found 0 infos
```

**Comment by Yohahaha** [comment]
Run Gluten Clickhouse CI

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Pull request merged**
