### PR TITLE
[GLUTEN-1680][CH] Fix ExpandTransform exception

### PR DESCRIPTION
**Pull request by exmy**
## What changes were proposed in this pull request?

(Fixes: \#1680)

## How was this patch tested?

manual test

### CODE REVIEW

**Comment by baibaichen** [comment]
Could you please describe more details? Thanks

**Comment by exmy** [comment]
> Could you please describe more details? Thanks

The method of `ExpandTransform::prepare()` have a statement `input.setNeeded()` which  is incorrectly placed inside the `if (!input.hasData()) {}`, this may cause exception `Cannot pull block from port which is not needed`.

**Comment by exmy** [comment]
cc @liuneng1994

**Comment by liuneng1994** [comment]
Run Gluten Clickhouse CI

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
