### PR TITLE
[VL] Daily Update Velox Version (2024-01-18)

### PR DESCRIPTION
**Pull request by rui-mo**
```
cea6a5 Fix shadowed variable in velox/expression/CastExpr-inl.h (8400)
842803 Reduce link parallelism to fix compilation OOM's (8403)
1ea0ff Fix format of documentation in SimpleAggregateAdapter.h (8402)
1ca874 Optimize computation of partition start rows in SortWindowBuild (7580)
2f9be0 Refactor HashBuild arbitration test (8376)
e2af9d Rename getDataType and getDataChannels funcs in HiveDataSink (8404)
82bcd3 Fix creation of DuckDB tables with arrays of boolean, tinyint and smallint (8408)
eb09be Actually ensure deterministic order of map keys in multimap_from_entries Presto function (8407)
587b5e Run Join Fuzzer on PRs (8414)
5a3c7f Extract initializeVerifiers and compareEquivalentPlanResults in AggregationFuzzer (8361)
d3f7b3 Refactor simdjson utilities (8397)
45d9f8 Use simdjson in cast from JSON operator (8216)
94a1b4 Extract storeBitsToByte to be reused (8416)
1d778e Minor refactor of ExchangeClient (8419)
99c2f8 Fix build for devtoolset-9 on CentOS 7 (8214)
```

### CODE REVIEW

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Comment by rui-mo** [comment]
@FelixYBW It seems the perf is back to 1226s. Is the noticed regression a random variance?

**Comment by FelixYBW** [comment]
> @FelixYBW It seems the perf is back to 1226s. Is the noticed regression a random variance?

Looks random case. PR8104 looks no impact to perf either. Let's ignore it.

**Pull request merged**
