### PR TITLE
[OPPRO-77] adding hdfs support

### PR DESCRIPTION
**Pull request by zhouyuan**
## What changes were proposed in this pull request?

This patch adds HDFS support

Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>

## How was this patch tested?

locally verified

### CODE REVIEW

**Comment by zhouyuan** [comment]
depends on: https://github.com/oap-project/velox/pull/11

**Comment by KevinyhZou** [comment]
@zhouyuan hello, I use this pr to support read dwrf file from hdfs, but encounter the error in `DwrfDatasource#InspectSchema`, which do not support hdfs.  and I have make another pr: https://github.com/oap-project/gluten/pull/389, please help to review.

**Review by FelixYBW — APPROVED** [review]

**Comment by FelixYBW** [comment]
@KevinyhZou  FYI, Velox redesigned their parquet reader and we have add it to Gluten. You can test parquet file format now.

**Comment by zhouyuan** [comment]
@KevinyhZou Thanks for working on this! let's switch to your new PR

**Comment by zhouyuan** [comment]
replaced by #389

**Pull request closed without merging**
