### PR TITLE
[VL] Fix duplicate metrics updating caused by R2C

### PR DESCRIPTION
**Pull request by rui-mo**
## What changes were proposed in this pull request?

Metrics are updated when `hasNext` becomes false. In RowToVeloxColumnarExec, when child's `hasNext` becomes false, it is called for another time, which causes duplicate metrics updating.

## How was this patch tested?

Verified on Jenkins.

### CODE REVIEW

**Review by winningsix — COMMENTED** [review]
Maybe off the topic. Do we still need [GeneralInIteratorV2](https://github.com/oap-project/gluten/blob/0edd7445781a144136a04502988bd0e1738cefa6/gluten-core/src/main/java/io/glutenproject/vectorized/GeneralInIteratorV2.java#L23)?

**Comment by rui-mo** [comment]
> Maybe off the topic. Do we still need [GeneralInIteratorV2](https://github.com/oap-project/gluten/blob/0edd7445781a144136a04502988bd0e1738cefa6/gluten-core/src/main/java/io/glutenproject/vectorized/GeneralInIteratorV2.java#L23)?

@winningsix GeneralInIteratorV2 looks not in use and can be removed.

**Comment by rui-mo** [comment]
This PR is under test from Meituan. Converting it to draft.

**Review by zhztheplayer — DISMISSED** [review]
Thanks!

After the patch, we will guarantee each `hasNext` (from both Vanilla Spark's and our code) would be called only once for one single item. Is that correct?

**Comment by rui-mo** [comment]
> After the patch, we will guarantee each `hasNext` (from both Vanilla Spark's and our code) would be called only once for one single item. Is that correct?

In R2C, `hasNext` is still called multiple times to append rows into a batch. But once `hasNext` becomes false, it should not be called anymore.

**Comment by rui-mo** [comment]
@zzcclp @liuneng1994 It seems the change to simplify `GeneralInIterator` breaks CH backend. Do you have any clue?
https://github.com/oap-project/gluten/pull/2865/files#diff-fbc4c486f291dec71f3a8a7e0e1e501b9362ec99774d38342db02f2382c47a06L32-R38

**Comment by zhztheplayer** [comment]
> @zzcclp @liuneng1994 It seems the change to simplify `GeneralInIterator` breaks CH backend. Do you have any clue? https://github.com/oap-project/gluten/pull/2865/files#diff-fbc4c486f291dec71f3a8a7e0e1e501b9362ec99774d38342db02f2382c47a06L32-R38

It's weird since the code is not used by CH backend...

**Comment by zzcclp** [comment]
> @zzcclp @liuneng1994 It seems the change to simplify `GeneralInIterator` breaks CH backend. Do you have any clue? https://github.com/oap-project/gluten/pull/2865/files#diff-fbc4c486f291dec71f3a8a7e0e1e501b9362ec99774d38342db02f2382c47a06L32-R38

CH backend has fixed this issue in https://github.com/oap-project/gluten/blob/f1a0a3e6b489b7e3290e75fab5c427201c5198bb/backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala#L135C17-L135C17

**Review by zhztheplayer — APPROVED** [review]
Thanks!

**Comment by rui-mo** [comment]
A follow up PR for hasNext and next clean up: https://github.com/oap-project/gluten/pull/3490.

**Pull request merged**
