### PR TITLE
[Gluten-986] Rename metrics name from wall nanos to totaltime to xxx.

### PR DESCRIPTION
**Pull request by Yohahaha**
Mentioned in #987

### CODE REVIEW

**Comment by zhztheplayer** [comment]
The CI failure during step `Setup docker container` might not be related. A fix proposed at #1036

**Comment by Yohahaha** [comment]
cc @FelixYBW @rui-mo

**Comment by rui-mo** [comment]
@Yohahaha Thank you. We find cpu count is also useful to us, and can be used to calculte the avg time. Could you help add that back?

**Comment by Yohahaha** [comment]
> We find cpu count is also useful to us, and can be used to calculte the avg time. Could you help add that back?

Sure, submit commit in this pr or open another pr?

How do you calculate avg time? cpu_time / cpu_count or wall_time / cpu_count?

**Comment by Yohahaha** [comment]
>> cpu_time / cpu_count or wall_time / cpu_count?

> I think wall_time is more useful to us.

Got it.

It looks like `cpu time` is not important for us currently, and from Spark's point of view it is also unimportant, shall we remove this to make Spark UI more clearly?

**Comment by rui-mo** [comment]
> It looks like `cpu time` is not important for us currently, and from Spark's point of view it is also unimportant, shall we remove this to make Spark UI more clearly? @rui-mo

@FelixYBW Binwei, how do you think so?

**Comment by FelixYBW** [comment]
> 

OK, let's remove cpu time, use wall time.

**Review by FelixYBW — APPROVED** [review]

**Pull request merged**
