### PR TITLE
[VL] Simplify ExecutionCtx + Handle JNI code pattern

### PR DESCRIPTION
**Pull request by zhztheplayer**
A clean-up to JNI code by pulling up a common pattern `ExecutionCtx` + `Handle`.

### CODE REVIEW

**Comment by zhztheplayer** [comment]
Closing, temporarily

**Comment by zhztheplayer** [comment]
cc @Yohahaha

**Comment by Yohahaha** [comment]
Thanks!

Overall goods, only one thoughts:
```java
  public static JniWrapper create(ExecutionCtx ctx) {
    return new JniWrapper(ExecutionCtxs.contextInstance);
  }

  public static JniWrapper create(ExecutionCtx ctx) {
    return new JniWrapper(ctx);
  }
```

First is good enough for user, but I prefer second one, it more like a develop API which bring more flexibility for developer who wants implement their own feature.

**Comment by zhztheplayer** [comment]
> Thanks!
> 
> Overall looks goods, only one thoughts:
> 
> ```java
>   public static JniWrapper create(ExecutionCtx ctx) {
>     return new JniWrapper(ExecutionCtxs.contextInstance);
>   }
> 
>   public static JniWrapper create(ExecutionCtx ctx) {
>     return new JniWrapper(ctx);
>   }
> ```
> 
> First is good enough for user, but I prefer second one, it more like a develop API which bring more flexibility for developer who wants implement their own feature.

I added both `create()` and `forCtx(ctx)`. Was that same with what you suggested?

**Comment by zhztheplayer** [comment]
Besides, developer can add `forCtx(ctx)` API to more JNI wrappers once needed.

**Review by rui-mo — APPROVED** [review]

**Comment by INBreezefall** [comment]
> A clean-up to JNI code by pulling up a common pattern `ExecutionCtx` + `Handle`.
Hi, I am a Gluten newbie. I have a simple question, hope you can help me. 

I can see that the ExecutionCtxAware interface is implemented in many JNI classes, but its handle method is not called in the Gluten project. Can this interface be deleted from JNI, such as ColumnarBatchJniWrapper?
What is the purpose of this interface? Will the handle method be called?

**Pull request merged**
