### PR TITLE
[OPPRO-90] Fix performance regression

### PR DESCRIPTION
**Pull request by marin-ma**
Fix rdd computed twice.

### CODE REVIEW

**Comment by marin-ma** [comment]
@zhouyuan @rui-mo Please help verify this patch.

**Comment by zhouyuan** [comment]
works for me, the redudant stage in Q1 is removed

**Comment by rui-mo** [comment]
Works for me too.

**Comment by marin-ma** [comment]
Can we merge this?

**Comment by zhouyuan** [comment]
@zzcclp PTAL

**Pull request merged**
