### PR TITLE
[GLUTEN-3559][VL] Fix GlutenCollectionExpressionSuite

### PR DESCRIPTION
**Pull request by surnaik**
## What changes were proposed in this pull request?

Fixes GlutenCollectionExpressionsSuite

(Fixes: #3559)

## How was this patch tested?

Tests ran locally

### CODE REVIEW

**Comment by surnaik** [comment]
@JkSelf @PHILO-HE @zhouyuan Please review. Thanks!

**Review by PHILO-HE — COMMENTED** [review]
Thanks for your continuous efforts!
I note the corresponding spark32 tests are not fixed. Don't we need to fix them?

**Comment by surnaik** [comment]
Can someone help me in retriggering this test
Velox backend / ubuntu2204-test (pull_request) Failing after 5m - It's failing with some download failed for xsimd. Thanks!

**Comment by PHILO-HE** [comment]
> Can someone help me in retriggering this test Velox backend / ubuntu2204-test (pull_request) Failing after 5m - It's failing with some download failed for xsimd. Thanks!

Just re-triggered this job.

**Review by PHILO-HE — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
