### PR TITLE
[DNM] test spark varbinary aggregate

### PR DESCRIPTION
**Pull request by gaoyangxiaozhu**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

(Fixes: #2169 )

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by gaoyangxiaozhu** [comment]
only fail with this test 

image

@zhouyuan  @zhejiangxiaomai could you help check if it's known issue, i didn't touch thhis part code

**Comment by zhejiangxiaomai** [comment]
I restarted the failed workflow.

**Comment by zhejiangxiaomai** [comment]
"test incorrect Parquet row group file offset" failed twice. maybe you need fix it.

**Comment by gaoyangxiaozhu** [comment]
> "test incorrect Parquet row group file offset" failed twice. maybe you need fix it.

hey @zhejiangxiaomai as synced offline with Zhouyuan, this a known issue and your team has send PR another https://github.com/oap-project/gluten/pull/2674/files to disable it since it always blocks other CH PRs check-in.

**Pull request closed without merging**
