### PR TITLE
[GLUTEN-2978][VL]fix: GlutenConfig.getConf should not be called before SQLConf initialize

### PR DESCRIPTION
**Pull request by summaryzb**
## What changes were proposed in this pull request?

https://github.com/oap-project/gluten/issues/2978

## How was this patch tested?

pass the existing test

### CODE REVIEW

**Comment by jackylee-ch** [comment]
cc @zzcclp @zhztheplayer @ulysses-you

**Review by ulysses-you — APPROVED** [review]

**Comment by winningsix** [comment]
Nice catch. How much was this PR impacting?

Nit: we can make [AGGREGATE_SIGS](https://github.com/oap-project/gluten/blob/fa3c8dd440103f234c04b955debadb786a6c16b7/gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala#L241) and [WINDOW_SIGS](https://github.com/oap-project/gluten/blob/fa3c8dd440103f234c04b955debadb786a6c16b7/gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala#L264C15-L264C26) as lazy.

**Comment by winningsix** [comment]
> https://github.com/oap-project/gluten/pull/2979#issuecomment-1700336561

Also, it looks the latest performance has some regression. The previous commit was good. Let's double confirm on result from next [PR](https://github.com/oap-project/gluten/pull/2923).

**Comment by ulysses-you** [comment]
I do not think other functions have the same issue, this pr fixes the code:
https://github.com/oap-project/gluten/blob/fa3c8dd440103f234c04b955debadb786a6c16b7/gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala#L238

**Comment by winningsix** [comment]
> I do not think other functions have the same issue, this pr fixes the code:
> 
> https://github.com/oap-project/gluten/blob/fa3c8dd440103f234c04b955debadb786a6c16b7/gluten-core/src/main/scala/io/glutenproject/expression/ExpressionMappings.scala#L238

Thanks for the explanation. Then I understood the PR title now :)

**Pull request merged**
