### PR TITLE
[VL] enable test 'as map of case class - reorder fields by name'

### PR DESCRIPTION
**Pull request by zhli1142015**
## What changes were proposed in this pull request?

UT change. Complex type support for map functions is added in https://github.com/facebookincubator/velox/pull/7560.
```
-- Project[expressions: (n1_1:MAP<INTEGER,ROW<b:INTEGER,a:VARCHAR>>, map(1,row_constructor(try_cast "n0_0" as INTEGER,"a")))] -> n1_1:MAP<INTEGER,ROW<b:INTEGER,a:VARCHAR>>
  -- ValueStream[] -> n0_0:BIGINT

```

### CODE REVIEW

**Comment by zhli1142015** [comment]
cc @rui-mo , thanks.

**Review by rui-mo — APPROVED** [review]
Thanks. We can merge it once CI passes.

**Comment by zhli1142015** [comment]
Run Gluten Clickhouse CI

**Comment by zhli1142015** [comment]
Looks CK validation failure is not related to this change. CC @baibaichen , @loneylee .
Thanks.
```
20:51:47  All tests passed.
20:51:49  [INFO] ------------------------------------------------------------------------
20:51:49  [INFO] Reactor Summary for Gluten Parent Pom 1.1.0-SNAPSHOT:
20:51:49  [INFO] 
20:51:49  [INFO] Gluten Parent Pom .................................. SUCCESS [  1.182 s]
20:51:49  [INFO] Gluten UI .......................................... SUCCESS [ 25.657 s]
20:51:49  [INFO] Gluten Shims ....................................... SUCCESS [  2.456 s]
20:51:49  [INFO] Gluten Shims Common ................................ SUCCESS [ 19.941 s]
20:51:49  [INFO] Gluten Shims for Spark 3.3 ......................... SUCCESS [ 23.826 s]
20:51:49  [INFO] Gluten Core ........................................ SUCCESS [01:29 min]
20:51:49  [INFO] Gluten Backends ClickHouse ......................... SUCCESS [56:30 min]
20:51:49  [INFO] Gluten Celeborn .................................... SUCCESS [  0.614 s]
20:51:49  [INFO] Gluten Celeborn Common ............................. SUCCESS [  6.327 s]
20:51:49  [INFO] Gluten Celeborn Clickhouse ......................... SUCCESS [01:04 min]
20:51:49  [INFO] Gluten Celeborn Package ............................ SUCCESS [  0.453 s]
20:51:49  [INFO] Gluten Package ..................................... SUCCESS [  5.385 s]
20:51:49  [INFO] Gluten Substrait Spark ............................. SUCCESS [ 32.892 s]
20:51:49  [INFO] Gluten Unit Test ................................... SUCCESS [  0.312 s]
20:51:49  [INFO] Gluten Unit Test Common ............................ SUCCESS [ 13.022 s]
20:51:49  [INFO] Gluten Unit Test Spark33 ........................... SUCCESS [40:47 min]
20:51:49  [INFO] ------------------------------------------------------------------------
20:51:49  [INFO] BUILD SUCCESS
20:51:49  [INFO] ------------------------------------------------------------------------
20:51:49  [INFO] Total time:  01:42 h
20:51:49  [INFO] Finished at: 2023-12-13T12:51:49Z
20:51:49  [INFO] ------------------------------------------------------------------------
[Pipeline] echo
20:51:49  enter finally
[Pipeline] sh
20:51:50  + ls -l
20:51:50  total 138692
20:51:50  -rw-r--r--  1 root root      4147 Dec 13 10:33 CONTRIBUTING.md
20:51:50  -rw-r--r--  1 root root     94051 Dec 13 10:33 LICENSE
20:51:50  -rw-r--r--  1 root root     10761 Dec 13 10:33 README.md
20:51:50  -rw-r--r--  1 root root       431 Dec 13 10:33 SECURITY.md
20:51:50  -rw-r--r--  1 root root    325088 Dec 13 10:33 TPP.txt
20:51:50  drwxr-xr-x 15 root root       247 Dec 13 10:33 apache-celeborn-0.3.0-incubating-bin
20:51:50  -rw-r--r--  1 root root 141533645 Dec 13 10:33 apache-celeborn-0.3.0-incubating-bin.tgz
20:51:50  drwxr-xr-x  9 root root       255 Dec 13 11:59 backends-clickhouse
20:51:50  drwxr-xr-x  4 root root        49 Dec 13 10:33 backends-velox
20:51:50  drwxr-xr-x  5 root root       124 Dec 13 10:33 cpp
20:51:50  drwxr-xr-x  3 root root        95 Dec 13 10:33 cpp-ch
20:51:50  drwxr-xr-x  3 root root      4096 Dec 13 10:33 dev
20:51:50  drwxr-xr-x  6 root root       282 Dec 13 10:33 docs
20:51:50  drwxr-xr-x  4 root root        49 Dec 13 10:33 ep
20:51:50  drwxr-xr-x  6 root root        81 Dec 13 10:33 gluten-celeborn
20:51:50  drwxr-xr-x  5 root root        98 Dec 13 11:12 gluten-core
20:51:50  drwxr-xr-x  3 root root        32 Dec 13 10:33 gluten-data
20:51:50  drwxr-xr-x  3 root root        32 Dec 13 10:33 gluten-delta
20:51:50  drwxr-xr-x  3 root root        32 Dec 13 10:33 gluten-iceberg
20:51:50  drwxr-xr-x  4 root root        46 Dec 13 11:09 gluten-ui
20:51:50  drwxr-xr-x  6 root root        80 Dec 13 10:33 gluten-ut
20:51:50  -rw-r--r--  1 root root      1441 Dec 13 10:33 mkdocs.yml
20:51:50  drwxr-xr-x  2 root root        21 Dec 13 10:33 package
20:51:50  -rw-r--r--  1 root root     28076 Dec 13 10:33 pom.xml
20:51:50  drwxr-xr-x  6 root root        80 Dec 13 10:33 shims
20:51:50  drwxr-xr-x  3 root root        29 Dec 13 10:33 substrait
20:51:50  drwxr-xr-x  5 root root        56 Dec 13 10:33 tools
[Pipeline] sh
20:51:51  + pwd
20:51:51  /home/jenkins/agent/workspace/gluten/gluten-ci/gluten2
[Pipeline] sh
20:51:51  + mkdir -p /maven-log/5272/3.3.1/backends-clickhouse
[Pipeline] sh
20:51:52  + mkdir -p /maven-log/5272/3.3.1/spark33
[Pipeline] sh
20:51:53  + pwd
20:51:53  + cp -r /home/jenkins/agent/workspace/gluten/gluten-ci/gluten2/backends-clickhouse /maven-log/5272/3.3.1/backends-clickhouse
[Pipeline] sh
20:52:25  + pwd
20:52:25  + cp -r /home/jenkins/agent/workspace/gluten/gluten-ci/gluten2/gluten-ut/spark33 /maven-log/5272/3.3.1/spark33
[Pipeline] sh
20:52:34  + ls -l /maven-log/5272/3.3.1/backends-clickhouse
20:52:34  total 4
20:52:34  drwxr-xr-x 9 1000 1000 6144 Dec 13 12:52 backends-clickhouse
[Pipeline] sh
20:52:35  + ls -l /maven-log/5272/3.3.1/spark33
20:52:35  total 4
20:52:35  drwxr-xr-x 5 1000 1000 6144 Dec 13 12:52 spark33
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] container
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Setting status of 39ad0fb04089de90d737cada840941d3b7ffe5a7 to FAILURE with url https://opencicd.kyligence.com/job/gluten/job/gluten-ci/5272/ and message: 'Something went really wrong. Investigate!
 '
Using context: Gluten ClickHouse CI
Finished: FAILURE
```

**Pull request merged**
