### PR TITLE
Revert "[CH] Enable tpcds more tests"

### PR DESCRIPTION
**Pull request by zzcclp**
This PR will lead to CI failed, revert first.
Reverts oap-project/gluten#1624

### CODE REVIEW

**Comment by zzcclp** [comment]
Run Gluten Clickhouse CI

**Comment by lwz9103** [comment]
Run Gluten Clickhouse CI

**Comment by zzcclp** [comment]
Run Gluten Clickhouse CI

**Comment by zzcclp** [comment]
Run Gluten Clickhouse CI

**Pull request merged**
