### PR TITLE
[CI] Skip CI jobs on backends whose code were unchanged

### PR DESCRIPTION
**Pull request by zhztheplayer**

### CODE REVIEW

**Comment by FelixYBW** [comment]
@zhztheplayer should we merge?

**Comment by zhztheplayer** [comment]
The PR got staled for a while and possibly needs some discussion to re-validate the idea, I think.

**Comment by zuochunwei** [comment]
good idea

**Comment by FelixYBW** [comment]
At least if we modify readme, we shouldn't trigger CI

**Comment by zhztheplayer** [comment]
@FelixYBW @zuochunwei

**Review by FelixYBW — APPROVED** [review]

**Pull request merged**
