### PR TITLE
[Gluten-276] Fix whole stage transformer suite

### PR DESCRIPTION
**Pull request by rui-mo**
## What changes were proposed in this pull request?

Fixed whole stage transformer suite.

Fixed https://github.com/oap-project/gluten/issues/276.

## How was this patch tested?

Verified on CI.

### CODE REVIEW

**Comment by marin-ma** [comment]
Is it necessary to create another test suite? Maybe we can just move the datasource v1/v2 config into `withSQLConf` and only maintain 1 test suite.

**Comment by rui-mo** [comment]
> Is it necessary to create another test suite? Maybe we can just move the datasource v1/v2 config into `withSQLConf` and only maintain 1 test suite.

Hi, I tried that but found the setting for `"spark.sql.sources.useV1SourceList"` did not take effect with `withSQLConf`, so I separated them into two suites. It would be nice if you know how to make it take effect.

**Comment by marin-ma** [comment]
> > Is it necessary to create another test suite? Maybe we can just move the datasource v1/v2 config into `withSQLConf` and only maintain 1 test suite.
> 
> Hi, I tried that but found the setting for `"spark.sql.sources.useV1SourceList"` did not take effect with `withSQLConf`, so I separated them into two suites. It would be nice if you know how to make it take effect.

Ok. This is because we call `CreateTPCHTables()` in `beforeAll()`, which lead to the tables created beforehand don't respect the settings in `withSQLConf`. I see Spark's test suites create tables inside each tests and use function `withTable` to drop those tables after each test finishes. Do you think we should follow their way?
Here's an exmaple: https://github.com/apache/spark/blob/66b1f79b72855af35351ff995492f2c13872dac5/sql/core/src/test/scala/org/apache/spark/sql/sources/InsertSuite.scala#L626-L661

**Comment by rui-mo** [comment]
> Ok. This is because we call `CreateTPCHTables()` in `beforeAll()`, which lead to the tables created beforehand don't respect the settings in `withSQLConf`. I see Spark's test suites will create tables inside each tests and use function `withTable` to drop those tables after each test finishes. Do you think we should follow their way? Here's an exmaple: https://github.com/apache/spark/blob/66b1f79b72855af35351ff995492f2c13872dac5/sql/core/src/test/scala/org/apache/spark/sql/sources/InsertSuite.scala#L626-L661

Got it, thanks. Will have a try.

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
