### PR TITLE
[GLUTEN-3559][VL] Fix TPCDS Plan Suite

### PR DESCRIPTION
**Pull request by ayushi-agarwal**
## What changes were proposed in this pull request?

As part of this change https://github.com/apache/spark/pull/38151 in spark 3.4 a new config was introduced spark.sql.readSideCharPadding which adds extra expression in project list expression. Due to this Suite fails with this error:

Unable to convert the expression staticinvoke(class org.apache.spark.sql.catalyst.util.CharVarcharCodegenUtils, StringType, readSidePadding, sm_type#106, 30, true, false, true)
java.lang.UnsupportedOperationException: Unable to convert the expression staticinvoke(class org.apache.spark.sql.catalyst.util.CharVarcharCodegenUtils, StringType, readSidePadding, sm_type#106, 30, true, false, true)
at io.substrait.spark.expression.ToSubstraitExpression.default(ToSubstraitExpression.scala:46)
at io.substrait.spark.expression.ToSubstraitExpression.translateUp(ToSubstraitExpression.scala:145)
at io.substrait.spark.expression.ToSubstraitExpression.translateUp(ToSubstraitExpression.scala:136)
at io.substrait.spark.expression.ToSubstraitExpression.convert(ToSubstraitExpression.scala:57)
at io.substrait.spark.expression.ToSubstraitExpression.apply(ToSubstraitExpression.scala:50)
at io.substrait.spark.logical.ToSubstraitRel.toExpression(ToSubstraitRel.scala:260)
at io.substrait.spark.logical.ToSubstraitRel.$anonfun$visitProject$1(ToSubstraitRel.scala:230)
at scala.collection.immutable.List.map(List.scala:297)
at io.substrait.spark.logical.ToSubstraitRel.visitProject(ToSubstraitRel.scala:230)
at io.substrait.spark.logical.ToSubstraitRel.visitProject(ToSubstraitRel.scala:45)
at org.apache.spark.sql.catalyst.plans.logical.LogicalPlanVisitor.visit(LogicalPlanVisitor.scala:38)
at org.apache.spark.sql.catalyst.plans.logical.LogicalPlanVisitor.visit$(LogicalPlanVisitor.scala:25)

To fix the suite I have disabled this config in suite.

(Fixes: \#3559)

## How was this patch tested?

Ran in local

### CODE REVIEW

**Comment by ayushi-agarwal** [comment]
@JkSelf I see only 5 checks are starting for this, gluten-clickhouse CI is not getting triggered.

**Comment by JkSelf** [comment]
@ayushi-agarwal We disable the tests related with `substrait-java`. Can you help to enable the tests [here](https://github.com/oap-project/gluten/blob/main/.github/workflows/velox_be.yml#L38)?

**Comment by ayushi-agarwal** [comment]
> @ayushi-agarwal We disable the tests related with `substrait-java`. Can you help to enable the tests [here](https://github.com/oap-project/gluten/blob/main/.github/workflows/velox_be.yml#L38)?

Thank @JkSelf for pointing this out. I have enabled it and will see if all the checks pass.

**Review by JkSelf — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
