### PR TITLE
[VL] Revert "Velox splitter supports dictionary encoding (#1069)"

### PR DESCRIPTION
**Pull request by PHILO-HE**
This reverts commit 9be2f04fd4c35f90fd0e46ed2be9d8957bf973c8.

### CODE REVIEW

**Comment by zuochunwei** [comment]
I Will fix this problem in PR #1117

**Comment by PHILO-HE** [comment]
This is the issue we met in tpcds q38.
```
Stack: [0x00007fa6992d3000,0x00007fa6993d4000],  sp=0x00007fa6993d1e80,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libvelox.so+0x13e59cb]  gluten::VeloxSplitter::CalculatePartitionBufferSize(facebook::velox::RowVector const&)+0x11b   Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  io.glutenproject.vectorized.ShuffleSplitterJniWrapper.split(JIJ)J+0
j  org.apache.spark.shuffle.GlutenColumnarShuffleWriter.internalWrite(Lscala/collection/Iterator;)V+283
j  org.apache.spark.shuffle.GlutenColumnarShuffleWriter.write(Lscala/collection/Iterator;)V+2

```

**Comment by rui-mo** [comment]
There are also some failed unit tests on CI. If this PR can resolve these issues, how about merging this one before the formal fix?

**Review by zhztheplayer — APPROVED** [review]
@zuochunwei Let's merge this and include #1069's change into #1117 too

**Comment by rui-mo** [comment]
@zuochunwei One failed test case:

```
count.sql
Expected "[2]    1", but got "[3]    1" Result did not match for query #8
SELECT count(DISTINCT a), count(DISTINCT 2,3) FROM testData
ScalaTestFailureLocation: org.apache.spark.sql.GlutenSQLQueryTestSuite at (GlutenSQLQueryTestSuite.scala:727)
org.scalatest.exceptions.TestFailedException: count.sql
Expected "[2]    1", but got "[3]    1" Result did not match for query #8
SELECT count(DISTINCT a), count(DISTINCT 2,3) FROM testData
```

**Comment by zuochunwei** [comment]
wait me hours

**Comment by zuochunwei** [comment]
> split

OK

**Comment by zuochunwei** [comment]
> @zuochunwei Let's merge this and include #1069's change into #1117 too

OK

**Pull request merged**
