### PR TITLE
[OPPRO-243] Support Spark33 with shimlayer

### PR DESCRIPTION
**Pull request by jinchengchenghh**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by rui-mo** [comment]
Verified TPC-DS on Spark3.2 locally.

**Comment by zzcclp** [comment]
There are some issues about our CI machine.
and I verified locally with ClickHouse Backend + Spark 3.2.2. But there are some issues with Spark 3.3.

Merge first and I will raise anorther PR to fix.

**Review by zzcclp — APPROVED** [review]
LGTM

**Comment by jinchengchenghh** [comment]
Thanks!

**Pull request merged**
