### PR TITLE
[VL] Daily Update Velox Version (2024_03_01)

### PR DESCRIPTION
**Pull request by GlutenPerfBot**
Rebase velox 2024_03_01 
Velox changes:
 https://github.com/facebookincubator/velox/commits/main/?since=2024-03-01&until=2024-03-01

27450699d by Pedro Eugenio Rocha Pedreira, parse_datetime() should allow UCT|UCT|GMT|GMT0 as 'Z'
93b2544ab by Jimmy Lu, Safer JSON cast from floating point to integer across platforms
0d494361d by hitarth, Avoid unnecessary looping through parquet rowgroups (#8741)
b557ab6bb by Masha Basmanova, Add support for date +/- interval year month Presto functions
ff0e098da by Jialiang Tan, Minor refactor in SharedArbitrator (#8892)
aae8934d2 by Masha Basmanova, Add from_iso8601_date Presto function
b2de8a6bd by Krishna Pai, Move folly init and gtest init before registration of functions. (#8882)
fd8e4ff1a by Sergey Pershin, Update documentation for 'split_to_map'.
c7c9e965b by Masha Basmanova, Fix CUBE aggregation over distinct inputs when input is empty
9dc4ccf25 by Masha Basmanova, Fix CUBE aggregation over sorted inputs when input is empty
85a56c874 by Sergey Pershin, Clear and fix a bug in Task::noMoreSplits().
0f25c1f7b by Sergey Pershin, Allow entry delimiter to be last in the input of SplitToMap().
dbb4f8f33 by Krishna Pai, Add support for returning results as Velox Vectors to ReferenceQueryRunner (#8880)
a8f4bfc1f by Masha Basmanova, Add support for UNKNOWN input to checksum Presto function
3fc707da1 by Krishna Pai, Fix broken Github Actions Macos13 build (#8908)
1070e365c by Bikramjeet Vig, Use a seperate memory pool for input vectors in ExpressionRunner

### CODE REVIEW

**Comment by ulysses-you** [comment]
Is it possible to let bot put the commit history at pr description ? cc @zhouyuan @PHILO-HE

**Comment by zhouyuan** [comment]
> Is it possible to let bot put the commit history at pr description ? cc @zhouyuan @PHILO-HE

Yes, It's doable and this is requested by several Gluten developers. Will add this in the bot code.

Thanks,
-yuan

**Review by PHILO-HE — APPROVED** [review]

**Comment by PHILO-HE** [comment]
> Is it possible to let bot put the commit history at pr description ? cc @zhouyuan @PHILO-HE

@ulysses-you, thanks for your suggestion! I just added some code in internal script to discover new commits for each rebase. Now the new commits can be put into PR's description by bot. See https://github.com/apache/incubator-gluten/pull/4908. cc @zhouyuan

**Pull request merged**
