### PR TITLE
[GLUTEN-CORE] [VL] Avoid duplicate window column name

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

Some function will have same window column name, but their result are different, such as first(expr) and first(expr, true).

### CODE REVIEW

**Comment by Yohahaha** [comment]
Hi @JkSelf @rui-mo 

Could you help take a look?

**Review by rui-mo — APPROVED** [review]

**Review by JkSelf — APPROVED** [review]
LGTM

**Comment by Yohahaha** [comment]
@zhouyuan @zhejiangxiaomai @ccat3z 

```
[100%] Built target columnar_to_row_benchmark
free(): invalid pointer
[100%] Built target generic_benchmark
free(): invalid pointer
CMake Error at /opt/gluten/dev/vcpkg/.vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/share/cmake-3.25/Modules/GoogleTestAddTests.cmake:112 (message):
  Error running test executable.

    Path: '/opt/gluten/cpp/build/velox/tests/velox_shuffle_writer_test'
    Result: Subprocess aborted
    Output:
      

Call Stack (most recent call first):
  /opt/gluten/dev/vcpkg/.vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/share/cmake-3.25/Modules/GoogleTestAddTests.cmake:225 (gtest_discover_tests_impl)


make[2]: *** [velox/tests/CMakeFiles/velox_shuffle_writer_test.dir/build.make:235: velox/tests/velox_shuffle_writer_test] Error 1
make[2]: *** Deleting file 'velox/tests/velox_shuffle_writer_test'
make[1]: *** [CMakeFiles/Makefile2:383: velox/tests/CMakeFiles/velox_shuffle_writer_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMake Error at /opt/gluten/dev/vcpkg/.vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/share/cmake-3.25/Modules/GoogleTestAddTests.cmake:112 (message):
  Error running test executable.

    Path: '/opt/gluten/cpp/build/velox/tests/orc_test'
    Result: Subprocess aborted
    Output:
      

Call Stack (most recent call first):
  /opt/gluten/dev/vcpkg/.vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/share/cmake-3.25/Modules/GoogleTestAddTests.cmake:225 (gtest_discover_tests_impl)


make[2]: *** [velox/tests/CMakeFiles/orc_test.dir/build.make:235: velox/tests/orc_test] Error 1
make[2]: *** Deleting file 'velox/tests/orc_test'
make[1]: *** [CMakeFiles/Makefile2:437: velox/tests/CMakeFiles/orc_test.dir/all] Error 2
[100%] Built target query_benchmark
free(): invalid pointer
CMake Error at /opt/gluten/dev/vcpkg/.vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/share/cmake-3.25/Modules/GoogleTestAddTests.cmake:112 (message):
  Error running test executable.

    Path: '/opt/gluten/cpp/build/velox/tests/velox_converter'
    Result: Subprocess aborted
    Output:
      

Call Stack (most recent call first):
  /opt/gluten/dev/vcpkg/.vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/share/cmake-3.25/Modules/GoogleTestAddTests.cmake:225 (gtest_discover_tests_impl)


make[2]: *** [velox/tests/CMakeFiles/velox_converter.dir/build.make:283: velox/tests/velox_converter] Error 1
make[2]: *** Deleting file 'velox/tests/velox_converter'
make[1]: *** [CMakeFiles/Makefile2:410: velox/tests/CMakeFiles/velox_converter.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by zhouyuan** [comment]
Hi @Yohahaha 

can you please do a rebase? The issue should due to a dependency commit of #1384 

-yuan

**Review by rui-mo — APPROVED** [review]

**Pull request merged**
