### PR TITLE
[CORE] Minor adjustment to columnar rule list, and move all columnar sub-rules to one source folder

### PR DESCRIPTION
**Pull request by zhztheplayer**
1. Add an extra `InsertTransitions` rule right after `TransformPreOverrides`. To verify whether we could consolidate the plan-implementing phase and C2R/R2C transition-adding phase together. (in future patch)
2. Move all sub-rules used by `ColumnarRuleOverrides` to source package/folder `io.glutenproject.extension.columnar`.

### CODE REVIEW

**Comment by zhztheplayer** [comment]
Run Gluten Clickhouse CI

**Comment by zhztheplayer** [comment]
Run Gluten Clickhouse CI

**Comment by lwz9103** [comment]
Run Gluten Clickhouse CI

**Review by JkSelf — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
