### PR TITLE
[GLUTEN-4416][VL][CI] Enable AQE for TPC-H test in some CI jobs

### LINKED ISSUE #4416: [IT] Enable Spark AQE when running Gluten TPC-H IT
### Description

As title

### PR DESCRIPTION
**Pull request by zwangsheng**
## What changes were proposed in this pull request?

Close #4416

Enable Spark AQE when running Gluten TPC-H IT

## How was this patch tested?

Exist CI

### CODE REVIEW

**Comment by zwangsheng** [comment]
PTAL @PHILO-HE, BTW, is there any additional consideration in disabled AQE for TPC-H IT?

**Comment by PHILO-HE** [comment]
> PTAL @PHILO-HE, BTW, is there any additional consideration in disabled AQE for TPC-H IT?

Thanks for your fix! Not sure why we disabled it before. Maybe, we can only keep it disabled for `static-build-centos7-test` CI job to cover no-AQE test.

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Comment by ulysses-you** [comment]
the failed tests are irrelevant

**Pull request merged**
