### PR TITLE
No need to build Spark prior to Velox backend's CI

### PR DESCRIPTION
**Pull request by zhztheplayer**

### CODE REVIEW

**Comment by rui-mo** [comment]
> It interesting that some suites other than SQLQuerySuites (e.g. GlutenBroadcastJoinSuite) get failed within this change. @rui-mo It would be helpful if you have some comments here. My intuition is that setting SPARK_HOME may make the suites find Spark client from disk instead of using embedded Spark context

For GlutenSQLQueryTestSuite, only a spark resource directory without compilation is enough. But I remember @JkSelf have added the compilation of Spark to fix one test suite. Maybe she could help provide more details.

**Comment by JkSelf** [comment]
When running `GlutenBroadcastJoinSuite `, spark need to detect the scala version by checking whether the directory of `{spark.test.home}/assembly/target/scala-2.12`  or `{spark.test.home}/assembly/target/scala-2.13` existing. If we set the spark source code without compiling,  it will throw exceptions because there is no detected scala version.

**Comment by zhztheplayer** [comment]
That's helpful information. Thanks @JkSelf and @rui-mo and I'll close this until it turns to be feasible.

**Comment by jinchengchenghh** [comment]
Can we move GlutenBroadcastJoinSuite failed tests to black list or run the complete test daily, build spark costs 43min which is too long.

**Comment by JkSelf** [comment]
Or can we compile the spark directory on the test machine before running CI?

**Comment by zhztheplayer** [comment]
> Or can we compile the spark directory on the test machine before running CI?

It's a good idea but may more or less break the isolation of each UT instance. I think we can just pre-build spark inside the docker image `gluten-buildenv`.

**Pull request closed without merging**
