### PR TITLE
[GLUTEN-2182][VL][FOLLOWUP] Add BUILD_EXAMPLES flag

### PR DESCRIPTION
**Pull request by ulysses-you**
## What changes were proposed in this pull request?

This pr is a followup of https://github.com/oap-project/gluten/pull/2427 to avoid compiling example code.

(Fixes: \#2182)

## How was this patch tested?

test locally:

```shell
./dev/buildbundle-veloxbe.sh --skip_build_ep=ON --enable_hdfs=ON --build_type=Debug --build_examples=ON
./dev/buildbundle-veloxbe.sh --skip_build_ep=ON --enable_hdfs=ON --build_type=Debug --build_examples=OFF
```

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @marin-ma

**Comment by marin-ma** [comment]
Please pass "--build_examples=ON" to gluten CI.

**Comment by ulysses-you** [comment]
@marin-ma thank you for the reminder, addressed

**Review by marin-ma — APPROVED** [review]

**Comment by marin-ma** [comment]
LGTM. Thanks.

**Pull request merged**
