### PR TITLE
[CORE] Add junitxml path of scalatest-maven-plugin for backends-velox, spark33 and spark34

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

See https://www.scalatest.org/user_guide/using_the_scalatest_maven_plugin, it helps CI tools collect UT results.

### CODE REVIEW

**Comment by Yohahaha** [comment]
@PHILO-HE please help review this minor patch, thank you!

**Comment by PHILO-HE** [comment]
Thanks for your work!
With this patch, some xml files will be generated under the configured path on CI server, right? Can we cover Spark32 tests?

**Comment by Yohahaha** [comment]
> Thanks for your work! With this patch, some xml files will be generated under the configured path on CI server, right? Can we cover Spark32 tests?

Spark32 already has such config, https://github.com/oap-project/gluten/blob/bc4c1ac753c4ca1822f6fcb23eeadee448912ac9/gluten-ut/spark32/pom.xml#L155

**Review by zhztheplayer — COMMENTED** [review]
Thanks. We already set the option in root pom:

https://github.com/oap-project/gluten/blob/bc4c1ac753c4ca1822f6fcb23eeadee448912ac9/pom.xml#L567

Would you figure out whether it's working or not?

**Comment by Yohahaha** [comment]
> Thanks. We already set the option in root pom:
> 
> https://github.com/oap-project/gluten/blob/bc4c1ac753c4ca1822f6fcb23eeadee448912ac9/pom.xml#L567
> 
> Would you figure out whether it's working or not?

I think not, you can check your CI machine's `backends-velox/target/scalatest-reports` before this patch and this patch.

**Comment by zhztheplayer** [comment]
Did you find out why it's not working? May it relate to relative/abstract path or something?

**Comment by Yohahaha** [comment]
> Did you find out why it's not working? May it relate to relative/abstract path or something?

nope, `-DtestFailureIgnore=true` also not work.

**Comment by Yohahaha** [comment]
can we merge?

**Review by PHILO-HE — APPROVED** [review]
Looks good! Thanks!
If there is any other comment, let's fix it in follow-up PR.

**Pull request merged**
