### PR TITLE
[GLUTEN-1277][CORE] Fix spark33 TPCDS Q66 decimal * int expression

### PR DESCRIPTION
**Pull request by jinchengchenghh**

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by jinchengchenghh** [comment]
I will move the logic to only take effect in velox backend, but I'm not sure if CH need this fix. @taiyang-li 
CH backend will throw exception with this PR:
https://github.com/oap-project/gluten/actions/runs/4624926840/jobs/8180220227?pr=1278
```
- TPCH Q7 *** FAILED ***
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 199.0 failed 1 times, most recent failure: Lost task 0.0 in stage 199.0 (TID 374) (gluten-ci.c.kyligence-212803.internal executor driver): org.apache.spark.SparkException: Managed memory leak detected; size = 1703999 bytes, task 0.0 in stage 199.0 (TID 374)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:516)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1500)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2454)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2403)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2402)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2402)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1160)
  at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1160)
  at scala.Option.foreach(Option.scala:407)
  ...
  Cause: org.apache.spark.SparkException: Managed memory leak detected; size = 1703999 bytes, task 0.0 in stage 199.0 (TID 374)
  at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:516)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1500)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:750)
```

**Comment by taiyang-li** [comment]
@jinchengchenghh I agree with blocking those changes for CH backend currently. It is not late to fix it when CH met similar issues.

**Review by zhouyuan — APPROVED** [review]
👍  works for me

**Pull request merged**
