### PR TITLE
[Gluten-219] add ch ut job

### PR DESCRIPTION
**Pull request by liuneng1994**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by weiting-chen** [comment]
@liuneng1994 @zzcclp 
There is a core dump after run pass all queries.
https://github.com/oap-project/gluten/runs/7188393461?check_suite_focus=true#step:11:664

**Comment by zzcclp** [comment]
> @liuneng1994 @zzcclp There is a core dump after run pass all queries. https://github.com/oap-project/gluten/runs/7188393461?check_suite_focus=true#step:11:664

yeah, there is an known issue, we will fix this later, but it doesn't affect the UT .

**Review by weiting-chen — APPROVED** [review]
It looks good to me.

**Comment by rui-mo** [comment]
Verified on Jenkins. LGTM.

**Comment by zhouyuan** [comment]
@liuneng1994 @zzcclp Thanks for adding this check!

**Pull request merged**
