### PR TITLE
[GLUTEN-1205][VL][FOLLOWUP] Refactor shuffle partition writer

### PR DESCRIPTION
**Pull request by kerwin-zk**
## What changes were proposed in this pull request?
1. Change SplitOptions to ShuffleWriterOptions.
2. Remove num_partitions from PartitionWriter's constructor, and add NumPartitions() function in ShuffleWriter.
3. Add parent class RssClient for CelebornClient to support clients of multiple RSS engines.
4. Remove celeborn_client in ShuffleWriterOptions, and add PartitionWriterCreator to receive instantiated RssClient.

### CODE REVIEW

**Comment by kerwin-zk** [comment]
@zhztheplayer cc

**Comment by zhztheplayer** [comment]
I pushed some changes to the PR.

Would you be good with them? @kerwin-zk

**Comment by kerwin-zk** [comment]
> I pushed some changes to the PR.
> 
> Would you be good with them? @kerwin-zk

@zhztheplayer I think it's ok.

**Review by zhztheplayer — DISMISSED** [review]
Thanks!

**Comment by kerwin-zk** [comment]
Already rebased. @zhztheplayer

**Comment by FelixYBW** [comment]
Hold a merge for while, I will take a look closely soon

**Pull request merged**
