### PR TITLE
[CH-269]support more struct/array/map functions

### PR DESCRIPTION
**Pull request by lgbo-ustc**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
unit tests

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Review by zzcclp — APPROVED** [review]
LGTM

**Comment by zzcclp** [comment]
please add some relative test cases and rebase.

**Review by JkSelf — COMMENTED** [review]
Can you add related unit tests?

**Comment by lgbo-ustc** [comment]
> Can you add related unit tests?

test is in `GlutenDataFrameComplexTypeSuite`

**Comment by JkSelf** [comment]
@lgbo-ustc 
Thanks for your information. Velox already enable this suite [here](https://github.com/oap-project/gluten/blob/680570e5a25161478be8fe6651eaf6d2f3f339b9/gluten-ut/spark32/src/test/scala/io/glutenproject/utils/velox/VeloxTestSettings.scala#L161).

**Review by JkSelf — APPROVED** [review]
LGTM.

**Comment by zzcclp** [comment]
Please rebase and rerun the ut, there are many missing commits.

**Pull request merged**
