### PR TITLE
[VL] Daily Update Velox Version (2024_03_06)

### PR DESCRIPTION
**Pull request by GlutenPerfBot**
Rebase velox 2024_03_06 
 
3b6ce7129 by duanmeng, Add query abort injection test utility (#8948)
021d7147a by zhli1142015, Add configuration 'spark.partition_id' and refactor rand(seed) function (#8934)
b8b48d5f4 by Yang Zhang, Add unhex Spark function (#8289)
07a151827 by xiaoxmeng, Move SharedArbitrator back to memory namespace for Alpha dependency (#8954)
3b8aa1987 by Jialiang Tan, Fix typo in reclaim section guard (#8968)
fe4547388 by Wei He, Fix incorrect result of arbitrary() with spilling (#8809)
d3d9fce6d by xiaoxmeng, Fix flaky tests in hash join tests (#8967)
66d8bf226 by Orri Erling, Reuse Serializer (#8849)
fbd657d0c by xumingming, Implement timestamp +/- IntervalYearMonth (#8848)
8283be385 by Daniel Munoz, ResultOrActions (#8841)
a3e67175a by Pedro Pedreira, Remove obsolete setup-velox-torcharrow.sh (#8961)
dec9bb991 by duanmeng, Remove testWithTableScan flag in testAggregations (#8958)
b9afa14f1 by aditi-pandit, Allow HiveSplit info columns like '$file_size' and '$file_modified_time' to be queried in SQL (#8800)
1027b32b7 by Jimmy Lu, Fix crash in DWRF selective flat map reader fast path with all inlined string keys (#8952)
f82112aea by Pramod, Add decimal support for floor function (#8803)
32b9cadf5 by xiaodai1002, Fix crash when SimdComparison calls SIMD instructions (#8820)
93003290d by Yang Zhang, Propagate HiveConfig::kLoadQuantum (#8947)
2e1721f82 by Jialiang Tan, Followup: Deprecate spill pct completely (#8937)
eba938b61 by xiaoxmeng, Hash join changes for probe side spilling support (#8926)

### CODE REVIEW

**Comment by PHILO-HE** [comment]
```
- unhex *** FAILED ***
2024-03-06T09:10:25.2605935Z [31m  Incorrect evaluation: unhex(123, false), actual: [B@5c786cca, expected: [B@2e9f94fb

- CONVERSION_INVALID_INPUT: to_binary conversion function hex *** FAILED ***
2024-03-06T09:54:29.2127709Z [31m  Expected exception org.apache.spark.SparkException to be thrown, but no exception was thrown
```

**Comment by zhouyuan** [comment]
related: https://github.com/facebookincubator/velox/pull/8289

**Comment by Yohahaha** [comment]
seems unhex add a new behavior failOnError.

**Comment by Yohahaha** [comment]
https://github.com/apache/spark/pull/38416 Spark fix unhex when input has odd length...

**Comment by PHILO-HE** [comment]
> - CONVERSION_INVALID_INPUT: to_binary conversion function hex *** FAILED ***

@Yohahaha, I note Spark `to_binary(input, hex)`  is converted to `unhex(input, failOnError = true)`. We don't consider `failOnError=true` in Gluten, since it is generally related to `ANSI=ON` (Gluten only supports OFF).  Not sure why [ToBinary](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/stringExpressions.scala#L2870) doesn't have a `failOnError` arg (should be false by default), which is expected to be passed to unhex function.

**Comment by PHILO-HE** [comment]
> [apache/spark#38416](https://github.com/apache/spark/pull/38416) Spark fix unhex when input has odd length...

Let's align with Spark's fix. Thanks!

**Comment by Yohahaha** [comment]
> > [apache/spark#38416](https://github.com/apache/spark/pull/38416) Spark fix unhex when input has odd length...
> 
> @Yohahaha Looks the fix was introduced in Spark-3.3.2 (Gluten test is 3.3.1) & Spark-3.4+. Let's align with Spark's fix. Thanks!

maybe we could use branch 3.3 for CI, instead of tag 3.3.1?

**Comment by PHILO-HE** [comment]
> > > [apache/spark#38416](https://github.com/apache/spark/pull/38416) Spark fix unhex when input has odd length...
> > 
> > 
> > @Yohahaha Looks the fix was introduced in Spark-3.3.2 (Gluten test is 3.3.1) & Spark-3.4+. Let's align with Spark's fix. Thanks!
> 
> maybe we could use branch 3.3 for CI, instead of tag 3.3.1?

There should have some compatibility issues between Spark 3.3.1 and 3.3 branch. I think we cannot user other Spark 3.3 version for CI unless we upgrade Gluten's 3.3 support.

**Comment by PHILO-HE** [comment]
Let's temporarily ignore two tests related to "unhex". We can re-enable them after the fix velox. cc @Yohahaha.

**Review by zhouyuan — APPROVED** [review]

**Comment by ulysses-you** [comment]
it seems this rebase affect performance , cc @zhouyuan @PHILO-HE

**Comment by PHILO-HE** [comment]
> it seems this rebase affect performance , cc @zhouyuan @PHILO-HE

Maybe, the internal test environment is not stable. I found the regression disappears in the latest commits. Thanks!

**Comment by ulysses-you** [comment]
Thank you @PHILO-HE for taking a look. I'm afraid the regression disappears in the latest commits is due to https://github.com/apache/incubator-gluten/pull/4783. That pr improves the performance before merging, and go away with post performance CI...

**Comment by PHILO-HE** [comment]
@ulysses-you, I see. That pr should bring perf. back. Since the regression is not large (1.x%), let's ignore the rebase impact. Thanks!

**Pull request merged**
