### PR TITLE
[GJ-86] Enable q1 transformation

### PR DESCRIPTION
**Pull request by rui-mo**
This pr:

- Enabled the transformation needed in TPC-H Q1.
- Separate pre-projection from Agg.
Closes https://github.com/oap-project/gazelle-jni/issues/86.

### CODE REVIEW

**Comment by zzcclp** [comment]
there are some conflicts, please rebase.

**Comment by QiangCai** [comment]
@rui-mo which velox branch you used for this PR?

**Comment by QiangCai** [comment]
@rui-mo which velox branch is this PR basing on ?

**Comment by rui-mo** [comment]
@QiangCai To build with Velox, you can use velox_dev branch, and check below issue to use the correct Velox branch and Arrow.
https://github.com/oap-project/gluten/issues/85
BTW, we are going to move the velox_dev branch to master, please see this PR:
https://github.com/oap-project/gluten/pull/101.

**Pull request merged**
