### PR TITLE
[OPPRO-307] Support limit on Velox backend

### PR DESCRIPTION
**Pull request by rui-mo**
## What changes were proposed in this pull request?

This PR supports limit on Velox backend.

## How was this patch tested?

verified on Jenkins.

### CODE REVIEW

**Review by JkSelf — APPROVED** [review]
LGTM. Can we  add a simple unit test?

**Comment by rui-mo** [comment]
> LGTM. Can we add a simple unit test?

Added unit test.

**Comment by JkSelf** [comment]
@rui-mo 
In Gluten, both GlobalLimitExec and LocalLimitExec are converted to LimitTransformer. Do we need to do special handling on the Velox side or not?

**Comment by rui-mo** [comment]
@JkSelf Merging this PR, if you have further comments, you can still comment here, thanks!

**Comment by JkSelf** [comment]
> > @rui-mo In Gluten, both GlobalLimitExec and LocalLimitExec are converted to LimitTransformer. Do we need to do special handling on the Velox side or not?
> 
> Velox LimitNode has a parameter naming `isPartial_` but it only take effect for logging. The logic of both are almost the same in Velox and Spark (BaseLimitExec), and the difference is final limit can only be single-threaded while partial limit is executed by each task in Spark.

Got it. Thanks for your explain.

**Pull request merged**
