### PR TITLE
[CORE] Minor refactor WholeStageTransformContext

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

WholeStageTransformContext's intputAttr and outputAttr are unused.

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by PHILO-HE** [comment]
Just note some code style test failure for CH backend. You can try to create a fix:
`mvn spotless:apply -Pbackends-clickhouse -Pspark-3.2 -DskipTests -Pspark-ut`
or
`mvn spotless:apply -Pbackends-clickhouse -Pspark-3.3 -DskipTests -Pspark-ut`

**Comment by Yohahaha** [comment]
> Just note some code style test failure for CH backend. You can try to create a fix: `mvn spotless:apply -Pbackends-clickhouse -Pspark-3.2 -DskipTests -Pspark-ut` or `mvn spotless:apply -Pbackends-clickhouse -Pspark-3.3 -DskipTests -Pspark-ut`

Thanks! will request for review when all CI passed.

**Comment by Yohahaha** [comment]
Hi @PHILO-HE, this PR is ready for review.

**Review by PHILO-HE — APPROVED** [review]
Looks great!

**Pull request merged**
