### PR TITLE
[VL] Optimize the method of obtaining taskAttemptId in nativeMake

### PR DESCRIPTION
**Pull request by kerwin-zk**
## What changes were proposed in this pull request?
Optimize the method of obtaining taskAttemptId in nativeMake

### CODE REVIEW

**Comment by kerwin-zk** [comment]
@jinchengchenghh @zhztheplayer cc

**Review by jinchengchenghh — DISMISSED** [review]

**Comment by kerwin-zk** [comment]
@zhouyuan cc

**Comment by zhztheplayer** [comment]
@kerwin-zk Can you rebase?

**Comment by kerwin-zk** [comment]
> @kerwin-zk Can you rebase?

OK. I'll handle it.

**Comment by kerwin-zk** [comment]
@zhztheplayer done.

**Review by zhztheplayer — APPROVED** [review]

**Pull request merged**
