### PR TITLE
[VL] (Refactor) Using createXXX replace getXXX to indicate creating object

### PR DESCRIPTION
**Pull request by zuochunwei**
## What changes were proposed in this pull request?

 
(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zuochunwei** [comment]
@zhztheplayer

**Comment by FelixYBW** [comment]
Do we append back trace info to exception string?

**Comment by zuochunwei** [comment]
> Do we append back trace info to exception string?

Not yet.
I found that the backtrace is also used in Velox.

**Comment by zhztheplayer** [comment]
Hi @zuochunwei Can we use a pipelined `AllocationListener` to achieve this? These days we actively modify the memory code so it's great if we make sure this kind of debug code easy to maintain.

**Comment by zuochunwei** [comment]
> Hi @zuochunwei Can we use a pipelined `AllocationListener` to achieve this? These days we actively modify the memory code so it's great if we make sure this kind of debug code easy to maintain.

sounds good, I will improve this PR

**Review by zhztheplayer — APPROVED** [review]

**Pull request merged**
