### PR TITLE
Support set spark session config to native query context

### PR DESCRIPTION
**Pull request by jinchengchenghh**
Move some configs from static config to session config
Some configs in spark is not static, such as `hadoop.fs.defaultFS`,  but in gluten, it is static, because it should be used to register Hive connector which should be reused in velox

### CODE REVIEW

**Comment by FelixYBW** [comment]
Memo: Spark configurations are divided into two category, one is static one and configured once spark context is started, the other one is dynamic which can be configured at run time and take effect once it's set. It's possible to set it per query. Previously Gluten only support static one. The PR added the feature to support dynamic configuration. The used configurations are passed to native on each native iterator contruction which is at the beginning of each task. Then in the task it uses the same configuration

**Comment by zhztheplayer** [comment]
> Some configs in spark is not static, such as hadoop.fs.defaultFS, but in gluten, it is static, because it should be used to register Hive connector which should be reused in velox

Would you mean user can re-set options like `hadoop.fs.defaultFS` in a single Spark session? Then it may result in problem if we only pick the earliest one. Can we add some FIXMEs in code if we cannot deal with this kind of problem at this time?

**Comment by FelixYBW** [comment]
> Would you mean user can re-set options like `hadoop.fs.defaultFS` in a single Spark session? Then it may result in problem if we only pick the earliest one. Can we add some FIXMEs in code if we cannot deal with this kind of problem at this time?

@jinchengchenghh  Can we distinguish static and dynamic config? here we only pass dynamic config. Static config still use the old static map when loading library.

**Comment by jinchengchenghh** [comment]
> > Would you mean user can re-set options like `hadoop.fs.defaultFS` in a single Spark session? Then it may result in problem if we only pick the earliest one. Can we add some FIXMEs in code if we cannot deal with this kind of problem at this time?
> 
> @jinchengchenghh Can we distinguish static and dynamic config? here we only pass dynamic config. Static config still use the old static map when loading library. Because some static config need to be used by shuffle as well.

Yes, static config still is in old static map, but it contains some dynamic configs, if we move these(include S3 and HDFS config and so on) to dynamic config, we need to register HiveConnector for each iterator.

**Comment by FelixYBW** [comment]
No, I mean we only pass the dynamic config for each iterator. Keep the static config as it is now.

**Comment by zhztheplayer** [comment]
> Yes, static config still is in old static map, but it contains some dynamic configs, if we move these(include S3 and HDFS config and so on) to dynamic config, we need to register HiveConnector for each iterator.

My understanding is that if one runs `set spark.hadoop.fs.defaultFS=xxx` in the Spark session, Gluten's native code will not be aware of that. But the same will take effects on Vanilla Spark's components which are being reused by Gluten, for example the Catalyst planner, thus this will create inconsistency. It may not be a big deal and we can add some TODOs/FIXMEs for that

**Comment by jinchengchenghh** [comment]
> > Yes, static config still is in old static map, but it contains some dynamic configs, if we move these(include S3 and HDFS config and so on) to dynamic config, we need to register HiveConnector for each iterator.
> 
> My understanding is that if one runs `set spark.hadoop.fs.defaultFS=xxx` in the Spark session, Gluten's native code will not be aware of that. But the same will take effects on Vanilla Spark's components which are being reused by Gluten, for example the Catalyst planner, thus this will create inconsistency. It may not be a big deal and we can add some TODOs/FIXMEs for that

Yes, you are right

**Review by zhztheplayer — APPROVED** [review]
Thanks!

**Pull request merged**
