### PR TITLE
[VL] Refactor split buffer allocation

### PR DESCRIPTION
**Pull request by marin-ma**
Extract the duplicated logic in both `resizePartitionBuffer` and `allocatePartitionBuffer`.
In prealloc partition buffer, use `resizePartitionBuffer` instead of `allocatePartitionBuffer` if need to preserve buffer data for the next split, and remove the resize branch in `allocate PartitionBuffer`.

### CODE REVIEW

**Comment by marin-ma** [comment]
@FelixYBW Could you help to review? Thanks!

**Review by FelixYBW — APPROVED** [review]
Thank you for your work!

**Pull request merged**
