### PR TITLE
[CORE] Upgrade spark 34 version to 342

### PR DESCRIPTION
**Pull request by JkSelf**
## What changes were proposed in this pull request?

Upgrade spark 34 version to 342.

## How was this patch tested?

Existing unit tests.

### CODE REVIEW

**Comment by FelixYBW** [comment]
Does it impact UT?

**Comment by JkSelf** [comment]
> Does it impact UT?

Yes.  The TPC-H and TPC-DS can passed. However the unit tests failed.

**Review by PHILO-HE — APPROVED** [review]
Looks good!

**Comment by JkSelf** [comment]
@FelixYBW @PHILO-HE Thanks for your review. I will merge this PR firstly and record the four failed https://github.com/oap-project/gluten/issues/3559.

**Pull request merged**
