### PR TITLE
[GLUTEN-4141][VL] Support Gluten Build in Debian 11

### PR DESCRIPTION
**Pull request by surnaik**
## What changes were proposed in this pull request?

Adds Support for building Gluten in Debian 11

(Fixes: #4141)

## How was this patch tested?

Manually built and tested in a Debian 11 environment

### CODE REVIEW

**Comment by surnaik** [comment]
@zhouyuan Please review. Thanks!

**Comment by surnaik** [comment]
> 👍 haven't tested but looks good based on the code

Thanks @zhouyuan , appreciate it! I have tested it manually on a debian 11 spark 3.3 cluster.

**Comment by FelixYBW** [comment]
we can merge the PR but we don't and won't have CI to track the Debian 11 build.

**Comment by FelixYBW** [comment]
Is there any script changes in Velox side?

**Pull request merged**
