### PR TITLE
[VL][CI] Increase the scale of testing dataset

### PR DESCRIPTION
**Pull request by rui-mo**
## What changes were proposed in this pull request?

Increase the scale of testing TPC-DS dataset from 0.1G to 1.0G, 10.0G and 30.0G.

## How was this patch tested?

Testing the time consumption.

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by zhouyuan** [comment]
SF100 seems too big, can you please try to use sf1 or sf10 ?

**Comment by FelixYBW** [comment]
Why do we need to increase? is it because some bugs not shown in small SF?

**Comment by rui-mo** [comment]
> Why do we need to increase? is it because some bugs not shown in small SF?

@FelixYBW Yes, we found undetected bug if the dataset was too small. After trying, 30G could be the smallest size to uncover this known bug.

**Comment by FelixYBW** [comment]
> @FelixYBW Yes, we found undetected bug if the dataset was too small. After trying, 30G could be the smallest size to uncover this known bug.

Is it a single bug? Maybe it's not efficient to adjust the the config for any single bug. We need some regular stress test to cover these bugs, instead of CI tool.

**Comment by rui-mo** [comment]
> Is it a single bug? Maybe it's not efficient to adjust the the config for any single bug. We need some regular stress test to cover these bugs, instead of CI tool.

Two bugs can be uncovered on a larger dataset. If the scale is too small, some queries have empty output for both vanilla and Gluten, so the bugs are hidden.

**Comment by kerwin-zk** [comment]
> @kerwin-zk this patch tries to increase the scale factor of TPCDS, however celeborn based shuffle seems run into `PushDataTimeout` failures, can you please take a look here?
> 
> -yuan

@zhouyuan This may be a parameter problem, the default parameters of celeborn need to be modified, because there is only one node, so the default parameters cannot support increased data.

**Review by FelixYBW — APPROVED** [review]

**Comment by rui-mo** [comment]
@kerwin-zk Thank you. I will try that.

**Comment by kerwin-zk** [comment]
@rui-mo  For new exception information, a new parameter needs to be added. In gluten-it's Constants.scala, add .set("spark.celeborn.push.limit.inFlight.timeout", "1200s") to the VELOX_WITH_CELEBORN_CONF parameter.

**Comment by rui-mo** [comment]
> @rui-mo For new exception information, a new parameter needs to be added. In gluten-it's Constants.scala, add .set("spark.celeborn.push.limit.inFlight.timeout", "1200s") to the VELOX_WITH_CELEBORN_CONF parameter.

@kerwin-zk Thank you. Will try that.

**Review by zhouyuan — APPROVED** [review]
👍

**Pull request merged**
