### PR TITLE
[CH] minor improvements for BroadCastJoinBuilder

### PR DESCRIPTION
**Pull request by exmy**
## How was this patch tested?

 manual tests

### CODE REVIEW

**Comment by exmy** [comment]
@zzcclp @liuneng1994 Could you help review this?

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Comment by liuneng1994** [comment]
Run Gluten Clickhouse CI

**Comment by exmy** [comment]
Run Gluten Clickhouse CI

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
