### PR TITLE
[OPPRO-41] Handle null in velox to row

### PR DESCRIPTION
**Pull request by rui-mo**
## What changes were proposed in this pull request?

Supported null handling in Velox to Row conversion.

## How was this patch tested?

Verified on Jenkins.
Tested with https://github.com/oap-project/velox/pull/36 and https://github.com/oap-project/velox/pull/35.

### CODE REVIEW

**Comment by rui-mo** [comment]
Hi @zhztheplayer, please help take a review, thanks.

**Comment by FelixYBW** [comment]
Do we still use Velox to Row? I remember @zhztheplayer changed to arrow to row.

**Comment by rui-mo** [comment]
> 



> Do we still use Velox to Row? I remember @zhztheplayer changed to arrow to row.

If the input is from whole stage transformer, we are using Velox to Row, and Velox's internal conversion is used. If the input is from other operators, for example, shuffle, then Arrow to Row is used.

**Comment by rui-mo** [comment]
Hi @zhztheplayer @JkSelf, could you help review this PR? Thanks.

**Comment by JkSelf** [comment]
@rui-mo LGTM. Also Verified in local TPC-DS queries.

**Review by JkSelf — APPROVED** [review]
LGTM

**Pull request merged**
