### PR TITLE
[GLUTEN-3917][FOLLOWUP] Add back SparkShimLoader import

### PR DESCRIPTION
**Pull request by ulysses-you**
## What changes were proposed in this pull request?

Fix SparkShimLoader not found.

## How was this patch tested?

Pass CI

### CODE REVIEW

**Review by PHILO-HE — APPROVED** [review]
Thanks for your fix!

**Comment by JkSelf** [comment]
@ulysses-you Thanks for your quickly fix!

**Review by JkSelf — APPROVED** [review]
LGTM. Thanks.

**Comment by ulysses-you** [comment]
The build step is passed, I'm merging it to unblock CI.

**Pull request merged**
