### PR TITLE
[CH-320] Support space function

### PR DESCRIPTION
**Pull request by KevinyhZou**
## What changes were proposed in this pull request?
Support space function for clickhouse 
the releated pr: https://github.com/Kyligence/ClickHouse/pull/321
the realted issue: https://github.com/Kyligence/ClickHouse/issues/320

## How was this patch tested?
by add unit test in GlutenClickHouseTPCHSUite.scala

### CODE REVIEW

**Comment by KevinyhZou** [comment]
@zzcclp  rebase done. this function use repeat function to implement,  I have sumit a pr to ch to support this function: https://github.com/ClickHouse/ClickHouse/pull/47049,  and it was suggested to use repeat function replace this,

**Comment by zzcclp** [comment]
please rebase and rerun all test case

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by KevinyhZou** [comment]
done @zzcclp

**Review by zzcclp — APPROVED** [review]
LGTM

**Comment by zzcclp** [comment]
BTW, @rui-mo please help to check whether velox supports this function ?

**Comment by rui-mo** [comment]
> BTW, @rui-mo please help to check whether velox supports this function ?

@zzcclp Looks not yet. It's OK to add it in Gluten because it will fallback if there is no registration for this function in Velox.

**Comment by zzcclp** [comment]
> > BTW, @rui-mo please help to check whether velox supports this function ?
> 
> @zzcclp Looks not yet. It's OK to add it in Gluten because it will fallback if there is no registration for this function in Velox.

does it need to add this function into VELOX_EXPR_BLACKLIST ?

**Comment by rui-mo** [comment]
> does it need to add this function into VELOX_EXPR_BLACKLIST ?

@zzcclp That is only temporarily needed for those implemented in Velox but have different semantics or results. For the unimplemented ones, a search to the function registration map will help reject.

**Pull request merged**
