### PR TITLE
[OPPRO-110] Use static lib of Protobuf

### PR DESCRIPTION
**Pull request by zhztheplayer**
Dynamical linking libprotobuf.so can cause a problem since the substrait proto has been defined in several places (e.g. Arrow, Velox, Gluten):

> [libprotobuf ERROR google/protobuf/descriptor_database.cc:644] File already exists in database: substrait/extensions/extensions.proto

A reasonable solution is to static link libprotobuf.a to all targets requiring protobuf in build process.

### CODE REVIEW

**Comment by zhouyuan** [comment]
this should be already fixed by?
https://github.com/oap-project/gluten/blob/main/tools/build_velox.sh#L62

**Comment by zhztheplayer** [comment]
The commit you mentioned was included when seeing the error. I guess it's because Gluten's dynamically linking libprotobuf.so which was hard coded, and Arrow also has chance to make dynamic link if we don't explicitly set `-DARROW_PROTOBUF_USE_SHARED=OFF`.

**Comment by zhouyuan** [comment]
@marin-ma

**Comment by zhztheplayer** [comment]
@marin-ma if you have any comments. thanks.

@zzcclp would you like to review also? Thanks.

**Comment by marin-ma** [comment]
LGTM.

**Pull request merged**
