### PR TITLE
[VL] Change preferEvict to preferSpill

### PR DESCRIPTION
**Pull request by zuochunwei**
## What changes were proposed in this pull request?

It's misleading to use `preferEvict` and `preferSpill` interleaved, I prefer `preferSpill` to `preferEvict`.

(Please fill in changes proposed in this fix)

(Fixes: \#ISSUE-ID)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by PHILO-HE** [comment]
LGTM! Thanks! @zhztheplayer, please take a look.

**Comment by marin-ma** [comment]
This one is conflicted with #3091

**Comment by zuochunwei** [comment]
> This one is conflicted with #3091

preferSpill=false will cause big jobs to fail

**Comment by marin-ma** [comment]
Do we still need this PR?

**Comment by FelixYBW** [comment]
we have removed preferspill, now we only support preferspill=false in localshufflewrite and preferspill=true for remoteshuffle

**Comment by PHILO-HE** [comment]
Suppose this PR is not needed. Will close it soon. Thanks!

**Pull request closed without merging**
