### PR TITLE
[VL] Remove combined buffer in shuffle split and use default allocator

### PR DESCRIPTION
**Pull request by marin-ma**

### CODE REVIEW

**Comment by FelixYBW** [comment]
So the split buffer uses ShuffleMemoryPool, spill buffer uses arrow::default_pool, right?

**Comment by marin-ma** [comment]
> So the split buffer uses ShuffleMemoryPool, spill buffer uses arrow::default_pool, right?

Yes. Only split buffer uses ShuffleMemoryPool.

**Review by zhztheplayer — APPROVED** [review]

**Review by zhztheplayer — APPROVED** [review]

**Comment by zuochunwei** [comment]
Why we made this change?

**Comment by FelixYBW** [comment]
This is part of the OOM solution. We need to shrink or reallocate split buffer on OOM. In this way large combine buffer can't be used any more.

**Pull request merged**
