### PR TITLE
[CORE] Improve rewrite spark plan rules framework

### PR DESCRIPTION
**Pull request by ulysses-you**
## What changes were proposed in this pull request?

This pr adds a framework `RewriteSparkPlanRulesManager` to help rewrite spark plan rules and tag transform hint. It moves AddTransformHintRule before rewrite rules. `RewriteSparkPlanRulesManager` would rewrite plan and apply AddTransformHintRule for each opeartor. If the rewritten opeartor is still TRANSFORM_UNSUPPORTED, using original opeartor.

This pr also removes applyForValidation in AddTransformHintRule, so that we do not need to apply rewrite rules twice.

## How was this patch tested?

Pass CI

### CODE REVIEW

**Comment by ulysses-you** [comment]
cc @liujiayi771 thank you

**Comment by liujiayi771** [comment]
@ulysses-you Great design. LGTM. Thanks.

**Review by yaooqinn — APPROVED** [review]

**Pull request merged**
