### PR TITLE
[Gluten-core] Remove jni unload log

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by Yohahaha** [comment]
I'm not sure this log is necessary, if yes, let's use LOG(INFO) instead of std::cerr.

@rui-mo @zhztheplayer @zhouyuan

**Comment by Yohahaha** [comment]
This pr should not make CI fails.

**Comment by rui-mo** [comment]
> This pr should not make CI fails.

@Yohahaha Yes, you're right. We've just fixed the failure on main branch, would you like to rebase this PR?

**Comment by Yohahaha** [comment]
> > This pr should not make CI fails.
> 
> @Yohahaha Yes, you're right. We've just fixed the failure on main branch, would you like to rebase this PR?

Thanks, done.

**Review by waitinfuture — DISMISSED** [review]
LGTM, but I prefer to retain this log currently.

**Review by FelixYBW — APPROVED** [review]

**Comment by FelixYBW** [comment]
> 

change to log(info)?

**Comment by Yohahaha** [comment]
Why need keep this log? If use LOG(INFO), it will print to standard error by default, and we can not control this behavior.
Print a meaningless and uncontrollable log to user cause confusion.

**Comment by FelixYBW** [comment]
> Why need keep this log? If use LOG(INFO), it will print to standard error by default, and we can not control this behavior. Print a meaningless and uncontrollable log to user cause confusion.

I'm ok without it

**Review by zhztheplayer — APPROVED** [review]

**Pull request merged**
