### PR TITLE
[GLUTEN-3473][VL]  Add rapidjson-dev library to the setup instructions

### LINKED ISSUE #3473: rapidjson library needs to be installed for velox build but it is not part of the apt-get setup instructions
### Problem description

I was running builddeps-veloxbe.sh from 84599e16661d6ae1eba633e4ebaa30c5def37fe4 

### System information

Velox System Info v0.0.2
Commit: 84599e16661d6ae1eba633e4ebaa30c5def37fe4
CMake Version: 3.26.4
System: Linux-6.2.0-32-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/home/holden/miniconda3/lib/python3.10/site-packages/cmake/data;/usr/local;/usr/X11R6;/usr/pkg;/opt
  
Conda Env
<details>

```
# packages in environment at /home/holden/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.4.0                    pypi_0    pypi
accelerate                0.19.0                   pypi_0    pypi
adagio                    0.2.4                    pypi_0    pypi
aiofiles                  22.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiohttp-cors              0.7.0                    pypi_0    pypi
aiorwlock                 1.3.0                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aiosqlite                 0.19.0                   pypi_0    pypi
amqp                      5.1.1                    pypi_0    pypi
ansible                   7.5.0                    pypi_0    pypi
ansible-core              2.14.5                   pypi_0    pypi
antlr4-python3-runtime    4.11.1                   pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asgiref                   3.7.2                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
atomicwrites              1.4.1                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
autopep8                  2.0.2                    pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
behave                    1.2.6                    pypi_0    pypi
billiard                  4.1.0                    pypi_0    pypi
bitsandbytes              0.39.0                   pypi_0    pypi
black                     23.7.0                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    6.0.0                    pypi_0    pypi
blessed                   1.20.0                   pypi_0    pypi
boltons                   23.0.0          py310h06a4308_0  
brotli                    1.0.9                    pypi_0    pypi
brotlipy                  0.7.0           py310h7f8727e_1002  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2022.12.7            ha878542_0    conda-forge
cachetools                5.3.1                    pypi_0    pypi
celery                    5.3.1                    pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
cffi                      1.15.1          py310h5eee18b_3  
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
click-didyoumean          0.3.0                    pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
click-repl                0.3.0                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
cmake                     3.26.4                   pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
colorful                  0.5.5                    pypi_0    pypi
comm                      0.1.3                    pypi_0    pypi
conda                     23.3.1          py310hff52083_0    conda-forge
conda-content-trust       0.1.3           py310h06a4308_0  
conda-package-handling    2.0.2           py310h06a4308_0  
conda-package-streaming   0.7.0           py310h06a4308_0  
contourpy                 1.1.0                    pypi_0    pypi
cron-descriptor           1.4.0                    pypi_0    pypi
croniter                  1.3.15                   pypi_0    pypi
cryptography              38.0.4          py310h9ce1e76_0  
cssselect                 1.2.0                    pypi_0    pypi
cssselect2                0.7.0                    pypi_0    pypi
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cycler                    0.11.0                   pypi_0    pypi
dask                      2023.4.0                 pypi_0    pypi
dask-kubernetes           2023.3.2                 pypi_0    pypi
dataclasses-json          0.5.7                    pypi_0    pypi
datacompy                 0.10.2                   pypi_0    pypi
datasets                  2.12.0                   pypi_0    pypi
dateutils                 0.6.12                   pypi_0    pypi
debugpy                   1.6.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deepdiff                  6.3.0                    pypi_0    pypi
deepspeed                 0.10.1+7f26bb6a          pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
diff-cover                7.5.0                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
dirtyjson                 1.0.8                    pypi_0    pypi
distlib                   0.3.7                    pypi_0    pypi
distributed               2023.4.0                 pypi_0    pypi
django                    4.2.3                    pypi_0    pypi
django-appconf            1.0.5                    pypi_0    pypi
django-celery-beat        2.5.0                    pypi_0    pypi
django-classy-tags        4.0.0                    pypi_0    pypi
django-cms                3.11.3                   pypi_0    pypi
django-compressor         4.4                      pypi_0    pypi
django-compressor-toolkit 0.6.0                    pypi_0    pypi
django-configurations     2.4.1                    pypi_0    pypi
django-cookie-consent     0.4.0                    pypi_0    pypi
django-extensions         3.2.3                    pypi_0    pypi
django-filer              3.0.0                    pypi_0    pypi
django-formtools          2.4.1                    pypi_0    pypi
django-memoize            2.3.1                    pypi_0    pypi
django-pipeline           2.1.0                    pypi_0    pypi
django-polymorphic        3.1.0                    pypi_0    pypi
django-regex-field        3.1.0                    pypi_0    pypi
django-sekizai            4.1.0                    pypi_0    pypi
django-stubs              4.2.3                    pypi_0    pypi
django-stubs-ext          4.2.2                    pypi_0    pypi
django-timezone-field     5.1                      pypi_0    pypi
django-treebeard          4.7                      pypi_0    pypi
django-user-agents        0.4.0                    pypi_0    pypi
djangocms-admin-style     3.2.4                    pypi_0    pypi
djangocms-attributes-field 3.0.0                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docstring-parser          0.15                     pypi_0    pypi
docutils                  0.20.1                   pypi_0    pypi
dotmap                    1.3.30                   pypi_0    pypi
easy-thumbnails           2.8.5                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
enum-compat               0.0.3                    pypi_0    pypi
exceptiongroup            1.1.1                    pypi_0    pypi
execnet                   2.0.2                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
falcontune                0.1.0                    pypi_0    pypi
fastapi                   0.88.0                   pypi_0    pypi
fasteners                 0.18                     pypi_0    pypi
fastjsonschema            2.16.3                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.12.4                   pypi_0    pypi
findspark                 2.0.1                    pypi_0    pypi
fonttools                 4.40.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.3.3                    pypi_0    pypi
fs                        2.4.16                   pypi_0    pypi
fsspec                    2023.4.0                 pypi_0    pypi
fugue                     0.8.5                    pypi_0    pypi
fugue-sql-antlr           0.1.6                    pypi_0    pypi
fuzzywuzzy                0.18.0                   pypi_0    pypi
geographiclib             2.0                      pypi_0    pypi
geopy                     2.3.0                    pypi_0    pypi
giflib                    5.2.1                h5eee18b_3  
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2           py310heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
google-api-core           2.11.1                   pypi_0    pypi
google-auth               2.17.3                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
googleapis-common-protos  1.59.1                   pypi_0    pypi
gpustat                   1.1                      pypi_0    pypi
greenlet                  2.0.2                    pypi_0    pypi
grpcio                    1.51.3                   pypi_0    pypi
gunicorn                  20.1.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
h5py                      3.9.0                    pypi_0    pypi
haversine                 2.8.0                    pypi_0    pypi
hjson                     3.1.0                    pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
huggingface-hub           0.14.1                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
icd10-cm                  0.0.5                    pypi_0    pypi
idna                      3.4             py310h06a4308_0  
importlib-metadata        6.6.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
inquirer                  3.1.3                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.22.0                   pypi_0    pypi
ipython                   8.12.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
iso8601                   1.1.0                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jaraco-classes            3.3.0                    pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jeepney                   0.8.0                    pypi_0    pypi
jinja2                    3.1.2           py310h06a4308_0  
jira                      3.5.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
json5                     0.9.11                   pypi_0    pypi
jsonargparse              4.21.2                   pypi_0    pypi
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter-client            8.2.0                    pypi_0    pypi
jupyter-core              5.3.0                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-server            2.5.0                    pypi_0    pypi
jupyter-server-fileid     0.9.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyter-server-ydoc       0.8.0                    pypi_0    pypi
jupyter-ydoc              0.2.4                    pypi_0    pypi
jupyterlab                3.6.3                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.22.1                   pypi_0    pypi
keyring                   24.2.0                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
kombu                     5.3.1                    pypi_0    pypi
kopf                      1.36.0                   pypi_0    pypi
kubernetes                26.1.0                   pypi_0    pypi
kubernetes-asyncio        24.2.2                   pypi_0    pypi
lame                      3.100                h7b6447c_0  
langchain                 0.0.201                  pypi_0    pypi
langchainplus-sdk         0.0.10                   pypi_0    pypi
langdetect                1.0.9                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
levenshtein               0.21.1                   pypi_0    pypi
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.6.1.9                       0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.17                 h5eee18b_0  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.2                h7f8727e_0  
libnpp                    11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.41.5               h5eee18b_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lightning                 2.1.0.dev0               pypi_0    pypi
lightning-cloud           0.5.36                   pypi_0    pypi
lightning-utilities       0.8.0                    pypi_0    pypi
linecache2                1.0.0                    pypi_0    pypi
lit                       16.0.5.post0             pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lxml                      4.9.3                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
marshmallow               3.19.0                   pypi_0    pypi
marshmallow-enum          1.5.1                    pypi_0    pypi
matplotlib                3.7.2                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
meshtastic                2.1.6                    pypi_0    pypi
mistune                   2.0.5                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0           py310h7f8727e_0  
mkl_fft                   1.3.1           py310hd6ae3a3_0  
mkl_random                1.2.2           py310h00e6091_0  
more-itertools            10.1.0                   pypi_0    pypi
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mplcursors                0.5.2                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
msgpack                   1.0.5                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multimethod               1.9.1                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
mypy                      1.4.1                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nbclassic                 0.5.5                    pypi_0    pypi
nbclient                  0.7.3                    pypi_0    pypi
nbconvert                 7.3.1                    pypi_0    pypi
nbformat                  5.8.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6                    pypi_0    pypi
nettle                    3.7.3                hbbd107a_1  
networkx                  2.8.4           py310h06a4308_1  
nh3                       0.2.14                   pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.5.4                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numexpr                   2.8.4                    pypi_0    pypi
numpy                     1.24.3          py310hd5efca6_0  
numpy-base                1.24.3          py310h8e6c178_0  
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-ml-py              12.535.77                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openapi-schema-pydantic   1.2.4                    pypi_0    pypi
opencensus                0.11.2                   pypi_0    pypi
opencensus-context        0.1.3                    pypi_0    pypi
opencv-python             4.8.0.74                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1t               h7f8727e_0  
optimum                   1.8.5                    pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
outcome                   1.2.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.1                    pypi_0    pypi
pandera                   0.16.1                   pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parameterized             0.9.0                    pypi_0    pypi
parse                     1.19.1                   pypi_0    pypi
parse-type                0.6.2                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.4.0                    pypi_0    pypi
pathlib-mate              1.2.1                    pypi_0    pypi
pathspec                  0.11.1                   pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pdbp                      1.5.0                    pypi_0    pypi
peft                      0.3.0                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.4.0           py310h6a678d5_0  
pip                       23.2.1                   pypi_0    pypi
pkginfo                   1.9.6                    pypi_0    pypi
platformdirs              3.10.0                   pypi_0    pypi
pluggy                    1.0.0           py310h06a4308_1  
prettytable               3.8.0                    pypi_0    pypi
prometheus-client         0.16.0                   pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
py-spy                    0.3.14                   pypi_0    pypi
py4j                      0.10.9.7                 pypi_0    pypi
pyarrow                   11.0.0                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pyclipper                 1.3.0.post4              pypi_0    pypi
pycosat                   0.6.4           py310h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  1.10.7                   pypi_0    pypi
pydyf                     0.7.0                    pypi_0    pypi
pygatt                    4.0.5                    pypi_0    pypi
pygments                  2.16.1                   pypi_0    pypi
pyjwt                     2.7.0                    pypi_0    pypi
pykube-ng                 22.9.0                   pypi_0    pypi
pynose                    1.4.8                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyotp                     2.9.0                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pypdf2                    3.0.1                    pypi_0    pypi
pypdfium2                 3.21.1                   pypi_0    pypi
pyphen                    0.14.0                   pypi_0    pypi
pyproject-api             1.6.1                    pypi_0    pypi
pypubsub                  4.0.3                    pypi_0    pypi
pyqrcode                  1.2.1                    pypi_0    pypi
pyqt5                     5.15.9                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.12.1                  pypi_0    pypi
pyre-extensions           0.0.29                   pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pyserial                  3.5                      pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0  
pyspark                   3.5.0                    pypi_0    pypi
pyspark-asyncactions      0.0.4                    pypi_0    pypi
pytesseract               0.3.10                   pypi_0    pypi
pytest                    7.3.1                    pypi_0    pypi
pytest-html               2.0.1                    pypi_0    pypi
pytest-metadata           3.0.0                    pypi_0    pypi
pytest-ordering           0.6                      pypi_0    pypi
pytest-rerunfailures      12.0                     pypi_0    pypi
pytest-xdist              3.3.1                    pypi_0    pypi
python                    3.10.9               h7a1cb2a_0  
python-crontab            2.7.1                    pypi_0    pypi
python-dateutil           2.8.2                    pypi_0    pypi
python-doctr              0.6.0                    pypi_0    pypi
python-editor             1.0.4                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
python-levenshtein        0.21.1                   pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytorch-cuda              11.8                 h7e8668a_3    pytorch
pytorch-lightning         2.0.3                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytorch-triton            2.1.0+440fd1bf20          pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.0.2                   pypi_0    pypi
qpd                       0.4.4                    pypi_0    pypi
rapidfuzz                 2.15.1                   pypi_0    pypi
ray                       2.5.1                    pypi_0    pypi
rcssmin                   1.1.1                    pypi_0    pypi
readchar                  4.0.5                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
readme-renderer           42.0                     pypi_0    pypi
regex                     2023.5.4                 pypi_0    pypi
reportlab                 4.0.4                    pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
requests-toolbelt         1.0.0                    pypi_0    pypi
resolvelib                0.8.1                    pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986                   2.0.0                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rich                      13.5.2                   pypi_0    pypi
rjsmin                    1.2.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel.yaml               0.17.21         py310h5eee18b_0  
ruamel.yaml.clib          0.2.6           py310h5eee18b_1  
sacremoses                0.0.53                   pypi_0    pypi
safetensors               0.3.1                    pypi_0    pypi
sbvirtualdisplay          1.2.0                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
secretstorage             3.3.3                    pypi_0    pypi
selenium                  4.11.2                   pypi_0    pypi
seleniumbase              4.18.6                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
sentry-sdk                1.25.1                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                68.2.2                   pypi_0    pypi
shapely                   1.8.5.post1              pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
smart-open                6.3.0                    pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sorl-thumbnail            12.9.0                   pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
spark-expectations        1.0.0                    pypi_0    pypi
spark-testing-base        0.10.0                   pypi_0    pypi
sqlalchemy                1.4.49                   pypi_0    pypi
sqlalchemy-mate           1.4.28.4                 pypi_0    pypi
sqlfluff                  2.0.7                    pypi_0    pypi
sqlfluff-plugin-sparksql-upgrade 0.0.0                     dev_0    <develop>
sqlglot                   17.4.1                   pypi_0    pypi
sqlite                    3.40.1               h5082296_0  
sqlparse                  0.4.4                    pypi_0    pypi
stack-data                0.6.2                    pypi_0    pypi
starlette                 0.22.0                   pypi_0    pypi
starsessions              1.3.0                    pypi_0    pypi
static-thumbnails         0.9                      pypi_0    pypi
stripe                    5.4.0                    pypi_0    pypi
svglib                    1.5.1                    pypi_0    pypi
sympy                     1.11.1          py310h06a4308_0  
tabcompleter              1.3.0                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tblib                     1.7.0                    pypi_0    pypi
tenacity                  8.2.2                    pypi_0    pypi
tensorboard               2.13.0                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
timeago                   1.0.16                   pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.3                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0          py310h06a4308_0  
torch                     2.0.1+cu118              pypi_0    pypi
torchaudio                2.0.2+cu118              pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchtriton               2.0.0                     py310    pytorch
torchvision               0.15.2+cu118             pypi_0    pypi
tornado                   6.3.1                    pypi_0    pypi
tox                       3.28.0                   pypi_0    pypi
tqdm                      4.64.1          py310h06a4308_0  
traceback2                1.4.0                    pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
transformers              4.29.2                   pypi_0    pypi
triad                     0.9.1                    pypi_0    pypi
trio                      0.22.2                   pypi_0    pypi
trio-websocket            0.10.4                   pypi_0    pypi
trl                       0.4.4                    pypi_0    pypi
twine                     4.0.2                    pypi_0    pypi
typeguard                 4.1.5                    pypi_0    pypi
types-pytz                2023.3.0.0               pypi_0    pypi
types-pyyaml              6.0.12.10                pypi_0    pypi
types-requests            2.31.0.1                 pypi_0    pypi
types-urllib3             1.26.25.13               pypi_0    pypi
typeshed-client           2.3.0                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
ua-parser                 0.18.0                   pypi_0    pypi
unidecode                 1.3.6                    pypi_0    pypi
unittest2                 1.1.0                    pypi_0    pypi
unittest2pytest           0.4                      pypi_0    pypi
uri-template              1.2.0                    pypi_0    pypi
urllib3                   2.0.4                    pypi_0    pypi
user-agents               2.2.0                    pypi_0    pypi
uszipcode                 1.0.1                    pypi_0    pypi
uvicorn                   0.22.0                   pypi_0    pypi
vine                      5.0.0                    pypi_0    pypi
virtualenv                20.24.5                  pypi_0    pypi
wandb                     0.15.3                   pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
weasyprint                59.0                     pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  2.3.4                    pypi_0    pypi
wheel                     0.41.2                   pypi_0    pypi
wrapt                     1.15.0                   pypi_0    pypi
wsproto                   1.2.0                    pypi_0    pypi
xformers                  0.0.20                   pypi_0    pypi
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.2.10               h5eee18b_1  
y-py                      0.5.9                    pypi_0    pypi
yarl                      1.9.1                    pypi_0    pypi
ypy-websocket             0.8.2                    pypi_0    pypi
zict                      3.0.0                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zopfli                    0.2.2                    pypi_0    pypi
zstandard                 0.18.0          py310h5eee18b_0  
zstd                      1.5.5                hc292b87_0  
```

</details>

### CMake log

_No response_

### PR DESCRIPTION
**Pull request by holdenk**
as it is required for the dependencies to build.

## What changes were proposed in this pull request?

Add rapidjson-dev library to the setup instructions

Fixes #3473 

## How was this patch tested?

Installed rapidjson-dev and re-ran setup script got success

See https://www.youtube.com/watch?v=UbB7v2f7A6k

### CODE REVIEW

**Comment by FelixYBW** [comment]
need we add to vcpk?

**Comment by holdenk** [comment]
@FelixYBW I don't think so: on a machine where I built it successfully I did `sudo apt-get remove librust-vcpkg-dev` and it was not installed.

**Comment by holdenk** [comment]
CC @FelixYBW can you review?

**Comment by holdenk** [comment]
Does anyone have time to review doc changes or should I drop this?

**Pull request closed without merging**
