### PR TITLE
[VL] Ut for bloomfilter validation fix

### PR DESCRIPTION
**Pull request by zhli1142015**
## What changes were proposed in this pull request?

Encounter this error when we run q93, we increase settings "spark.sql.optimizer.runtime.bloomFilter.maxNumItems" for our tests. add UT for fix in velox.

Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: (5404631 vs. 4000000) estimatedNumItems argument must be constant for all input rows
Retriable: False
Expression: newVal == val
Function: setConstantArgument
File: /var/git/Velox/velox/functions/sparksql/aggregates/BloomFilterAggAggregate.cpp
Line: 225

## How was this patch tested?

UT.

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by jinchengchenghh** [comment]
Please rebase to fix UT

**Comment by jinchengchenghh** [comment]
rebase velox and gluten code

**Comment by zhouyuan** [comment]
@zhli1142015 Can you please do a rebase? The velox patch is merged

-yuan

**Comment by jinchengchenghh** [comment]
Can you please rebase the 11 commits to one?

**Review by zhouyuan — APPROVED** [review]

**Comment by FelixYBW** [comment]
@jinchengchenghh can you merge?

**Pull request merged**
