### PR TITLE
[GLUTEN-1907][CH] Fix config_file error.

### PR DESCRIPTION
**Pull request by ditgittube**
## What changes were proposed in this pull request?

Fix excetpion after config spark.gluten.sql.columnar.backend.ch.runtime_config.config_file=/etc/native_engine/config.xml

(Fixes: \#1907)

## How was this patch tested?
start thrift after config config spark.gluten.sql.columnar.backend.ch.runtime_config.config_file

### CODE REVIEW

**Review by taiyang-li — APPROVED** [review]
LGTM

**Comment by taiyang-li** [comment]
Pls rebase on main

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Comment by liuneng1994** [comment]
Run Gluten Clickhouse CI

**Pull request merged**
