### PR TITLE
[DNM] Reproduce some bug

### PR DESCRIPTION
**Pull request by Yohahaha**

### CODE REVIEW

**Comment by Yohahaha** [comment]
Reproduce in velox-backend-ubuntu2004-test.

Correct result: {7, 7, 7}
Velox result: {7, 7, 7}
After convert RowVector to GlutenBatch: {null, 7, 7} or core

**Comment by Yohahaha** [comment]
@jinchengchenghh @rui-mo @zhztheplayer @zhouyuan

**Comment by rui-mo** [comment]
@Yohahaha Thank you. I will take a look later.

**Comment by Ma-Jian1** [comment]
This is caused by the last operator C2R, and toArray uses the memory freed by the iterator. @JkSelf has a fix maybe can resolve the problem.

**Comment by JkSelf** [comment]
@Yohahaha   This is a bug for spark 3.2 and 3.3. And we have merged [PR#40958](https://github.com/apache/spark/pull/40958) into spark 3.3 to fix this issue. I will port this fix in Gluten later. Thanks.

**Comment by Yohahaha** [comment]
Good to know this!

**Pull request closed without merging**
