### PR TITLE
[GLUTEN-2022][CH]Fix error: Can't find required partition column day in partition schema StructType()

### PR DESCRIPTION
**Pull request by taiyang-li**
## What changes were proposed in this pull request?

Fix error
```
Error in query: Can't find required partition column day in partition schema StructType()
```

(Fixes: \#2022)

### CODE REVIEW

**Comment by baibaichen** [comment]
How does you test?

**Comment by taiyang-li** [comment]
I will try to add an ut later @baibaichen

**Comment by loneylee** [comment]
LGTM

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
