### PR TITLE
[CH-232] Support DataTypeNothing, which close https://github.com/Kyligence/ClickHouse/issues/232

### PR DESCRIPTION
**Pull request by taiyang-li**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

test by CH[[249]]

### CODE REVIEW

**Comment by taiyang-li** [comment]
```
0: jdbc:hive2://localhost:10000/> explain formatted  select null from range(10);   

+----------------------------------------------------+
|                        plan                        |
+----------------------------------------------------+
| == Physical Plan ==
CHNativeColumnarToRow (5)
+- * ProjectExecTransformer (3)
   +- RowToCHNativeColumnar (2)
      +- * Range (1)


(1) Range [codegen id : 1]
Output [1]: [id#75L]
Arguments: Range (0, 10, step=1, splits=None)

(2) RowToCHNativeColumnar
Input [1]: [id#75L]

(3) ProjectExecTransformer
Input [1]: [id#75L]
Arguments: [null AS NULL#76]

(4) WholeStageCodegenTransformer (12)
Input [1]: [NULL#76]

(5) CHNativeColumnarToRow
Input [1]: [NULL#76]
```

**Review by lviiii — COMMENTED** [review]
Is there any UT to test DataTypeNothing?

**Comment by taiyang-li** [comment]
> Is there any UT to test DataTypeNothing?

I will add uts later.

**Review by lviiii — APPROVED** [review]
Ready to be merged after passing CI.

**Comment by taiyang-li** [comment]
Failed clickhouse backend ut can't be reproduced in my dev environment.

**Comment by taiyang-li** [comment]
I tried all uts in ClickHouseTestSettings.scala, but still can't reproduce the core in github actions.

**Comment by rui-mo** [comment]
> I tried all uts in ClickHouseTestSettings.scala, but still can't reproduce the core in github actions. Is it possible that we get some clues from backend hosts? @rui-mo

Hi @taiyang-li, I remember the host of CH backend is on Kyligence's machine. Maybe @zzcclp could help provide some information.

**Comment by loneylee** [comment]
> > I tried all uts in ClickHouseTestSettings.scala, but still can't reproduce the core in github actions. Is it possible that we get some clues from backend hosts? @rui-mo
> 
> Hi @taiyang-li, I remember the host of CH backend is on Kyligence's machine. Maybe @zzcclp could help provide some information.

It’s seem version mismatch backend and gluten rebase and try it again

**Comment by taiyang-li** [comment]
@lviiii The arrow ut was failed because 
`GET request of: org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.jar from central failed: Read timed out` .  Can you run it again?

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
