### PR TITLE
[CELEBORN] Unify the celeborn shuffle manager of velox and ch

### PR DESCRIPTION
**Pull request by kerwin-zk**
## What changes were proposed in this pull request?
* Decouple velox and  gluten-celeborn module, use two new modules in gluten-celeborn to support velox and ch respectively, and integrate the common parts into the common module
* Use a celeborn shuffle manager and pusher to support both velox and clickhouse
* Decouple celeborn and backends-clickhouse module, migrate the celeborn-related code and UT in the backends-clickhouse to the gluten-celeborn-clickhouse module

## How was this patch tested?
CI

### CODE REVIEW

**Comment by exmy** [comment]
Can you fix this issue #3012  as well while you're at it?

**Comment by ulysses-you** [comment]
> Could you fix this issue https://github.com/oap-project/gluten/issues/3012 as well while you're at it?

IIUC, it's hard to fix. Celeborn use the vanilla Spark shuffle reader and the shuffle read records is accumulated inside  vanilla Spark shuffle reader.

**Comment by kerwin-zk** [comment]
> Could you fix this issue #3012 as well while you're at it?

ok. I'll take a look together.

**Comment by kerwin-zk** [comment]
@exmy This issue #3012  has been resolved and you need to use the latest celeborn client. https://github.com/apache/incubator-celeborn/pull/1878

**Comment by exmy** [comment]
> @exmy This issue #3012 has been resolved and you need to use the latest celeborn client. [apache/incubator-celeborn#1878](https://github.com/apache/incubator-celeborn/pull/1878)

Thanks!

**Review by liuneng1994 — COMMENTED** [review]
LGTM

**Comment by exmy** [comment]
LGTM

**Review by liuneng1994 — APPROVED** [review]

**Pull request merged**
