### PR TITLE
[CH-250]Support grouping sets

### PR DESCRIPTION
**Pull request by lgbo-ustc**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

Support offloading grouping sets into clickhouse

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
unit tests

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)
test by CH[[251]]

### CODE REVIEW

**Comment by lgbo-ustc** [comment]
@rui-mo @JkSelf May you help to look at this problem? I think there are some problems in `ExpandExecTransformer`

At present, `ExpandExecTransformer` is based the assumption, columns in `projections` could be divided into two parts, aggregating columns and grouping columns(including grouping id column). For the following query
```SQL
select msgtype, hour, count(1) from t group by msgtype, hour with rollup
```
The `CustomExpandExec.projections` header is 
```
[msgtype#90L, msgtype#110L, hour#111, spark_grouping_id#109L]
```
The `CustomExpandExec.groupingExpressions` is 
```
[msgtype#110L, hour#111, spark_grouping_id#109L]
```

The `CustomExpandExec.aggregateExpressions` is 
```
[msgtype#90L]
```
The above assumption looks correct.



But this failed on test case `Gluten null count` in `GlutenDataFrameAggregateSuite`  
```scala
checkAnswer(
      testData3
        .agg(count($"a"), count($"b"), count(lit(1)), count_distinct($"a"), count_distinct($"b")),
      Row(2, 1, 2, 2, 1))
```
The `CustomExpandExec.projections` header is 
```
[a#12773, b#12774, gid#12772, b#12775]
```
The `CustomExpandExec.groupingExpressions` is 
```
[a#12773, b#12774, gid#12772]
```

The `CustomExpandExec.aggregateExpressions` is 
```
[partial_count(1), partial_count(b#12775)]
```

**Comment by JkSelf** [comment]
@lgbo-ustc This is a corner case, where the Expand operator is used to optimize the count distinct performance. The existing ExpandExecTransformer may not handle this use case. And can we fallback to vanilla spark?

**Comment by lgbo-ustc** [comment]
Yes, we can try to fallback the excution to vanilla spark.

 But I still have some questions. The aggretationg expressions seems don't be computed in the expand exec node, for example in the case `Gluten null count`. The projection expressions seems be the only one we need to care, why don't we use this directly to project one block into blocks?

**Comment by JkSelf** [comment]
Velox backend need the aggregation and grouping expressions when creating the GroupId node [here](https://github.com/facebookincubator/velox/blob/4214508faedb34e7375eab8e06aec897b4f88e0c/velox/core/PlanNode.h#L625). So we need passing separately  the aggregation and grouping expression from ExpandExecTransformer to native.

**Review by JkSelf — APPROVED** [review]
Filed [ISSUE#842](https://github.com/oap-project/gluten/issues/842) and will resolve this issue after velox community can accept the projections parameter to creating the GroupId node.

**Comment by zzcclp** [comment]
@JkSelf can this pr be merged?
BTW, @lgbo-ustc please rebase to main branch and re-run the test cases with Spark 3.3.

**Comment by JkSelf** [comment]
@zzcclp LGTM

**Pull request merged**
