### PR TITLE
[VL] Agg support Covariance function

### PR DESCRIPTION
**Pull request by liujiayi771**
## What changes were proposed in this pull request?

support corr, covar_pop and covar_samp agg function.

## How was this patch tested?

add test in velox backend TestOperator.

### CODE REVIEW

**Comment by rui-mo** [comment]
> Failed in udf/udf-group-by.sql and group-by.sql in GlutenSQLQueryTestSuite
> 
> ```
> gluten answer: 0.9999999999999999      0.9999999999999999      3
> spark answer:  1.0                     1.0                     3
> ```
> 
> @rui-mo Have you dealt with ut failures like this before?

@liujiayi771 I see. From CI logs, I noticed below two failures on Velox backend. You can also download them to check.

```shell
group-by.sql *** FAILED ***^[[0m
2023-03-09T02:54:49.3597692Z ^[[31m  group-by.sql^[[0m
2023-03-09T02:54:49.3599027Z ^[[31m  Expected "[1.0     1.0]    3", but got "[0.9999999999999999        0.9999999999999999]     3" Result did not match for query #26
```

```shell
udf/udf-group-by.sql - Regular Python UDF *** FAILED ***^[[0m
2023-03-09T03:05:04.3158417Z ^[[31m  udf/udf-group-by.sql - Regular Python UDF^[[0m
2023-03-09T03:05:04.3159494Z ^[[31m  Python: 3.8^[[0m
2023-03-09T03:05:04.3161046Z ^[[31m  Expected "[1.0     1.0]    3", but got "[0.9999999999999999        0.9999999999999999]     3" Result did not match for query
```

I think this is because the result comparion of `GlutenSQLQueryTestSuite` does not have precision tolerance. Would you like to take a look if the result comparision can be improved?

Also, there are below failures on CH backend. cc @zzcclp 

```shell
- group with sets *** FAILED ***
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 749.0 failed 1 times, most recent failure: Lost task 0.0 in stage 749.0 (TID 1555) (glutendev.c.kyligence-212803.internal executor driver): java.lang.RuntimeException: Parse substrait::Plan from string failed
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x1674ef7a in /tmp/libch.so
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x11bf33d5 in /tmp/libch.so
2. DB::Exception::Exception<char const (&) [41], void>(int, char const (&) [41]) @ 0xacc1dd6 in /tmp/libch.so
3. local_engine::SerializedPlanParser::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0xacb7f8a in /tmp/libch.so
4. Java_io_glutenproject_vectorized_ExpressionEvaluatorJniWrapper_nativeCreateKernelWithIterator @ 0xb07c386 in /tmp/libch.so
```

**Comment by zzcclp** [comment]
please rebase to main branch and try again.

**Comment by zhouyuan** [comment]
@liujiayi771 
can you please also rebase your velox branch? 
There are one commit to enable ltrim/rtrim in velox 
https://github.com/oap-project/velox/commits/main

-yuan

**Comment by liujiayi771** [comment]
> @liujiayi771 can you please also rebase your velox branch? There are one commit to enable ltrim/rtrim in velox https://github.com/oap-project/velox/commits/main
> 
> -yuan

ok

**Comment by zzcclp** [comment]
It needs to add these new agg functions in `CHExpressionUtil.CH_AGGREGATE_FUNC_BLACKLIST` to fallback

**Comment by liujiayi771** [comment]
> It needs to add these new agg functions in `CHExpressionUtil.CH_AGGREGATE_FUNC_BLACKLIST` to fallback

ok, I will add it.

**Comment by liujiayi771** [comment]
@rui-mo I found the problem. The calculation formulas of spark and velox are different when calculating the final result. Although they are equivalent in mathematics, the final result is biased due to reasons such as the retention of decimals in the computer calculation results. I modified the corr calculation formula in velox to make the result consistent with spark.

Some UTs fail because of NaN, I rewritten these UTs into GLUTEN_TEST, and removed the Row that would produce NaN.

**Comment by rui-mo** [comment]
@liujiayi771 Thank you!
> I modified the corr calculation formula in velox to make the result consistent with spark.

I recorded this change in https://github.com/oap-project/gluten/issues/822, because actually the changed aggregate function is a Presto sql one in Velox, and we need to add a Spark sql one in the long term.

**Comment by rui-mo** [comment]
> Some UTs fail because of NaN, I rewritten these UTs into GLUTEN_TEST, and removed the Row that would produce NaN.
 
Just curious, what is the failure case for NaN? Maybe like NaN being treated as NULL？

**Comment by liujiayi771** [comment]
> #822

Same as [#1047](https://github.com/oap-project/gluten/pull/1047), velox return null, but the correct answer is NaN.

**Comment by liujiayi771** [comment]
@rui-mo Can you merge PR in oap/velox, and I will revert repo url.

**Comment by rui-mo** [comment]
> @rui-mo Can you merge PR in oap/velox, and I will revert repo url.

@liujiayi771 Merged.

**Review by rui-mo — APPROVED** [review]

**Pull request merged**
