### PR TITLE
[GLUTEN-1690][VL] Header Search Paths do not include the complete velox directory during development

### PR DESCRIPTION
**Pull request by kerwin-zk**
## What changes were proposed in this pull request?
Header Search Paths do not include the complete velox directory during development

### CODE REVIEW

**Comment by kerwin-zk** [comment]
@zhejiangxiaomai @zhztheplayer @zhouyuan cc

**Review by zhztheplayer — DISMISSED** [review]
Can you rebase? Thanks.

**Comment by kerwin-zk** [comment]
> Can you rebase? Thanks.

@zhztheplayer done

**Review by zhztheplayer — APPROVED** [review]
Thank you. Waiting for CI

**Comment by kerwin-zk** [comment]
@zhztheplayer CI is done.

**Review by zhouyuan — APPROVED** [review]

**Pull request merged**
