### PR TITLE
[CH-328] Support function isNaN

### PR DESCRIPTION
**Pull request by exmy**
## What changes were proposed in this pull request?

support function isNaN for ch backend

## How was this patch tested?

unit tests and manual tests

related issue: [issue-328](https://github.com/Kyligence/ClickHouse/issues/328)

### CODE REVIEW

**Comment by exmy** [comment]
test this please

**Comment by zzcclp** [comment]
does this need to modify ch backend too ? 
please rebase

**Comment by exmy** [comment]
> does this need to modify ch backend too ? please rebase

done, and the modify on ch backend have merged in pr: https://github.com/Kyligence/ClickHouse/pull/333

**Comment by zzcclp** [comment]
> > does this need to modify ch backend too ? please rebase
> 
> done, and the modify on ch backend have merged in pr: [Kyligence/ClickHouse#333](https://github.com/Kyligence/ClickHouse/pull/333)

Got it.

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
