### PR TITLE
[GLUTEN-1920][scripts]build/fix: Pass arguments to the child build script from parent script with velox BE

### PR DESCRIPTION
**Pull request by paul-amonson**
## What changes were proposed in this pull request?

Allow the wrapper script "dev/buildbundle-veloxbe.sh" to pass arguments to the child script "dev/builddeps-veloxbe.sh".

Fixes Issue #1920 

## How was this patch tested?
Built using command line "./dev/buildbundle-veloxbe.sh --enable_s3=ON" and verified that S3 Connector was included in the built collateral.

### CODE REVIEW

**Comment by zhouyuan** [comment]
@paul-amonson hi, it looks the script is working on my env
image

**Comment by paul-amonson** [comment]
> @paul-amonson hi, the old script is working on my env(CentOS 7). Could this issue possibility due to the shell other than bash? image

Let me check this, my experience was on Ubuntu 22.04's distribution version of bash.

**Comment by paul-amonson** [comment]
Oh, its working for me too so this fix is not needed. I can close the PR and #1920 can be closed.  Now I need to figure out we during testing there was no S3 connector. I am assuming user error.  ;)  Thanks.

**Comment by paul-amonson** [comment]
Closing as this was NOT the cause of the missing S3 connector in my test.

**Pull request closed without merging**
