### PR TITLE
[CORE] Remove usage limit of NativeMemoryManager#tmpInstance

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

Remove NativeMemoryManager#tmpInstance usage check, make it more flexible, caller should know why use this method clearly.

### CODE REVIEW

**Comment by Yohahaha** [comment]
@zhztheplayer would you help take a look? 

cc @liujiayi771

**Comment by liujiayi771** [comment]
Thanks. This modification makes the use of tmpInstance more flexible.

**Comment by Yohahaha** [comment]
Could you give any feedbacks? @zhztheplayer

**Review by zhztheplayer — APPROVED** [review]
It looks like a patch to loose current restrictions. Any specific reason for the change?

**Comment by Yohahaha** [comment]
> It looks like a patch to loose current restrictions. Any specific reason for the change?

Let this method more flexible, out internal experimental feature need this.

**Pull request merged**
