### PR TITLE
[GLUTEN-1554][CH] Support collect_set

### PR DESCRIPTION
**Pull request by exmy**
## What changes were proposed in this pull request?

(Fixes: #1554)

## How was this patch tested?
ut

### CODE REVIEW

**Comment by exmy** [comment]
https://github.com/Kyligence/ClickHouse/pull/443 The change on Kyli CH is same as `collect_list` cc @lgbo-ustc @zzcclp @liuneng1994

**Comment by lgbo-ustc** [comment]
May add some tests for null values?

**Comment by lgbo-ustc** [comment]
LGTM

**Comment by exmy** [comment]
@rui-mo `Window function not registered: collect_set, Source: USER, ErrorCode: INVALID_ARGUMENT`, it seems velox does't support `collect_set` yet?  Could you help confirm where we can add it to the blacklist? Thanks!

**Comment by rui-mo** [comment]
> @rui-mo `Window function not registered: collect_set, Source: USER, ErrorCode: INVALID_ARGUMENT`, it seems velox does't support `collect_set` yet? Could you help confirm where we can add it to the blacklist? Thanks!

@exmy  OK, I will check that.

**Comment by rui-mo** [comment]
@exmy Could you please rebase this PR? The function on `collect_set` should be fixed.

**Comment by exmy** [comment]
> @exmy Could you please rebase this PR? The function on `collect_set` should be fixed.

now, there is a new error: `Window function not registered: array_distinct` @rui-mo

**Comment by rui-mo** [comment]
Just merged https://github.com/oap-project/velox/pull/350 to fallback collect_set in window.

**Review by rui-mo — APPROVED** [review]

**Comment by rui-mo** [comment]
TODO: test collect_set on Velox backend.

**Pull request merged**
