### PR TITLE
[VL] Use clang-format 12 to format check

### PR DESCRIPTION
**Pull request by zhejiangxiaomai**
## What changes were proposed in this pull request?
use clang-format 12 in GHA.

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by PHILO-HE** [comment]
Please also help update our doc to align with this change, e.g., `NewToGluten.md`. Thanks!

**Comment by zhejiangxiaomai** [comment]
> Please also help update our doc to align with this change, e.g., `NewToGluten.md`. Thanks!

Thanks, Just updated.

**Review by PHILO-HE — APPROVED** [review]

**Comment by zuochunwei** [comment]
Why do we need this version? 
I installed this version failed in our environment machine.

**Comment by zhejiangxiaomai** [comment]
> Why do we need this version? I installed this version failed in our environment machine.

Just keep the same version with meta/velox

**Pull request merged**
