### PR TITLE
[VL] Remove unnecessary registerFileSystem and registerReader

### PR DESCRIPTION
**Pull request by Yohahaha**
These codes already be invoked in velox `HiveConnectorFactory::initialize()` https://github.com/oap-project/velox/blob/b8fc63ec35f049a49e417ba4b0845c2b1e367748/velox/connectors/hive/HiveConnector.cpp#L138-L160

### CODE REVIEW

**Comment by Yohahaha** [comment]
@rui-mo could you help take a look? thanks!

**Review by rui-mo — COMMENTED** [review]
Could you add some background for this change in the PR description? Thanks.

**Comment by Yohahaha** [comment]
> Could you add some background for this change in the PR description? Thanks.

Added.

**Review by rui-mo — APPROVED** [review]

**Comment by Yohahaha** [comment]
Could we merge?

**Review by rui-mo — COMMENTED** [review]
The readers are registered with [Connector.h#L444-L445](https://github.com/oap-project/velox/blob/update/velox/connectors/Connector.h#L444-L445), and we once found static variable was not always reliable as discussed in https://github.com/oap-project/gluten/pull/3442#issuecomment-1772294887. Maybe we need more tests on this PR and https://github.com/oap-project/gluten/pull/3442.

**Comment by zhztheplayer** [comment]
@rui-mo Do we actually have HDFS-based test in GHA CI?

It seems like Velox requires VELOX_ENABLE_HDFS=ON to call `registerHdfsFileSystem` internally. I don't see we set `VELOX_ENABLE_HDFS=ON` at anywhere in our code base. Could you double-check? @Yohahaha

**Comment by rui-mo** [comment]
> @rui-mo Do we actually have HDFS-based test in GHA CI?

Seems there's hdfs-based compilation test, but no execution test.

**Comment by zhztheplayer** [comment]
> The readers are registered with [Connector.h#L444-L445](https://github.com/oap-project/velox/blob/update/velox/connectors/Connector.h#L444-L445), and we once found static variable was not always reliable as discussed in [#3442 (comment)](https://github.com/oap-project/gluten/pull/3442#issuecomment-1772294887). Maybe we need more tests on this PR and #3442.

This PR's changed registration code should be invoked within RAII by Velox so we don't have to worry about the static initialization issue (if it does exist). But we should still have this PR tested with actual HDFS data. @Yohahaha Did you already test the PR?

**Comment by zhztheplayer** [comment]
FWIW, about SIOF https://en.cppreference.com/w/cpp/language/siof

**Comment by Yohahaha** [comment]
> @rui-mo Do we actually have HDFS-based test in GHA CI?
> 
> It seems like Velox requires VELOX_ENABLE_HDFS=ON to call `registerHdfsFileSystem` internally. I don't see we set `VELOX_ENABLE_HDFS=ON` at anywhere in our code base. Could you double-check? @Yohahaha

https://github.com/oap-project/gluten/blob/edc2c538ad02990a933087dbe292dfe109e7d0e0/ep/build-velox/src/build_velox.sh#L97-L99

**Comment by zhztheplayer** [comment]
> > @rui-mo Do we actually have HDFS-based test in GHA CI?
> > It seems like Velox requires VELOX_ENABLE_HDFS=ON to call `registerHdfsFileSystem` internally. I don't see we set `VELOX_ENABLE_HDFS=ON` at anywhere in our code base. Could you double-check? @Yohahaha
> 
> https://github.com/oap-project/gluten/blob/edc2c538ad02990a933087dbe292dfe109e7d0e0/ep/build-velox/src/build_velox.sh#L97-L99

Oops we had it set. So it looks workable to me. Wait for Jenkins result.

**Comment by Yohahaha** [comment]
> > The readers are registered with [Connector.h#L444-L445](https://github.com/oap-project/velox/blob/update/velox/connectors/Connector.h#L444-L445), and we once found static variable was not always reliable as discussed in [#3442 (comment)](https://github.com/oap-project/gluten/pull/3442#issuecomment-1772294887). Maybe we need more tests on this PR and #3442.
> 
> This PR (3445, not 3442)'s changed registration code should be invoked within initialize-on-first-use by Velox so we don't have to worry about the static initialization issue (if it does exist). But we should still have this PR tested with actual HDFS data. @Yohahaha Did you already test the PR?

We always test all patches with HDFS.

**Review by zhztheplayer — APPROVED** [review]

**Pull request merged**
