### PR TITLE
[VL] [Minor] Fix compile error in debug mode

### PR DESCRIPTION
**Pull request by JkSelf**
## What changes were proposed in this pull request?

Fix the following compile error in debug mode.

```
/mnt/DP_disk1/sparkuser/projects/gluten/cpp/velox/compute/VeloxBackend.cc: In member function ‘void gluten::VeloxBackend::init(const std::unordered_map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&)’:
/mnt/DP_disk1/sparkuser/projects/gluten/cpp/velox/compute/VeloxBackend.cc:204:13: error: cannot convert ‘const facebook::velox::Config*’ to ‘const facebook::velox::Config&’
  204 |   printConf(veloxcfg);
      |             ^~~~~~~~
      |             |
      |             const facebook::velox::Config*
/mnt/DP_disk1/sparkuser/projects/gluten/cpp/velox/compute/VeloxBackend.cc:111:61: note:   initializing argument 1 of ‘void gluten::VeloxBackend::printConf(const facebook::velox::Config&)’
  111 | void VeloxBackend::printConf(const facebook::velox::Config& conf) {
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
make[2]: *** [velox/CMakeFiles/velox.dir/build.make:63: velox/CMakeFiles/velox.dir/compute/VeloxBackend.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:192: velox/CMakeFiles/velox.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

## How was this patch tested?

local debug mode compile.

### CODE REVIEW

**Review by zhztheplayer — DISMISSED** [review]
@JkSelf I assume the CI errors are not related?

**Comment by Yohahaha** [comment]
#3748 will remove GLUTEN_PRINT_DEBUG macro in most cases, and refine printConfig usage, maybe we can fix this issue in that patch.

**Comment by Yohahaha** [comment]
#3748 will remove GLUTEN_PRINT_DEBUG macro in most cases, and refine printConfig usage, maybe we can fix this issue in that patch.

**Comment by zhztheplayer** [comment]
@Yohahaha Thanks. And would you like to rebase your work after this patch gets merged? Since this one is very close to being ready.

**Comment by Yohahaha** [comment]
> @Yohahaha Thanks. And would you like to rebase your work after this patch gets merged? Since this one is small and very close to being ready.

OK.

**Review by PHILO-HE — APPROVED** [review]
Looks good! Thanks!

**Comment by zhztheplayer** [comment]
We don't have debug build test on CI yet. Verified locally.

**Pull request merged**
