### PR TITLE
[GLUTEN-1632][CH]Daily Update Clickhouse Version (20230919)

### PR DESCRIPTION
**Pull request by lwz9103**
Auto commit by gluten daily build, please check the build status and merge it if it's green.

### CODE REVIEW

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI

**Comment by lwz9103** [comment]
Run Gluten Clickhouse CI

**Comment by baibaichen** [comment]
we need merge due to https://github.com/ClickHouse/ClickHouse/pull/54651

**Comment by lwz9103** [comment]
Run Gluten Clickhouse CI

**Comment by lgbo-ustc** [comment]
LGTM

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
