### PR TITLE
[GLUTEN-3559][VL] Fix unit tests in GlutenSQLQueryTestSuite suite - Part 1

### PR DESCRIPTION
**Pull request by vibhaska**
## What changes were proposed in this pull request?

This PR enables following tests in the suite GlutenSQLQueryTestSuite:
 - describe-query.sql *** FAILED ***
 - sql-compatibility-functions.sql *** FAILED ***
 - cast.sql *** FAILED ***
 - show-tables.sql *** FAILED ***
 - intersect-all.sql *** FAILED ***
 - cte-nested.sql *** FAILED ***
 - random.sql *** FAILED ***
 - datetime-formatting-invalid.sql *** FAILED ***
 - show-create-table.sql *** FAILED ***
 - cte-nonlegacy.sql *** FAILED ***
 - inline-table.sql *** FAILED ***
 - describe-table-column.sql *** FAILED ***
 - map.sql *** FAILED ***
 - describe.sql *** FAILED ***
 - datetime-parsing-invalid.sql *** FAILED ***
 - show_columns.sql *** FAILED ***
 - comments.sql *** FAILED ***
 - udaf.sql *** FAILED ***
 - json-functions.sql *** FAILED ***
 - describe-table-after-alter-table.sql *** FAILED ***
 - show-tblproperties.sql *** FAILED ***
 - grouping_set.sql *** FAILED ***
 - charvarchar.sql *** FAILED ***
 - table-valued-functions.sql *** FAILED ***
 - regexp-functions.sql *** FAILED ***
 - change-column.sql *** FAILED ***
 - string-functions.sql *** FAILED ***
 - columnresolution-negative.sql *** FAILED ***
 - timestamp-ntz.sql *** FAILED ***
 - interval.sql *** FAILED ***
 - date.sql *** FAILED ***
 - bitwise.sql *** FAILED ***
 - natural-join.sql *** FAILED ***
 - timezone.sql *** FAILED ***
 - datetime-legacy.sql *** FAILED ***
 - csv-functions.sql *** FAILED ***
 - pivot.sql *** FAILED ***
 - group-by-filter.sql *** FAILED ***
 - except-all.sql *** FAILED ***
 - join-lateral.sql *** FAILED ***
 - like-any.sql *** FAILED ***
 - table-aliases.sql *** FAILED ***
 - transform.sql *** FAILED ***
 - query_regex_column.sql *** FAILED ***
 - count.sql *** FAILED ***
 - show-views.sql *** FAILED ***
 - timestamp.sql *** FAILED ***
 - try_arithmetic.sql *** FAILED ***
 - extract.sql *** FAILED ***
 - cte.sql *** FAILED ***
 - cte-legacy.sql *** FAILED ***
 - order-by-ordinal.sql *** FAILED ***
 - literals.sql *** FAILED ***
 - limit.sql *** FAILED ***
 - like-all.sql *** FAILED ***
 - tablesample-negative.sql *** FAILED ***
 - subquery/in-subquery/in-basic.sql *** FAILED ***
 - subquery/negative-cases/subq-input-typecheck.sql *** FAILED ***
 - subquery/negative-cases/invalid-correlation.sql *** FAILED ***
 - postgreSQL/create_view.sql *** FAILED ***
 - postgreSQL/boolean.sql *** FAILED ***
 - postgreSQL/aggregates_part1.sql *** FAILED ***
 - postgreSQL/window_part3.sql *** FAILED ***
 - postgreSQL/strings.sql *** FAILED ***
 - postgreSQL/window_part4.sql *** FAILED ***
 - postgreSQL/int8.sql *** FAILED ***
 - postgreSQL/union.sql *** FAILED ***
 - postgreSQL/aggregates_part4.sql *** FAILED ***
 - postgreSQL/int4.sql *** FAILED ***
 - postgreSQL/numeric.sql *** FAILED ***
 - postgreSQL/window_part2.sql *** FAILED ***
 - postgreSQL/with.sql *** FAILED ***
 - postgreSQL/interval.sql *** FAILED ***
 - postgreSQL/date.sql *** FAILED ***
 - postgreSQL/join.sql *** FAILED ***
 - postgreSQL/select_having.sql *** FAILED ***
 - postgreSQL/text.sql *** FAILED ***
 - postgreSQL/limit.sql *** FAILED ***
 - postgreSQL/float4.sql *** FAILED ***
 - postgreSQL/select_implicit.sql *** FAILED ***
 - postgreSQL/aggregates_part3.sql *** FAILED ***

(Fixes: \#3559)

## How was this patch tested?

Ran this UT to confirm the fix

### CODE REVIEW

**Comment by vibhaska** [comment]
I think CI/CD failures are related to https://github.com/oap-project/gluten/issues/4203. So will wait for its resolution.

**Comment by JkSelf** [comment]
@vibhaska https://github.com/oap-project/gluten/pull/4341 merged. Can you help to rebase? Thanks.

**Comment by vibhaska** [comment]
@JkSelf @zhli1142015 @ayushi-agarwal 

With merge of https://github.com/oap-project/gluten/pull/4293 and https://github.com/oap-project/gluten/pull/4341 now this PR should pass.

But then I realized that https://github.com/oap-project/gluten/blob/main/.github/workflows/velox_be.yml has not been changed. So I did same with additional commit https://github.com/oap-project/gluten/pull/4273/files#diff-92077173e6a535009e50974639976b3c49d45cfb05141bac9d291fc13bb06a8a

But I am seeing failures like,
- SPARK-40280: filter pushdown - int with annotation *** FAILED ***
  org.apache.spark.sql.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/spark342/sql/core/src/test/resources/test-data/tagged_int.parquet
- SPARK-40280: filter pushdown - long with annotation *** FAILED ***
  org.apache.spark.sql.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/spark342/sql/core/src/test/resources/test-data/tagged_long.parquet.
  at
- Gluten - SPARK-23852: Broken Parquet push-down for partially-written stats *** FAILED ***
  org.apache.spark.sql.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/spark342/sql/core/src/test/resources/test-data/parquet-1217.parquet.

Kindly suggest. Is there additional changes expected for https://github.com/oap-project/gluten/issues/4203?

**Comment by vibhaska** [comment]
> @JkSelf @zhli1142015 @ayushi-agarwal
> 
> With merge of #4293 and #4341 now this PR should pass.
> 
> But then I realized that https://github.com/oap-project/gluten/blob/main/.github/workflows/velox_be.yml has not been changed. So I did same with additional commit https://github.com/oap-project/gluten/pull/4273/files#diff-92077173e6a535009e50974639976b3c49d45cfb05141bac9d291fc13bb06a8a
> 
> All expected tests were passing, But I am seeing failures like,
> 
> * SPARK-40280: filter pushdown - int with annotation *** FAILED ***
>   org.apache.spark.sql.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/spark342/sql/core/src/test/resources/test-data/tagged_int.parquet
> * SPARK-40280: filter pushdown - long with annotation *** FAILED ***
>   org.apache.spark.sql.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/spark342/sql/core/src/test/resources/test-data/tagged_long.parquet.
>   at
> * Gluten - SPARK-23852: Broken Parquet push-down for partially-written stats *** FAILED ***
>   org.apache.spark.sql.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/spark342/sql/core/src/test/resources/test-data/parquet-1217.parquet.
> 
> Please note that above missing files are older files from Spark OSS present in both Spark33 and Spark34. So appears to me as cleanup issue. Kindly suggest.
> 
> Is there additional changes expected for #4203?

Thanks @PHILO-HE . One more PR is in making https://github.com/oap-project/gluten/pull/4362/files

**Comment by JkSelf** [comment]
@vibhaska https://github.com/oap-project/gluten/pull/4362/files merged. Can you help to rebase? Thanks.

**Comment by vibhaska** [comment]
Closing in favor of https://github.com/oap-project/gluten/pull/4357

**Pull request closed without merging**
