### PR TITLE
[VL] Add overlay function support for Velox backend

### PR DESCRIPTION
**Pull request by Yohahaha**
## What changes were proposed in this pull request?

Since oap/velox has already include this commit after rebase, let's add it.

## How was this patch tested?

Tested in GlutenStringExpressionsSuite

### CODE REVIEW

**Comment by Yohahaha** [comment]
Hi @PHILO-HE @rui-mo 

This PR is ready for review, would you help take a look?
The reason of CI failure is network problem.

**Review by rui-mo — COMMENTED** [review]
Can we add test for this function to ensure it is offloaded to native?
Eg. https://github.com/oap-project/gluten/blob/main/backends-velox/src/test/scala/io/glutenproject/execution/TestOperator.scala#L472-L477

**Review by rui-mo — COMMENTED** [review]
Please also update this doc on function support, thanks!
https://github.com/oap-project/gluten/blob/main/docs/velox-backend-support-progress.md#function-support

**Comment by Yohahaha** [comment]
Docs and test has already added, please ignore lots of line change of doc, my IDE will auto reformat it and I have no idea to avoid it. :(

**Comment by Yohahaha** [comment]
But seems CI still has network issue.

**Review by PHILO-HE — DISMISSED** [review]
Looks great!

**Review by rui-mo — APPROVED** [review]

**Review by rui-mo — COMMENTED** [review]
Looks the changes on doc is not added for now, is it missing?

**Comment by Yohahaha** [comment]
@rui-mo see this comments, https://github.com/oap-project/gluten/pull/2567#pullrequestreview-1562129569

@PHILO-HE will track the function support state and do a bulk update

**Comment by Yohahaha** [comment]
Thanks for merging!

**Pull request merged**
