### PR TITLE
[cpp] bugfix for splitter::CreateRecordBatchFromBuffer

### PR DESCRIPTION
**Pull request by zuochunwei**
## What changes were proposed in this pull request?
1. add an anonymous namespace for module functions
2. move `sizeof_binary_offset` into the loop to fix a bug of `splitter::CreateRecordBatchFromBuffer`
3. modify the comment to avoid misleading

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by rui-mo** [comment]
@zuochunwei The failed UT is not related to this PR but on the main branch. I will take a look, thanks.
image

**Comment by zuochunwei** [comment]
> @zuochunwei The failed UT is not related to this PR but on the main branch. I will take a look, thanks. image

thanks

**Comment by rui-mo** [comment]
@zuochunwei This issue was fixed, and rebase is needed, thanks.

**Comment by zuochunwei** [comment]
> @zuochunwei This issue was fixed, and rebase is needed, thanks.

OK

**Review by jinchengchenghh — APPROVED** [review]

**Pull request merged**
