### PR TITLE
[GJ-98] Enable TPCH Q6 & Q1 for arrow backend

### PR DESCRIPTION
**Pull request by marin-ma**
Depends on https://github.com/oap-project/arrow/pull/93

### CODE REVIEW

**Comment by zzcclp** [comment]
Please rebase to master.

**Comment by marin-ma** [comment]
@rui-mo @zzcclp Rebase done. Please help review.

**Comment by rui-mo** [comment]
Verified on Velox backend. LGTM.

**Comment by rui-mo** [comment]
Verified on Velox backend. LGTM.

**Comment by zzcclp** [comment]
Verified on ClickHouse backend. LGTM.

**Pull request merged**
