### PR TITLE
[VL] Optimize Velox to Internal Row

### PR DESCRIPTION
**Pull request by FelixYBW**
Optimize Velox to Internal Row. Previously we fill the destination column by column, which can hardly keep destination buffer data in L1 cache, especially when column number increases. But it needn't to flatten the row vector.

    The new method flatten the row vector firstly, then similar as Arrow's C2R, we use a 3 loop to fill the buffer:

    each batch is N rows
    for b in batches:
      for c in b_column:
        for r in rows:
          buf[r][c]=b_column[c]

    The expectation is both src and dst data is only fetched in L1 cache once

Perf:
TPCH LITEITEM table 11 columns
l_orderkey: int64
l_partkey: int64
l_suppkey: int64
l_linenumber: int32
l_quantity: double
l_extendedprice: double
l_discount: double
l_tax: double
l_shipinstruct: string
l_shipmode: string
l_comment: string

<table>
<tr>
	<td> 
	<td> Arrow
	<td> before opt
	<td> after opt
<tr>
	<td> 1 thread
	<td>  7.14s
	<td> 11.3s
	<td> 5.45s
<tr>
    <td> 32 threads
	<td> 49.8s
	<td> 105s
	<td> 65.4s
</table>

TPCH scan only performance test:

<table>
<tr>
	<td> vanilla
	<td> orig
	<td> this PR
<tr>
	<td> 1
	<td> 0.94
	<td> 1.04
</table>

### CODE REVIEW

**Comment by FelixYBW** [comment]
@jinchengchenghh Can you take a look?

**Comment by jinchengchenghh** [comment]
Do you run at the jenkins? Can you backport decimal Velox to row from https://github.com/oap-project/gluten/pull/1176/files#diff-467eb78d0235e3623ad443e886360015d85a71112637cdf5c1aa00721c100d41R174 to here?

**Comment by FelixYBW** [comment]
> Do you run at the jenkins? Can you backport decimal Velox to row from [#1176 (files)](https://github.com/oap-project/gluten/pull/1176/files#diff-467eb78d0235e3623ad443e886360015d85a71112637cdf5c1aa00721c100d41R174) to here?

@JkSelf Can you add UT for decimal VeloxColumnar2Row and VeloxSplitter?

**Comment by FelixYBW** [comment]
> > Do you run at the jenkins? Can you backport decimal Velox to row from [#1176 (files)](https://github.com/oap-project/gluten/pull/1176/files#diff-467eb78d0235e3623ad443e886360015d85a71112637cdf5c1aa00721c100d41R174) to here?
> 
> @JkSelf Can you add UT for decimal VeloxColumnar2Row and VeloxSplitter?

@JkSelf Can you move your VeloxC2R to this PR?

**Comment by FelixYBW** [comment]
> ```
> Optimize Velox to Internal Row. Previously we fill the destination column by column, which can hardly keep destination buffer data in L1 cache, especially when column number increases. But it needn't to flatten the row vector.
> 
> The new method flatten the row vector firstly, then similar as Arrow's C2R, we use a 3 loop to fill the buffer:
> 
> each batch is N rows
> for b in batches:
>   for c in b_column:
>     for r in rows:
>       buf[r][c]=b_column[c]
> 
> The expectation is both src and dst data is only fetched in L1 cache once
> ```
> 
> Perf: TPCH LITEITEM table 11 columns l_orderkey: int64 l_partkey: int64 l_suppkey: int64 l_linenumber: int32 l_quantity: double l_extendedprice: double l_discount: double l_tax: double l_shipinstruct: string l_shipmode: string l_comment: string
> 
> Arrow	before opt	after opt
> 1 thread	7.14s	11.3s	5.45s
> 32 threads	49.8s	105s	65.4s

TPCH

**Comment by JkSelf** [comment]
> > > Do you run at the jenkins? Can you backport decimal Velox to row from [#1176 (files)](https://github.com/oap-project/gluten/pull/1176/files#diff-467eb78d0235e3623ad443e886360015d85a71112637cdf5c1aa00721c100d41R174) to here?
> > 
> > 
> > @JkSelf Can you add UT for decimal VeloxColumnar2Row and VeloxSplitter?
> 
> @JkSelf Can you move your VeloxC2R to this PR?

Sure. I will move the VeloxColumnar2Row with decimal support here and add the UTs later.

**Comment by JkSelf** [comment]
@FelixYBW 
Filed [PR#1](https://github.com/FelixYBW/gluten/pull/1) to add short decimal and long decimal ut for VeloxColumnarToRow and VeloxSplitter. The VeloxColumnarToRow can pass the ut. But it seems there has some issue in VeloxSplitter with decimal type.

**Review by jinchengchenghh — DISMISSED** [review]

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by FelixYBW** [comment]
close the PR, will start a new one

**Pull request closed without merging**
