### PR TITLE
[CORE] Record ignored tests by test framework

### PR DESCRIPTION
**Pull request by Yohahaha**

### CODE REVIEW

**Review by PHILO-HE — APPROVED** [review]
Thanks!

**Comment by PHILO-HE** [comment]
Hi @Yohahaha, do we need to fix this?
https://github.com/oap-project/gluten/blob/main/gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala#L43

**Comment by PHILO-HE** [comment]
> Hi @Yohahaha, do we also need to fix this? https://github.com/oap-project/gluten/blob/main/gluten-ut/common/src/test/scala/org/apache/spark/sql/GlutenSQLTestsBaseTrait.scala#L43

Let's firstly merge this pr. Note anther pr covers this mentioned issue.

**Comment by Yohahaha** [comment]
1,121 tests were ignored.

**Pull request merged**
