### PR TITLE
Optimize VeloxColumnarToRowConverter

### PR DESCRIPTION
**Pull request by zuochunwei**
## What changes were proposed in this pull request?

1. add the keyword `inline` for functions defined in the header file.
2. refactor `getColumnar2RowConverter` by reusing the implementation of the parent class
3. take the check statement out of the `loop` for performance.

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zuochunwei** [comment]
@rui-mo @zhztheplayer @zhejiangxiaomai

**Comment by Yohahaha** [comment]
> ## What changes were proposed in this pull request?
> 1. delete the statement of `memset(buffer_->mutable_data(), 0)` for the consideration of performance, I have made the comparing test, and the result shows it's ok.

I am curious about the specific performance gain, could you paste your test result?

**Comment by zuochunwei** [comment]
> > ## What changes were proposed in this pull request?
> > 
> > 1. delete the statement of `memset(buffer_->mutable_data(), 0)` for the consideration of performance, I have made the comparing test, and the result shows it's ok.
> 
> I am curious about the specific performance gain, could you paste your test result?

I have made the comparing test, which shows that this deletion does not affect the correction.

I sum the  `VeloxColumnarToRowConverter's buffer_` by treating them as an int array, and the result shows the total value is the same before and after deleting.

**Comment by FelixYBW** [comment]
@zhztheplayer Does Velox backend still use the Arrow's columnar to Row? Did we change to Velox's Columnar to Row?

**Comment by zuochunwei** [comment]
> @zhztheplayer Does Velox backend still use the Arrow's columnar to Row? Did we change to Velox's Columnar to Row?

I guess not, because `VeloxBackend::getColumnar2RowConverter()` will return `VeloxColumnarToRowConverter` from the `if` branch.

**Review by zhejiangxiaomai — APPROVED** [review]

**Pull request merged**
