### PR TITLE
[CH-290] support to_date/date_format/trunc/add_months/map_from_arrays/translate

### PR DESCRIPTION
**Pull request by taiyang-li**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

test by CH[[291]]

### CODE REVIEW

**Comment by taiyang-li** [comment]
Notice: must be merge until clickhouse upgrade to 23.2

**Comment by taiyang-li** [comment]
failed uts below becuase current kyligence/clickhouse version hasn't upgraded.
```
2023-02-10T10:41:17.5788065Z - date format *** FAILED ***
2023-02-10T10:41:24.4388233Z - DateFormat *** FAILED ***
2023-02-10T10:42:16.8600320Z - string translate *** FAILED ***
2023-02-10T10:42:36.3554795Z - translate *** FAILED ***
2023-02-10T10:42:37.7256509Z *** 4 TESTS FAILED ***
```

**Comment by taiyang-li** [comment]
6c8aabc15d523e064b78679ce339539


6c8aabc15d523e064b78679ce339539

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
