### PR TITLE
[OPPRO-167] Add output metrics

### PR DESCRIPTION
**Pull request by rui-mo**
## What changes were proposed in this pull request?

Added output rows and batches to each transformer.

## How was this patch tested?

Verified on Jenkins.

### CODE REVIEW

**Review by zzcclp — APPROVED** [review]
LGTM

**Comment by rui-mo** [comment]
Hi @zhztheplayer, I found below error on Github action for this PR. Do you know what the issue refers to, or how to debug it? Thanks.

image

**Comment by zhztheplayer** [comment]
> Hi @zhztheplayer, I found below error on Github action for this PR. Do you know what the issue refers to, or how to debug it? Thanks.

There is an error in CI log
```
java.lang.NullPointerException
	at org.apache.spark.sql.execution.SparkPlan.sparkContext(SparkPlan.scala:67)
	at io.glutenproject.execution.FilterExecBaseTransformer.metrics$lzycompute(BasicPhysicalOperatorTransformer.scala:58)
	at io.glutenproject.execution.FilterExecBaseTransformer.metrics(BasicPhysicalOperatorTransformer.scala:57)
	at org.apache.spark.sql.execution.SparkPlan.longMetric(SparkPlan.scala:135)
	at io.glutenproject.execution.FilterExecBaseTransformer.updateMetrics(BasicPhysicalOperatorTransformer.scala:113)
	at io.glutenproject.execution.WholeStageTransformerExec.updateMetrics(WholeStageTransformerExec.scala:193)
	at io.glutenproject.execution.WholeStageTransformerExec.$anonfun$doExecuteColumnar$3(WholeStageTransformerExec.scala:325)
	at io.glutenproject.backendsapi.velox.VeloxIteratorApi$$anon$2.next(VeloxIteratorApi.scala:252)
	at io.glutenproject.vectorized.CloseableColumnBatchIterator.next(CloseableColumnBatchIterator.scala:53)
	at io.glutenproject.vectorized.CloseableColumnBatchIterator.next(CloseableColumnBatchIterator.scala:30)
	at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40)
	at io.glutenproject.backendsapi.velox.VeloxSparkPlanExecApi.$anonfun$createBroadcastRelation$1(VeloxSparkPlanExecApi.scala:154)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:863)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:863)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by rui-mo** [comment]
> I guess it's related to the lazy keyword used in BasicPhysicalOperatorTransformer
> 
> https://github.com/oap-project/gluten/blob/7bbf25ef2c1b72b8dc5e2585162bc85cb9550608/jvm/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala#L57-L61
> 
> `sparkContext` doesn't seem to be accessible from task thread. It should only be valid for driver thread.

Fixed this issue by call the metric once on driver. Thanks for your great help!

**Pull request merged**
